import type { Line } from "./villagers";

// Every piece of interface copy is Swedish first; English only appears on hover.
export const ui = {
  title: { sv: "Lilla Ö", en: "Little Island" },
  tagline: { sv: "Lär dig svenska på en liten ö.", en: "Learn Swedish on a little island." },
  play: { sv: "Spela", en: "Play" },
  continue: { sv: "Fortsätt", en: "Continue" },
  signIn: { sv: "Logga in och spela", en: "Sign in and play" },
  loading: { sv: "Båten kommer…", en: "The boat is coming…" },
  level: { sv: "Nivå", en: "Level" },
  words: { sv: "ord", en: "words" },
  dictionary: { sv: "Ordbok", en: "Dictionary" },
  soundOn: { sv: "Ljud på", en: "Sound on" },
  soundOff: { sv: "Ljud av", en: "Sound off" },
  musicOn: { sv: "Musik på", en: "Music on" },
  musicOff: { sv: "Musik av", en: "Music off" },
  menu: { sv: "Meny", en: "Menu" },
  signOut: { sv: "Logga ut", en: "Sign out" },
  close: { sv: "Stäng", en: "Close" },
  back: { sv: "Tillbaka", en: "Back" },
  walkHint: { sv: "Gå med W A S D, eller klicka på marken.", en: "Walk with W A S D, or click on the ground." },
  hoverHint: { sv: "Håll musen över ett ord för att se vad det betyder.", en: "Hold the mouse over a word to see what it means." },
  talkTo: (name: string): Line => ({ sv: `Prata med ${name}`, en: `Talk to ${name}` }),
  lookAt: { sv: "Titta", en: "Look" },
  goalTalk: (name: string, place: Line): Line => ({
    sv: `Hitta ${name} vid ${place.sv.toLocaleLowerCase("sv-SE")}`,
    en: `Find ${name} at ${place.en.toLocaleLowerCase("en")}`,
  }),
  goalLearnMore: (name: string): Line => ({ sv: `Lär dig mer av ${name}`, en: `Learn more from ${name}` }),
  goalMeetElin: { sv: "Gå till Elin på bryggan", en: "Walk to Elin on the dock" },
  goalDone: { sv: "Utforska ön och hitta nya ord", en: "Explore the island and find new words" },
  newWord: { sv: "Nytt ord!", en: "New word!" },
  levelUp: { sv: "Ny nivå!", en: "New level!" },
  treeGrows: { sv: "Trädet på torget växer!", en: "The tree in the square is growing!" },
  newFriend: (name: string): Line => ({ sv: `${name} vill träffa dig!`, en: `${name} wants to meet you!` }),
  next: { sv: "Nästa", en: "Next" },
  check: { sv: "Kolla", en: "Check" },
  dontKnow: { sv: "Jag vet inte", en: "I don't know" },
  hint: { sv: "Tips", en: "Hint" },
  listen: { sv: "Lyssna", en: "Listen" },
  slowly: { sv: "Långsamt", en: "Slowly" },
  sayIt: { sv: "Säg det", en: "Say it" },
  listening: { sv: "Jag lyssnar…", en: "I'm listening…" },
  writeSwedish: { sv: "Skriv på svenska…", en: "Write in Swedish…" },
  howDoYouSay: { sv: "Hur säger man", en: "How do you say" },
  sayInSwedish: { sv: "Säg på svenska", en: "Say in Swedish" },
  whatDoesItMean: { sv: "Vad betyder det?", en: "What does it mean?" },
  whatDidYouHear: { sv: "Vad hörde du?", en: "What did you hear?" },
  buildSentence: { sv: "Bygg meningen", en: "Build the sentence" },
  newPhrase: { sv: "Ett nytt uttryck", en: "A new expression" },
  repeatAfterMe: { sv: "Säg efter mig!", en: "Repeat after me!" },
  youSaid: { sv: "Du sa", en: "You said" },
  heardYou: { sv: "Jag hörde", en: "I heard" },
  bye: { sv: "Hej då!", en: "Bye!" },
  again: { sv: "En gång till!", en: "One more time!" },
  talkForReal: { sv: "Prata på riktigt", en: "Talk for real (voice)" },
  chatTyping: { sv: "Chatta", en: "Chat (typing)" },
  yourName: { sv: "Skriv ditt namn…", en: "Write your name…" },
  saving: { sv: "Sparar…", en: "Saving…" },
  xpGained: { sv: "poäng", en: "points" },
  phrases: { sv: "Fraser", en: "Phrases" },
  things: { sv: "Saker på ön", en: "Things on the island" },
  notFound: { sv: "Inte hittad än", en: "Not found yet" },
  notMet: { sv: "Inte lärt än", en: "Not learned yet" },
  connecting: { sv: "Ringer upp…", en: "Calling…" },
  liveNow: { sv: "Prata bara! Jag lyssnar.", en: "Just talk! I'm listening." },
  mute: { sv: "Tyst", en: "Mute" },
  unmute: { sv: "Mikrofon på", en: "Microphone on" },
  endCall: { sv: "Avsluta", en: "End" },
  liveOver: { sv: "Samtalet är slut.", en: "The conversation is over." },
  reflect: { sv: "Vad lärde jag mig?", en: "What did I learn?" },
  typeReply: { sv: "Svara på svenska…", en: "Answer in Swedish…" },
  send: { sv: "Skicka", en: "Send" },
  needsAccount: { sv: "Logga in för att prata på riktigt.", en: "Sign in to talk for real." },
  liveUnavailable: { sv: "Rösten fungerar inte just nu. Vi kan chatta istället!", en: "Voice isn't working right now. We can chat instead!" },
  notReadyToTalk: { sv: "Lär dig lite mer först, sen kan vi prata!", en: "Learn a bit more first, then we can talk!" },
  error: { sv: "Hoppsan! Något gick fel.", en: "Oops! Something went wrong." },
  tryAgain: { sv: "Försök igen", en: "Try again" },
  captions: { sv: "Undertexter", en: "Subtitles" },
  mic: { sv: "Mikrofon", en: "Microphone" },
  youLabel: { sv: "Du", en: "You" },
  stageLabel: { sv: "Växer", en: "Growing" },
  swedishKeys: { sv: "Svenska bokstäver", en: "Swedish letters" },
  controls: { sv: "Kontroller", en: "Controls" },
  controlsMove: { sv: "Gå: W A S D / pilar / klicka", en: "Walk: W A S D / arrows / click" },
  controlsTalk: { sv: "Prata: E / mellanslag", en: "Talk: E / space" },
  controlsCamera: { sv: "Kamera: dra med musen, scrolla för zoom", en: "Camera: drag with the mouse, scroll to zoom" },
  controlsRun: { sv: "Spring: håll Shift", en: "Run: hold Shift" },
} as const;
