import type { Concept, LearnerConceptState } from "@/types/learning";

export const demoConcepts: Concept[] = [
  {
    id: "demo-maaske",
    languageCode: "da",
    slug: "maaske",
    kind: "word",
    canonicalForm: "måske",
    gloss: "maybe",
    description: "A high-frequency adverb for uncertainty or possibility.",
    sortOrder: 10,
  },
  {
    id: "demo-jeg-vil-gerne",
    languageCode: "da",
    slug: "jeg-vil-gerne",
    kind: "chunk",
    canonicalForm: "jeg vil gerne …",
    gloss: "I would like …",
    description: "A productive, polite frame for expressing a wish or request.",
    sortOrder: 20,
  },
  {
    id: "demo-skal-vi-infinitive",
    languageCode: "da",
    slug: "skal-vi-infinitive",
    kind: "construction",
    canonicalForm: "skal vi + infinitiv",
    gloss: "shall we + verb",
    description: "A construction for proposing a shared action.",
    sortOrder: 30,
  },
  {
    id: "demo-polite-request",
    languageCode: "da",
    slug: "polite-request",
    kind: "communicative_function",
    canonicalForm: "en høflig anmodning",
    gloss: "making a polite request",
    description: "Language choices used to ask for something without sounding abrupt.",
    sortOrder: 40,
  },
  {
    id: "demo-soft-d",
    languageCode: "da",
    slug: "soft-d",
    kind: "listening_phenomenon",
    canonicalForm: "blødt d",
    gloss: "soft d",
    description: "A frequent Danish sound that often differs from spelling expectations.",
    sortOrder: 50,
  },
  {
    id: "demo-stoed",
    languageCode: "da",
    slug: "stoed",
    kind: "listening_phenomenon",
    canonicalForm: "stød",
    gloss: "Danish stød",
    description: "A laryngeal feature that shapes distinctions and natural rhythm.",
    sortOrder: 60,
  },
];

export const initialDemoStates: LearnerConceptState[] = [
  {
    conceptId: "demo-maaske",
    recognitionText: 0.76,
    recognitionAudio: 0.48,
    recall: 0.56,
    production: 0.38,
    pronunciation: 0.42,
    automaticity: 0.27,
    contextDiversity: 0.35,
    speakerDiversity: 0.18,
    retrievalLatencyMs: 4100,
    lastExposureAt: "2026-08-06T18:00:00.000Z",
    lastSuccessfulRetrievalAt: "2026-08-06T18:00:00.000Z",
    retrievalStrength: 0.55,
    estimateConfidence: 0.46,
    exposureCount: 8,
    successfulRetrievalCount: 4,
    algorithmVersion: 1,
  },
  {
    conceptId: "demo-jeg-vil-gerne",
    recognitionText: 0.82,
    recognitionAudio: 0.51,
    recall: 0.62,
    production: 0.49,
    pronunciation: 0.36,
    automaticity: 0.31,
    contextDiversity: 0.44,
    speakerDiversity: 0.2,
    retrievalLatencyMs: 5200,
    lastExposureAt: "2026-08-06T18:04:00.000Z",
    lastSuccessfulRetrievalAt: "2026-08-06T18:04:00.000Z",
    retrievalStrength: 0.61,
    estimateConfidence: 0.54,
    exposureCount: 10,
    successfulRetrievalCount: 6,
    algorithmVersion: 1,
  },
  {
    conceptId: "demo-skal-vi-infinitive",
    recognitionText: 0.58,
    recognitionAudio: 0.3,
    recall: 0.29,
    production: 0.21,
    pronunciation: null,
    automaticity: 0.12,
    contextDiversity: 0.2,
    speakerDiversity: null,
    retrievalLatencyMs: 7400,
    lastExposureAt: "2026-08-05T18:00:00.000Z",
    lastSuccessfulRetrievalAt: "2026-08-03T18:00:00.000Z",
    retrievalStrength: 0.3,
    estimateConfidence: 0.34,
    exposureCount: 5,
    successfulRetrievalCount: 2,
    algorithmVersion: 1,
  },
  {
    conceptId: "demo-polite-request",
    recognitionText: 0.48,
    recognitionAudio: null,
    recall: 0.24,
    production: 0.2,
    pronunciation: null,
    automaticity: 0.1,
    contextDiversity: 0.24,
    speakerDiversity: null,
    retrievalLatencyMs: 8100,
    lastExposureAt: "2026-08-05T18:00:00.000Z",
    lastSuccessfulRetrievalAt: null,
    retrievalStrength: 0.23,
    estimateConfidence: 0.24,
    exposureCount: 3,
    successfulRetrievalCount: 1,
    algorithmVersion: 1,
  },
  {
    conceptId: "demo-soft-d",
    recognitionText: null,
    recognitionAudio: 0.2,
    recall: null,
    production: null,
    pronunciation: 0.12,
    automaticity: null,
    contextDiversity: 0.08,
    speakerDiversity: 0.06,
    retrievalLatencyMs: null,
    lastExposureAt: "2026-08-04T18:00:00.000Z",
    lastSuccessfulRetrievalAt: null,
    retrievalStrength: null,
    estimateConfidence: 0.18,
    exposureCount: 2,
    successfulRetrievalCount: 0,
    algorithmVersion: 1,
  },
];

