import { createEmptyState } from "@/lib/learning/model";
import type { Concept, LearnerConceptState } from "@/types/learning";

export const demoConcepts: Concept[] = [
  {
    id: "demo-hej",
    languageCode: "da",
    slug: "hej",
    kind: "word",
    canonicalForm: "hej",
    gloss: "hello",
    description: "The everyday Danish greeting.",
    sortOrder: 61,
  },
  {
    id: "demo-tak",
    languageCode: "da",
    slug: "tak",
    kind: "word",
    canonicalForm: "tak",
    gloss: "thanks",
    description: "A high-frequency word for thanks and polite requests.",
    sortOrder: 62,
  },
  {
    id: "demo-ja",
    languageCode: "da",
    slug: "ja",
    kind: "word",
    canonicalForm: "ja",
    gloss: "yes",
    description: "The basic Danish word for yes.",
    sortOrder: 63,
  },
  {
    id: "demo-nej",
    languageCode: "da",
    slug: "nej",
    kind: "word",
    canonicalForm: "nej",
    gloss: "no",
    description: "The basic Danish word for no.",
    sortOrder: 64,
  },
  {
    id: "demo-kaffe",
    languageCode: "da",
    slug: "kaffe",
    kind: "word",
    canonicalForm: "kaffe",
    gloss: "coffee",
    description: "A common café drink.",
    sortOrder: 91,
  },
  {
    id: "demo-te",
    languageCode: "da",
    slug: "te",
    kind: "word",
    canonicalForm: "te",
    gloss: "tea",
    description: "A common café drink.",
    sortOrder: 92,
  },
  {
    id: "demo-vand",
    languageCode: "da",
    slug: "vand",
    kind: "word",
    canonicalForm: "vand",
    gloss: "water",
    description: "The Danish word for water.",
    sortOrder: 93,
  },
  {
    id: "demo-maelk",
    languageCode: "da",
    slug: "maelk",
    kind: "word",
    canonicalForm: "mælk",
    gloss: "milk",
    description: "The Danish word for milk.",
    sortOrder: 94,
  },
  {
    id: "demo-kanelsnegl",
    languageCode: "da",
    slug: "kanelsnegl",
    kind: "word",
    canonicalForm: "kanelsnegl",
    gloss: "cinnamon roll",
    description: "A familiar Danish cinnamon pastry.",
    sortOrder: 95,
  },
  {
    id: "demo-med-maelk",
    languageCode: "da",
    slug: "med-maelk",
    kind: "chunk",
    canonicalForm: "med mælk",
    gloss: "with milk",
    description: "A small reusable café phrase.",
    sortOrder: 105,
  },
  {
    id: "demo-og-en-kanelsnegl",
    languageCode: "da",
    slug: "og-en-kanelsnegl",
    kind: "chunk",
    canonicalForm: "og en kanelsnegl",
    gloss: "and a cinnamon roll",
    description: "A phrase for adding food to an order.",
    sortOrder: 106,
  },
  {
    id: "demo-cafe-order-drink",
    languageCode: "da",
    slug: "cafe-order-drink",
    kind: "communicative_function",
    canonicalForm: "bestil en drink",
    gloss: "order a drink",
    description: "Ordering a chosen drink naturally.",
    sortOrder: 115,
  },
  {
    id: "demo-cafe-order-food",
    languageCode: "da",
    slug: "cafe-order-food",
    kind: "communicative_function",
    canonicalForm: "bestil noget at spise",
    gloss: "order something to eat",
    description: "Adding food to a café order.",
    sortOrder: 116,
  },
  {
    id: "demo-cafe-ask-bill",
    languageCode: "da",
    slug: "cafe-ask-bill",
    kind: "communicative_function",
    canonicalForm: "bed om regningen",
    gloss: "ask for the bill",
    description: "Finishing a café interaction naturally.",
    sortOrder: 117,
  },
  {
    id: "demo-maaske",
    languageCode: "da",
    slug: "maaske",
    kind: "word",
    canonicalForm: "måske",
    gloss: "maybe",
    description: "A high-frequency adverb for uncertainty or possibility.",
    sortOrder: 10,
  },
  {
    id: "demo-jeg-vil-gerne",
    languageCode: "da",
    slug: "jeg-vil-gerne",
    kind: "chunk",
    canonicalForm: "jeg vil gerne …",
    gloss: "I would like …",
    description: "A productive, polite frame for expressing a wish or request.",
    sortOrder: 20,
  },
  {
    id: "demo-skal-vi-infinitive",
    languageCode: "da",
    slug: "skal-vi-infinitive",
    kind: "construction",
    canonicalForm: "skal vi + infinitiv",
    gloss: "shall we + verb",
    description: "A construction for proposing a shared action.",
    sortOrder: 30,
  },
  {
    id: "demo-polite-request",
    languageCode: "da",
    slug: "polite-request",
    kind: "communicative_function",
    canonicalForm: "en høflig anmodning",
    gloss: "making a polite request",
    description: "Language choices used to ask for something without sounding abrupt.",
    sortOrder: 40,
  },
  {
    id: "demo-soft-d",
    languageCode: "da",
    slug: "soft-d",
    kind: "listening_phenomenon",
    canonicalForm: "blødt d",
    gloss: "soft d",
    description: "A frequent Danish sound that often differs from spelling expectations.",
    sortOrder: 50,
  },
  {
    id: "demo-stoed",
    languageCode: "da",
    slug: "stoed",
    kind: "listening_phenomenon",
    canonicalForm: "stød",
    gloss: "Danish stød",
    description: "A laryngeal feature that shapes distinctions and natural rhythm.",
    sortOrder: 60,
  },
  {
    id: "demo-jeg-hedder",
    languageCode: "da",
    slug: "jeg-hedder",
    kind: "chunk",
    canonicalForm: "jeg hedder …",
    gloss: "my name is …",
    description: "The everyday Danish frame for introducing yourself.",
    sortOrder: 70,
  },
  {
    id: "demo-hvad-hedder-du",
    languageCode: "da",
    slug: "hvad-hedder-du",
    kind: "chunk",
    canonicalForm: "hvad hedder du?",
    gloss: "what is your name?",
    description: "A common question when meeting someone.",
    sortOrder: 80,
  },
  {
    id: "demo-hyggeligt-at-moede-dig",
    languageCode: "da",
    slug: "hyggeligt-at-moede-dig",
    kind: "chunk",
    canonicalForm: "hyggeligt at møde dig",
    gloss: "nice to meet you",
    description: "A warm response to an introduction.",
    sortOrder: 90,
  },
  {
    id: "demo-en-kaffe-tak",
    languageCode: "da",
    slug: "en-kaffe-tak",
    kind: "chunk",
    canonicalForm: "en kaffe, tak",
    gloss: "a coffee, please",
    description: "A concise café order.",
    sortOrder: 100,
  },
  {
    id: "demo-jeg-tager",
    languageCode: "da",
    slug: "jeg-tager",
    kind: "construction",
    canonicalForm: "jeg tager …",
    gloss: "I’ll have …",
    description: "A relaxed way to choose something.",
    sortOrder: 110,
  },
  {
    id: "demo-regningen-tak",
    languageCode: "da",
    slug: "regningen-tak",
    kind: "chunk",
    canonicalForm: "må jeg bede om regningen?",
    gloss: "may I have the bill?",
    description: "A polite way to ask for the bill.",
    sortOrder: 120,
  },
  {
    id: "demo-hvor-er-stationen",
    languageCode: "da",
    slug: "hvor-er-stationen",
    kind: "chunk",
    canonicalForm: "hvor er stationen?",
    gloss: "where is the station?",
    description: "A practical question for finding your way.",
    sortOrder: 130,
  },
  {
    id: "demo-toget-til-koebenhavn",
    languageCode: "da",
    slug: "toget-til-koebenhavn",
    kind: "chunk",
    canonicalForm: "går dette tog til København?",
    gloss: "does this train go to Copenhagen?",
    description: "A useful route-checking question.",
    sortOrder: 140,
  },
  {
    id: "demo-jeg-skal-af-her",
    languageCode: "da",
    slug: "jeg-skal-af-her",
    kind: "chunk",
    canonicalForm: "jeg skal af her",
    gloss: "I need to get off here",
    description: "Used when leaving a bus or train.",
    sortOrder: 150,
  },
  {
    id: "demo-jeg-forstaar-ikke",
    languageCode: "da",
    slug: "jeg-forstaar-ikke",
    kind: "chunk",
    canonicalForm: "jeg forstår ikke",
    gloss: "I don’t understand",
    description: "A direct way to repair a difficult conversation.",
    sortOrder: 160,
  },
  {
    id: "demo-kan-du-gentage",
    languageCode: "da",
    slug: "kan-du-gentage",
    kind: "chunk",
    canonicalForm: "kan du gentage det?",
    gloss: "can you repeat that?",
    description: "A request to hear something again.",
    sortOrder: 170,
  },
  {
    id: "demo-tal-langsommere",
    languageCode: "da",
    slug: "tal-langsommere",
    kind: "chunk",
    canonicalForm: "kan du tale lidt langsommere?",
    gloss: "can you speak a little more slowly?",
    description: "A polite request to slow down.",
    sortOrder: 180,
  },
];

const legacyInitialDemoStates = [
  {
    conceptId: "demo-maaske",
    recognitionText: 0.76,
    recognitionAudio: 0.48,
    recall: 0.56,
    production: 0.38,
    pronunciation: 0.42,
    automaticity: 0.27,
    contextDiversity: 0.35,
    speakerDiversity: 0.18,
    retrievalLatencyMs: 4100,
    lastExposureAt: "2026-08-06T18:00:00.000Z",
    lastSuccessfulRetrievalAt: "2026-08-06T18:00:00.000Z",
    retrievalStrength: 0.55,
    estimateConfidence: 0.46,
    exposureCount: 8,
    successfulRetrievalCount: 4,
    algorithmVersion: 2,
  },
  {
    conceptId: "demo-jeg-vil-gerne",
    recognitionText: 0.82,
    recognitionAudio: 0.51,
    recall: 0.62,
    production: 0.49,
    pronunciation: 0.36,
    automaticity: 0.31,
    contextDiversity: 0.44,
    speakerDiversity: 0.2,
    retrievalLatencyMs: 5200,
    lastExposureAt: "2026-08-06T18:04:00.000Z",
    lastSuccessfulRetrievalAt: "2026-08-06T18:04:00.000Z",
    retrievalStrength: 0.61,
    estimateConfidence: 0.54,
    exposureCount: 10,
    successfulRetrievalCount: 6,
    algorithmVersion: 2,
  },
  {
    conceptId: "demo-skal-vi-infinitive",
    recognitionText: 0.58,
    recognitionAudio: 0.3,
    recall: 0.29,
    production: 0.21,
    pronunciation: null,
    automaticity: 0.12,
    contextDiversity: 0.2,
    speakerDiversity: null,
    retrievalLatencyMs: 7400,
    lastExposureAt: "2026-08-05T18:00:00.000Z",
    lastSuccessfulRetrievalAt: "2026-08-03T18:00:00.000Z",
    retrievalStrength: 0.3,
    estimateConfidence: 0.34,
    exposureCount: 5,
    successfulRetrievalCount: 2,
    algorithmVersion: 2,
  },
  {
    conceptId: "demo-polite-request",
    recognitionText: 0.48,
    recognitionAudio: null,
    recall: 0.24,
    production: 0.2,
    pronunciation: null,
    automaticity: 0.1,
    contextDiversity: 0.24,
    speakerDiversity: null,
    retrievalLatencyMs: 8100,
    lastExposureAt: "2026-08-05T18:00:00.000Z",
    lastSuccessfulRetrievalAt: null,
    retrievalStrength: 0.23,
    estimateConfidence: 0.24,
    exposureCount: 3,
    successfulRetrievalCount: 1,
    algorithmVersion: 2,
  },
  {
    conceptId: "demo-soft-d",
    recognitionText: null,
    recognitionAudio: 0.2,
    recall: null,
    production: null,
    pronunciation: 0.12,
    automaticity: null,
    contextDiversity: 0.08,
    speakerDiversity: 0.06,
    retrievalLatencyMs: null,
    lastExposureAt: "2026-08-04T18:00:00.000Z",
    lastSuccessfulRetrievalAt: null,
    retrievalStrength: null,
    estimateConfidence: 0.18,
    exposureCount: 2,
    successfulRetrievalCount: 0,
    algorithmVersion: 2,
  },
];

export const initialDemoStates: LearnerConceptState[] = legacyInitialDemoStates.map(
  (state) => ({
    ...createEmptyState(state.conceptId),
    ...state,
    algorithmVersion: 2,
  }),
);
