import type { Lesson, ListenSpeakItem } from "./course.ts";

const sofie = "sv-SE-SofieNeural" as const;
const mattias = "sv-SE-MattiasNeural" as const;

export const swedishLessons: Lesson[] = [
  {
    id: "sv-first-words",
    number: 1,
    title: "First words",
    description: "Start with four everyday words.",
    exercises: [
      {
        conceptSlug: "hej",
        audioId: "sv-learn-hej",
        voice: sofie,
        mode: "repeat",
        eyebrow: "Greet someone",
        prompt: "Hello",
        expected: "Hej.",
        note: "Hej is the everyday Swedish hello.",
      },
      {
        conceptSlug: "tack",
        audioId: "sv-learn-tack",
        voice: mattias,
        mode: "repeat",
        eyebrow: "Be polite",
        prompt: "Thanks",
        expected: "Tack.",
        note: "Tack means thanks and also softens short requests.",
      },
      {
        conceptSlug: "ja",
        audioId: "sv-learn-ja",
        voice: sofie,
        mode: "repeat",
        eyebrow: "Say yes",
        prompt: "Yes",
        expected: "Ja.",
        note: "Ja means yes.",
      },
      {
        conceptSlug: "nej",
        audioId: "sv-learn-nej",
        voice: mattias,
        mode: "repeat",
        eyebrow: "Say no",
        prompt: "No",
        expected: "Nej.",
        note: "Nej means no.",
      },
    ],
  },
  {
    id: "sv-meet-someone",
    number: 2,
    title: "Meet someone",
    description: "Build a short introduction.",
    support: {
      title: "Introductions",
      words: [
        { target: "hej", english: "hello" },
        { target: "jag", english: "I" },
        { target: "du", english: "you" },
        { target: "namn", english: "name" },
      ],
      starters: [
        { target: "Jag heter …", english: "My name is …" },
        { target: "Vad heter du?", english: "What is your name?" },
      ],
    },
    exercises: [
      {
        conceptSlug: "jag-heter",
        audioId: "sv-learn-jag-heter",
        voice: mattias,
        mode: "guided",
        eyebrow: "Introduce yourself",
        prompt: "Say your name.",
        expected: "Hej, jag heter Caleb.",
        note: "Jag heter … is the normal way to introduce yourself.",
      },
      {
        conceptSlug: "vad-heter-du",
        audioId: "sv-learn-vad-heter-du",
        voice: sofie,
        mode: "guided",
        eyebrow: "Ask their name",
        prompt: "Ask their name.",
        expected: "Vad heter du?",
        note: "Use this after your own introduction.",
      },
      {
        conceptSlug: "trevligt-att-traeffas",
        audioId: "sv-learn-trevligt-att-traeffas",
        voice: mattias,
        mode: "guided",
        eyebrow: "Respond warmly",
        prompt: "Say nice to meet you.",
        expected: "Trevligt att träffas.",
        note: "This is the standard warm response to an introduction.",
      },
    ],
  },
  {
    id: "sv-cafe-words",
    number: 3,
    title: "Café words",
    description: "Learn what is on the menu.",
    support: {
      title: "Menu",
      words: [
        { target: "kaffe", english: "coffee" },
        { target: "te", english: "tea" },
        { target: "vatten", english: "water" },
        { target: "mjölk", english: "milk" },
        { target: "kanelbulle", english: "cinnamon bun" },
      ],
    },
    exercises: [
      {
        conceptSlug: "kaffe",
        audioId: "sv-learn-kaffe",
        voice: sofie,
        mode: "repeat",
        eyebrow: "A drink",
        prompt: "Coffee",
        expected: "Kaffe.",
        note: "Kaffe means coffee.",
      },
      {
        conceptSlug: "te",
        audioId: "sv-learn-te",
        voice: mattias,
        mode: "repeat",
        eyebrow: "A drink",
        prompt: "Tea",
        expected: "Te.",
        note: "Te means tea.",
      },
      {
        conceptSlug: "vatten",
        audioId: "sv-learn-vatten",
        voice: sofie,
        mode: "repeat",
        eyebrow: "A drink",
        prompt: "Water",
        expected: "Vatten.",
        note: "Vatten means water.",
      },
      {
        conceptSlug: "mjoelk",
        audioId: "sv-learn-mjoelk",
        voice: mattias,
        mode: "repeat",
        eyebrow: "An extra",
        prompt: "Milk",
        expected: "Mjölk.",
        note: "Mjölk means milk.",
      },
      {
        conceptSlug: "kanelbulle",
        audioId: "sv-learn-kanelbulle",
        voice: sofie,
        mode: "repeat",
        eyebrow: "Something sweet",
        prompt: "Cinnamon bun",
        expected: "Kanelbulle.",
        note: "A kanelbulle is a classic Swedish cinnamon bun.",
      },
    ],
  },
  {
    id: "sv-build-an-order",
    number: 4,
    title: "Build an order",
    description: "Combine the café words.",
    support: {
      title: "Café",
      idea: "Try coffee with milk and a pastry.",
      words: [
        { target: "kaffe", english: "coffee" },
        { target: "te", english: "tea" },
        { target: "vatten", english: "water" },
        { target: "mjölk", english: "milk" },
        { target: "kanelbulle", english: "cinnamon bun" },
      ],
      starters: [
        { target: "Jag skulle vilja ha …", english: "I would like …" },
        { target: "… med mjölk", english: "… with milk" },
        { target: "Och en …", english: "And a …" },
      ],
    },
    exercises: [
      {
        conceptSlug: "jag-skulle-vilja",
        audioId: "sv-learn-jag-skulle-vilja",
        voice: mattias,
        mode: "guided",
        eyebrow: "Start the order",
        prompt: "Ask for a coffee.",
        expected: "Jag skulle vilja ha en kaffe.",
        note: "Jag skulle vilja ha … starts a polite order.",
      },
      {
        conceptSlug: "med-mjoelk",
        audioId: "sv-learn-med-mjoelk",
        voice: sofie,
        mode: "guided",
        eyebrow: "Change the drink",
        prompt: "Add milk.",
        expected: "En kaffe med mjölk.",
        note: "Med means with.",
      },
      {
        conceptSlug: "och-en-kanelbulle",
        audioId: "sv-learn-och-en-kanelbulle",
        voice: mattias,
        mode: "guided",
        eyebrow: "Add food",
        prompt: "Add a cinnamon bun.",
        expected: "Och en kanelbulle, tack.",
        note: "Och means and; tack finishes the order politely.",
      },
    ],
  },
  {
    id: "sv-at-the-cafe",
    number: 5,
    title: "At the café",
    description: "Choose what you want and order naturally.",
    support: {
      title: "Menu",
      idea: "Choose any combination from the menu.",
      words: [
        { target: "kaffe", english: "coffee" },
        { target: "te", english: "tea" },
        { target: "vatten", english: "water" },
        { target: "mjölk", english: "milk" },
        { target: "kanelbulle", english: "cinnamon bun" },
      ],
      starters: [
        { target: "Jag skulle vilja ha …", english: "I would like …" },
        { target: "Kan jag få …", english: "Can I have …" },
        { target: "Notan, tack.", english: "The bill, please." },
      ],
    },
    exercises: [
      {
        conceptSlug: "cafe-order-drink",
        audioId: "sv-learn-cafe-order-drink",
        voice: sofie,
        mode: "open",
        eyebrow: "Order a drink",
        prompt: "Order any drink.",
        expected: "Jag skulle vilja ha en kaffe med mjölk, tack.",
        note: "Choose anything from the menu and order it your way.",
      },
      {
        conceptSlug: "cafe-order-food",
        audioId: "sv-learn-cafe-order-food",
        voice: mattias,
        mode: "open",
        eyebrow: "Add something",
        prompt: "Add something to eat.",
        expected: "Och en kanelbulle, tack.",
        note: "Add any food you know; a different natural answer is welcome.",
      },
      {
        conceptSlug: "cafe-ask-bill",
        audioId: "sv-learn-cafe-ask-bill",
        voice: sofie,
        mode: "open",
        eyebrow: "Finish",
        prompt: "Ask for the bill.",
        expected: "Kan jag få notan, tack?",
        note: "Notan, tack is also natural and completely acceptable.",
      },
    ],
  },
  {
    id: "sv-getting-around",
    number: 6,
    title: "Getting around",
    description: "Find the station and the right train.",
    support: {
      title: "Transport",
      words: [
        { target: "station", english: "station" },
        { target: "tåg", english: "train" },
        { target: "biljett", english: "ticket" },
        { target: "hållplats", english: "stop" },
      ],
      starters: [
        { target: "Var ligger …?", english: "Where is …?" },
        { target: "Går det här tåget till …?", english: "Does this train go to …?" },
      ],
    },
    exercises: [
      {
        conceptSlug: "var-ligger-stationen",
        audioId: "sv-learn-var-ligger-stationen",
        voice: mattias,
        mode: "guided",
        eyebrow: "Find the station",
        prompt: "Ask where the station is.",
        expected: "Var ligger stationen?",
        note: "Var ligger … asks where a place is located.",
      },
      {
        conceptSlug: "taget-till-stockholm",
        audioId: "sv-learn-taget-till-stockholm",
        voice: sofie,
        mode: "open",
        eyebrow: "Check the train",
        prompt: "Check this train goes to Stockholm.",
        expected: "Går det här tåget till Stockholm?",
        note: "Replace Stockholm with any destination you need.",
      },
      {
        conceptSlug: "jag-ska-av-haer",
        audioId: "sv-learn-jag-ska-av-haer",
        voice: mattias,
        mode: "guided",
        eyebrow: "Your stop",
        prompt: "Say you need to get off here.",
        expected: "Jag ska av här.",
        note: "Ska av means need to get off.",
      },
    ],
  },
  {
    id: "sv-when-you-need-help",
    number: 7,
    title: "Need help",
    description: "Slow down a difficult conversation.",
    support: {
      title: "Help",
      words: [
        { target: "förstår", english: "understand" },
        { target: "upprepa", english: "repeat" },
        { target: "långsamt", english: "slowly" },
      ],
      starters: [
        { target: "Jag förstår inte.", english: "I do not understand." },
        { target: "Kan du …?", english: "Can you …?" },
      ],
    },
    exercises: [
      {
        conceptSlug: "jag-foerstar-inte",
        audioId: "sv-learn-jag-foerstar-inte",
        voice: sofie,
        mode: "repeat",
        eyebrow: "Be honest",
        prompt: "I don't understand",
        expected: "Jag förstår inte.",
        note: "This quickly resets a difficult conversation.",
      },
      {
        conceptSlug: "kan-du-upprepa",
        audioId: "sv-learn-kan-du-upprepa",
        voice: mattias,
        mode: "guided",
        eyebrow: "Try again",
        prompt: "Ask them to repeat.",
        expected: "Kan du upprepa det?",
        note: "Upprepa means repeat.",
      },
      {
        conceptSlug: "prata-langsammare",
        audioId: "sv-learn-prata-langsammare",
        voice: sofie,
        mode: "open",
        eyebrow: "Slow down",
        prompt: "Ask them to speak more slowly.",
        expected: "Kan du prata lite långsammare?",
        note: "Lite makes the request softer.",
      },
    ],
  },
  {
    id: "sv-make-plans",
    number: 8,
    title: "Make plans",
    description: "Keep an answer open and suggest an idea.",
    support: {
      title: "Plans",
      words: [
        { target: "kanske", english: "maybe" },
        { target: "tåg", english: "train" },
        { target: "i morgon", english: "tomorrow" },
      ],
      starters: [
        { target: "Kanske …", english: "Maybe …" },
        { target: "Ska vi …?", english: "Shall we …?" },
      ],
    },
    exercises: [
      {
        conceptSlug: "kanske",
        audioId: "sv-learn-kanske",
        voice: mattias,
        mode: "repeat",
        eyebrow: "Keep it open",
        prompt: "Maybe",
        expected: "Kanske.",
        note: "Kanske can stand alone or start a longer answer.",
      },
      {
        conceptSlug: "ska-vi-infinitive",
        audioId: "sv-learn-ska-vi-ta-taget",
        voice: sofie,
        mode: "open",
        eyebrow: "Suggest a plan",
        prompt: "Suggest taking the train.",
        expected: "Ska vi ta tåget?",
        note: "Ska vi + a verb suggests doing something together.",
      },
    ],
  },
];

export const swedishListenSpeakItems: ListenSpeakItem[] = [
  {
    id: "sv-maybe-later",
    conceptSlug: "kanske",
    audioId: "sv-listen-kanske-senare",
    voice: sofie,
    text: "Kanske senare.",
    meaning: "Maybe later.",
    options: ["Maybe later.", "See you tomorrow.", "It is already late."],
  },
  {
    id: "sv-maybe-tomorrow",
    conceptSlug: "kanske",
    audioId: "sv-listen-kanske-i-morgon",
    voice: mattias,
    text: "Kanske i morgon.",
    meaning: "Maybe tomorrow.",
    options: ["Maybe tomorrow.", "Tomorrow morning.", "Not tomorrow."],
  },
  {
    id: "sv-yes-maybe",
    conceptSlug: "kanske",
    audioId: "sv-listen-ja-kanske",
    voice: sofie,
    text: "Ja, kanske.",
    meaning: "Yes, maybe.",
    options: ["Yes, maybe.", "Yes, of course.", "No, maybe not."],
  },
  {
    id: "sv-anna-introduction",
    conceptSlug: "jag-heter",
    audioId: "sv-listen-jag-heter-anna",
    voice: mattias,
    text: "Hej, jag heter Anna.",
    meaning: "Hi, my name is Anna.",
    options: ["Hi, my name is Anna.", "Anna is over here.", "Hi, do you know Anna?"],
  },
  {
    id: "sv-erik-introduction",
    conceptSlug: "jag-heter",
    audioId: "sv-listen-jag-heter-erik",
    voice: sofie,
    text: "Jag heter Erik.",
    meaning: "My name is Erik.",
    options: ["My name is Erik.", "I know Erik.", "Erik is here."],
  },
  {
    id: "sv-sara-introduction",
    conceptSlug: "jag-heter",
    audioId: "sv-listen-hej-jag-heter-sara",
    voice: mattias,
    text: "Hej, jag heter Sara.",
    meaning: "Hi, my name is Sara.",
    options: ["Hi, my name is Sara.", "Hi Sara, come in.", "Sara says hello."],
  },
  {
    id: "sv-coffee-request",
    conceptSlug: "jag-skulle-vilja",
    audioId: "sv-listen-jag-skulle-vilja-kaffe",
    voice: sofie,
    text: "Jag skulle vilja ha en kaffe.",
    meaning: "I would like a coffee.",
    options: ["I would like a coffee.", "I have already had coffee.", "Is the coffee ready?"],
  },
  {
    id: "sv-tea-request",
    conceptSlug: "jag-skulle-vilja",
    audioId: "sv-listen-jag-skulle-vilja-te",
    voice: mattias,
    text: "Jag skulle vilja ha te.",
    meaning: "I would like tea.",
    options: ["I would like tea.", "The tea is cold.", "Do you have coffee?"],
  },
  {
    id: "sv-ticket-request",
    conceptSlug: "jag-skulle-vilja",
    audioId: "sv-listen-jag-skulle-vilja-biljett",
    voice: sofie,
    text: "Jag skulle vilja ha en biljett.",
    meaning: "I would like a ticket.",
    options: ["I would like a ticket.", "I have lost my ticket.", "The ticket is expensive."],
  },
  {
    id: "sv-find-station",
    conceptSlug: "var-ligger-stationen",
    audioId: "sv-listen-var-ligger-stationen",
    voice: mattias,
    text: "Var ligger stationen?",
    meaning: "Where is the station?",
    options: ["Where is the station?", "When does the train leave?", "Is this the last station?"],
  },
  {
    id: "sv-find-toilet",
    conceptSlug: "var-ligger-stationen",
    audioId: "sv-listen-var-ligger-toaletten",
    voice: sofie,
    text: "Var ligger toaletten?",
    meaning: "Where is the toilet?",
    options: ["Where is the toilet?", "Is the toilet free?", "The toilet is over there."],
  },
  {
    id: "sv-find-bus-stop",
    conceptSlug: "var-ligger-stationen",
    audioId: "sv-listen-var-ligger-busshallplatsen",
    voice: mattias,
    text: "Var ligger busshållplatsen?",
    meaning: "Where is the bus stop?",
    options: ["Where is the bus stop?", "The bus has stopped.", "When is the next bus?"],
  },
  {
    id: "sv-repeat-that",
    conceptSlug: "kan-du-upprepa",
    audioId: "sv-listen-kan-du-upprepa-det",
    voice: sofie,
    text: "Kan du upprepa det?",
    meaning: "Can you repeat that?",
    options: ["Can you repeat that?", "Can you explain that?", "Can you write that?"],
  },
  {
    id: "sv-repeat-slowly",
    conceptSlug: "kan-du-upprepa",
    audioId: "sv-listen-kan-du-upprepa-langsamt",
    voice: mattias,
    text: "Kan du upprepa det långsamt?",
    meaning: "Can you repeat that slowly?",
    options: ["Can you repeat that slowly?", "Can you speak louder?", "Can you wait a moment?"],
  },
  {
    id: "sv-repeat-question",
    conceptSlug: "kan-du-upprepa",
    audioId: "sv-listen-kan-du-upprepa-fragan",
    voice: sofie,
    text: "Kan du upprepa frågan?",
    meaning: "Can you repeat the question?",
    options: ["Can you repeat the question?", "Can you answer the question?", "Can you write the question?"],
  },
  {
    id: "sv-get-off-here",
    conceptSlug: "jag-ska-av-haer",
    audioId: "sv-listen-jag-ska-av-haer",
    voice: mattias,
    text: "Jag ska av här.",
    meaning: "I need to get off here.",
    options: ["I need to get off here.", "I am getting on here.", "I will wait here."],
  },
  {
    id: "sv-get-off-next-stop",
    conceptSlug: "jag-ska-av-haer",
    audioId: "sv-listen-jag-ska-av-naesta-hallplats",
    voice: sofie,
    text: "Jag ska av vid nästa hållplats.",
    meaning: "I need to get off at the next stop.",
    options: ["I need to get off at the next stop.", "I got on at the last stop.", "The next stop is closed."],
  },
  {
    id: "sv-get-off-now",
    conceptSlug: "jag-ska-av-haer",
    audioId: "sv-listen-vi-ska-av-nu",
    voice: mattias,
    text: "Vi ska av nu.",
    meaning: "We need to get off now.",
    options: ["We need to get off now.", "We need to wait here.", "We are leaving now."],
  },
];
