import type { SceneBeat } from "@/lib/game/scenes";

// Scenes for the units added when the course grew to A2: a few key phrases
// per unit, each played out twice. Other phrases are practised as lessons.

type Beats = Record<string, SceneBeat[]>;

// ---------- Elin: greetings and introductions ----------

export const elin: Beats = {
  "hej-daa": [
    {
      situation: "Anna is boarding the ferry home.",
      speaker: "Anna",
      cue: { t: "Nu går båten. Hej då!", en: "The boat's leaving. Bye!" },
      reaction: { t: "Hej då! Vi ses i sommar!", en: "Bye! See you this summer!" },
      accept: ["^hej ?då\\b", "^(vi ses|ha det bra)\\b"],
      notWith: ["vi-ses", "ha-det-bra"],
      pitch: 1.2,
    },
    {
      situation: "Lisa has to run home for dinner.",
      speaker: "Lisa",
      cue: { t: "Jag måste gå hem nu!", en: "I have to go home now!" },
      reaction: { t: "Hej då! Vi ses imorgon!", en: "Bye! See you tomorrow!" },
      accept: ["^hej ?då\\b", "^(vi ses|ha det bra)\\b"],
      notWith: ["vi-ses", "ha-det-bra"],
      pitch: 1.45,
    },
  ],
  "god-morgon": [
    {
      situation: "Seven in the morning. Nils walks past with his fishing rod.",
      speaker: "Nils",
      cue: { t: "God morgon! Du är tidigt uppe!", en: "Good morning! You're up early!" },
      reaction: { t: "Ja, fisken väntar!", en: "Yes, the fish are waiting!" },
      accept: ["^god morgon\\b"],
      pitch: 0.8,
    },
    {
      situation: "Elin is opening the harbour office with a cup of coffee.",
      speaker: "Elin",
      cue: { t: "God morgon! Har du sovit gott?", en: "Good morning! Did you sleep well?" },
      reaction: { t: "Vad bra! Kaffe finns på kaféet.", en: "Good! There's coffee at the café." },
      accept: ["^god morgon\\b"],
    },
  ],
  "hur-maar-du": [
    {
      situation: "Elin waves at you from the dock. Ask how she is.",
      speaker: "Elin",
      cue: { t: "Hej! Kul att se dig!", en: "Hi! Nice to see you!" },
      reaction: { t: "Jag mår bra, tack! Och du?", en: "I'm well, thanks! And you?" },
      accept: ["^(hej )?hur mår du\\b", "^(hej )?hur är det\\b"],
      notWith: ["hur-aer-det"],
    },
    {
      situation: "Astrid sits down on a bench with a sigh. Ask how she is.",
      speaker: "Astrid",
      cue: { t: "Oj, vilken lång dag.", en: "Oh, what a long day." },
      reaction: { t: "Lite trött, men glad!", en: "A bit tired, but happy!" },
      accept: ["^(hej )?hur mår du\\b", "^(hej )?hur är det\\b"],
      notWith: ["hur-aer-det"],
      pitch: 0.95,
    },
  ],
  "bra-tack": [
    {
      situation: "Bosse is sweeping outside the café.",
      speaker: "Bosse",
      cue: { t: "Hej! Hur mår du idag?", en: "Hi! How are you today?" },
      reaction: { t: "Vad skönt att höra!", en: "Great to hear!" },
      accept: ["^(jag mår )?(bra|jättebra|fint)( tack)?"],
      pitch: 0.8,
    },
    {
      situation: "The ferry captain leans over the railing.",
      speaker: "Kaptenen",
      cue: { t: "Hej där! Hur är det?", en: "Hi there! How's it going?" },
      reaction: { t: "Fint! Välkommen ombord nästa gång!", en: "Great! Welcome aboard next time!" },
      accept: ["^(jag mår )?(bra|jättebra|fint)( tack)?"],
      pitch: 0.7,
    },
  ],
  foerlaat: [
    {
      situation: "You bump into Erik and step on his foot.",
      speaker: "Erik",
      cue: { t: "Aj! Min fot!", en: "Ouch! My foot!" },
      reaction: { t: "Ingen fara!", en: "No worries!" },
      accept: ["^(förlåt|ursäkta)\\b"],
      notWith: ["ursaekta"],
      pitch: 0.85,
    },
    {
      situation: "You're twenty minutes late to meet Elin.",
      speaker: "Elin",
      cue: { t: "Där är du ju! Jag har väntat länge.", en: "There you are! I've been waiting for ages." },
      reaction: { t: "Ingen fara, jag har tid.", en: "No worries, I have time." },
      accept: ["^(förlåt|ursäkta)\\b"],
      notWith: ["ursaekta"],
    },
  ],
  varsaagod: [
    {
      situation: "You're holding the island map. Lisa wants a look.",
      speaker: "Lisa",
      cue: { t: "Får jag titta på kartan?", en: "Can I look at the map?" },
      reaction: { t: "Tack! Där är ju fyren!", en: "Thanks! There's the lighthouse!" },
      accept: ["^(ja )?varsågod\\b"],
      pitch: 1.45,
    },
    {
      situation: "A tourist needs a pen. You have one.",
      speaker: "Turist",
      cue: { t: "Ursäkta, har du en penna?", en: "Excuse me, do you have a pen?" },
      reaction: { t: "Tack så mycket!", en: "Thank you very much!" },
      accept: ["^(ja )?varsågod\\b"],
      pitch: 0.85,
    },
  ],
  "ingen-orsak": [
    {
      situation: "You helped a tourist carry her bags off the ferry.",
      speaker: "Turist",
      cue: { t: "Tack för hjälpen!", en: "Thanks for the help!" },
      reaction: { t: "Du är så snäll!", en: "You're so kind!" },
      accept: ["^(ingen orsak|det var så lite|varsågod)\\b"],
      notWith: ["det-var-saa-lite", "varsaagod"],
      pitch: 1.1,
    },
    {
      situation: "You bought Lisa an ice cream.",
      speaker: "Lisa",
      cue: { t: "Tack för glassen!", en: "Thanks for the ice cream!" },
      reaction: { t: "Mmm, den är jättegod!", en: "Mmm, it's delicious!" },
      accept: ["^(ingen orsak|det var så lite|varsågod)\\b"],
      notWith: ["det-var-saa-lite", "varsaagod"],
      pitch: 1.45,
    },
  ],
  "var-kommer-du-ifraan": [
    {
      situation: "A new face on the dock introduces herself. Ask where she's from.",
      speaker: "Sara",
      cue: { t: "Hej! Jag heter Sara.", en: "Hi! My name is Sara." },
      reaction: { t: "Jag kommer från Norge!", en: "I'm from Norway!" },
      accept: ["^var kommer du (ifrån|från)\\b"],
      pitch: 1.15,
    },
    {
      situation: "Elin introduces her new neighbour. Ask him where he's from.",
      speaker: "Tom",
      cue: { t: "Hej! Jag är Tom, jag är ny här.", en: "Hi! I'm Tom, I'm new here." },
      reaction: { t: "Från Skottland!", en: "From Scotland!" },
      accept: ["^var kommer du (ifrån|från)\\b"],
      pitch: 0.9,
    },
  ],
  "jag-kommer-fraan": [
    {
      situation: "Elin wants to know where you're from.",
      speaker: "Elin",
      cue: { t: "Var kommer du ifrån?", en: "Where are you from?" },
      reaction: { t: "Oj, vad spännande!", en: "Oh, how exciting!" },
      accept: ["^jag kommer från \\p{L}+"],
    },
    {
      situation: "The ferry captain hears your accent.",
      speaker: "Kaptenen",
      cue: { t: "Du är inte härifrån, va? Var kommer du ifrån?", en: "You're not from here, are you? Where are you from?" },
      reaction: { t: "Välkommen till Sverige!", en: "Welcome to Sweden!" },
      accept: ["^jag kommer från \\p{L}+"],
      pitch: 0.7,
    },
  ],
  "jag-bor-i": [
    {
      situation: "Elin wonders if you live on the island.",
      speaker: "Elin",
      cue: { t: "Bor du här på ön?", en: "Do you live here on the island?" },
      reaction: { t: "Vad fint! Välkommen!", en: "How lovely! Welcome!" },
      accept: ["^(nej )?jag bor (i|på) \\p{L}+"],
    },
    {
      situation: "Anna is chatting with you on the ferry.",
      speaker: "Anna",
      cue: { t: "Var bor du?", en: "Where do you live?" },
      reaction: { t: "Där har jag aldrig varit!", en: "I've never been there!" },
      accept: ["^jag bor (i|på) \\p{L}+"],
      pitch: 1.2,
    },
  ],
  "pratar-du-engelska": [
    {
      situation: "A kid talks to you in very fast Swedish. Ask if he speaks English.",
      speaker: "Oskar",
      cue: { t: "Hej! Vill du leka med oss? Vi ska bygga en koja och …", en: "Hi! Do you want to play with us? We're going to build a den and …" },
      reaction: { t: "Lite! Hello!", en: "A little! Hello!" },
      accept: ["^(ursäkta )?(pratar|talar) du engelska\\b", "^kan du (prata )?engelska\\b"],
      pitch: 1.4,
    },
    {
      situation: "An old man asks you something you don't understand.",
      speaker: "Gubben",
      cue: { t: "Goddag, goddag! Vad vill ni här?", en: "Good day, good day! What do you want here?" },
      reaction: { t: "Nej, bara svenska, tyvärr!", en: "No, only Swedish, I'm afraid!" },
      accept: ["^(ursäkta )?(pratar|talar) du engelska\\b", "^kan du (prata )?engelska\\b"],
      pitch: 0.7,
    },
  ],
  "jag-pratar": [
    {
      situation: "Elin asks which languages you speak.",
      speaker: "Elin",
      cue: { t: "Vilka språk pratar du?", en: "Which languages do you speak?" },
      reaction: { t: "Din svenska är redan bra!", en: "Your Swedish is already good!" },
      accept: ["^jag pratar \\p{L}+"],
    },
    {
      situation: "A tourist asks if you speak German. You don't.",
      speaker: "Turist",
      cue: { t: "Pratar du tyska?", en: "Do you speak German?" },
      expect: { t: "Nej, jag pratar inte tyska.", en: "No, I don't speak German." },
      reaction: { t: "Okej, då pratar vi svenska!", en: "Okay, then we'll speak Swedish!" },
      accept: ["\\bjag pratar inte\\b"],
      pitch: 0.85,
    },
  ],
  "vem-aer-det": [
    {
      situation: "Someone on a fishing boat waves at Elin. Ask who it is.",
      speaker: "Elin",
      cue: { t: "Titta, han vinkar till oss!", en: "Look, he's waving at us!" },
      reaction: { t: "Det är Nils, fiskaren!", en: "It's Nils, the fisherman!" },
      accept: ["^vem är det\\b"],
    },
    {
      situation: "A woman jogs past and says hi to Elin. Ask who she is.",
      speaker: "Elin",
      cue: { t: "Hej hej, Karin!", en: "Hi hi, Karin!" },
      reaction: { t: "Det är Karin. Hon är sjuksköterska.", en: "That's Karin. She's a nurse." },
      accept: ["^vem är det\\b"],
    },
  ],
  "det-haer-aer": [
    {
      situation: "You arrive with your friend Tom. Introduce him to Elin.",
      speaker: "Elin",
      cue: { t: "Hej! Vem har du med dig?", en: "Hi! Who have you brought?" },
      expect: { t: "Det här är Tom.", en: "This is Tom." },
      reaction: { t: "Hej Tom! Välkommen!", en: "Hi Tom! Welcome!" },
      accept: ["^det här är \\p{L}+"],
    },
    {
      situation: "You show Elin a photo of your family.",
      speaker: "Elin",
      cue: { t: "Vilka är det på bilden?", en: "Who's in the picture?" },
      expect: { t: "Det här är min familj.", en: "This is my family." },
      reaction: { t: "Vilken fin familj!", en: "What a lovely family!" },
      accept: ["^det här är (min|mitt|mina) \\p{L}+"],
    },
  ],
};

// ---------- Nils: numbers and weather ----------

const WEATHER = "^hur (är|blir) vädret\\b";

export const nils: Beats = {
  "hur-maanga": [
    {
      situation: "Nils holds up a bucket full of fish. Ask how many.",
      speaker: "Nils",
      cue: { t: "Titta, fiskar!", en: "Look, fish!" },
      reaction: { t: "Tolv stycken!", en: "Twelve of them!" },
      accept: ["^hur många\\b"],
    },
    {
      situation: "Lisa shows you a bag of sweets. Ask how many.",
      speaker: "Lisa",
      cue: { t: "Jag har godis!", en: "I've got sweets!" },
      reaction: { t: "Hundra! Nej, tio.", en: "A hundred! No, ten." },
      accept: ["^hur många\\b"],
      pitch: 1.45,
    },
  ],
  "hur-gammal-aer-du": [
    {
      situation: "Lisa is wearing a paper crown. Ask how old she is.",
      speaker: "Lisa",
      cue: { t: "Jag fyller år idag!", en: "It's my birthday today!" },
      reaction: { t: "Jag är sju!", en: "I'm seven!" },
      accept: ["^hur gammal är du\\b"],
      pitch: 1.45,
    },
    {
      situation: "Nils says he's fished here all his life. Ask how old he is.",
      speaker: "Nils",
      cue: { t: "Jag har fiskat här i femtio år.", en: "I've fished here for fifty years." },
      reaction: { t: "Sjuttio! Men jag känner mig som tjugo.", en: "Seventy! But I feel like twenty." },
      accept: ["^hur gammal är du\\b"],
    },
  ],
  "jag-aer-aar": [
    {
      situation: "Nils wants to know your age.",
      speaker: "Nils",
      cue: { t: "Och du, hur gammal är du?", en: "And you, how old are you?" },
      reaction: { t: "Så ung!", en: "So young!" },
      accept: ["^jag är (\\p{N}+|\\p{L}+) år"],
    },
    {
      situation: "Lisa asks your age.",
      speaker: "Lisa",
      cue: { t: "Jag är sju. Hur gammal är du?", en: "I'm seven. How old are you?" },
      reaction: { t: "Då är du gammal!", en: "Then you're old!" },
      accept: ["^jag är (\\p{N}+|\\p{L}+) år"],
      pitch: 1.45,
    },
  ],
  "vad-kostar-det": [
    {
      situation: "Nils is selling fish from his boat. Ask the price.",
      speaker: "Nils",
      cue: { t: "Färsk fisk! Färsk fisk!", en: "Fresh fish! Fresh fish!" },
      reaction: { t: "Femtio kronor för en fisk.", en: "Fifty kronor a fish." },
      accept: ["^(vad|hur mycket) kostar (det|den|de)\\b"],
    },
    {
      situation: "Two kids are selling juice by the path. Ask the price.",
      speaker: "Oskar",
      cue: { t: "Saft! Kall saft!", en: "Juice! Cold juice!" },
      reaction: { t: "Tio kronor!", en: "Ten kronor!" },
      accept: ["^(vad|hur mycket) kostar (det|den|de)\\b"],
      pitch: 1.4,
    },
  ],
  "det-kostar": [
    {
      situation: "A tourist asks you the price of a coffee. The menu says 25 kronor.",
      speaker: "Turist",
      cue: { t: "Ursäkta, vad kostar en kaffe?", en: "Excuse me, how much is a coffee?" },
      expect: { t: "Det kostar tjugofem kronor.", en: "It costs twenty-five kronor." },
      reaction: { t: "Tack!", en: "Thanks!" },
      accept: ["^(den |det )?kostar (tjugofem|25)( kronor)?"],
      pitch: 0.85,
    },
    {
      situation: "Lisa wants an ice cream. It costs 20 kronor.",
      speaker: "Lisa",
      cue: { t: "Hur mycket kostar glassen?", en: "How much is the ice cream?" },
      expect: { t: "Det kostar tjugo kronor.", en: "It costs twenty kronor." },
      reaction: { t: "Oj, jag har bara tio!", en: "Oh, I only have ten!" },
      accept: ["^(den |det )?kostar (tjugo|20)( kronor)?"],
      pitch: 1.45,
    },
  ],
  "hur-aer-vaedret": [
    {
      situation: "Nils is about to take the boat out. Ask about the weather.",
      speaker: "Nils",
      cue: { t: "Jag ska ut med båten.", en: "I'm taking the boat out." },
      reaction: { t: "Lite blåsigt, men fint!", en: "A bit windy, but nice!" },
      accept: [WEATHER],
    },
    {
      situation: "Elin suggests a picnic tomorrow. Ask about the weather.",
      speaker: "Elin",
      cue: { t: "Ska vi ha picknick imorgon?", en: "Shall we have a picnic tomorrow?" },
      reaction: { t: "Sol hela dagen!", en: "Sun all day!" },
      accept: [WEATHER],
    },
  ],
  "det-regnar": [
    {
      situation: "It's pouring. Nils wants to go fishing anyway.",
      speaker: "Nils",
      cue: { t: "Ska vi fiska?", en: "Shall we go fishing?" },
      reaction: { t: "Fisken bryr sig inte!", en: "The fish don't care!" },
      accept: ["\\bdet regnar\\b"],
    },
    {
      situation: "It's raining hard. Leo wants to play football.",
      speaker: "Leo",
      cue: { t: "Vill du spela fotboll?", en: "Do you want to play football?" },
      reaction: { t: "Då spelar vi inne!", en: "Then we'll play inside!" },
      accept: ["\\bdet regnar\\b"],
      pitch: 1.3,
    },
  ],
  "det-blaaser": [
    {
      situation: "A gust of wind blows your hat off.",
      speaker: "Nils",
      cue: { t: "Oj, din mössa!", en: "Whoa, your hat!" },
      reaction: { t: "Ja, det blåser mycket idag!", en: "Yes, it's very windy today!" },
      accept: ["\\bdet blåser\\b"],
    },
    {
      situation: "Your map flies out of your hands on the platform.",
      speaker: "Stina",
      cue: { t: "Vart tog din karta vägen?", en: "Where did your map go?" },
      reaction: { t: "Håll i hatten!", en: "Hold on to your hat!" },
      accept: ["\\bdet blåser\\b"],
      pitch: 1.1,
    },
  ],
  "jag-fryser": [
    {
      situation: "An icy wind comes off the sea.",
      speaker: "Nils",
      cue: { t: "Du ser kall ut!", en: "You look cold!" },
      reaction: { t: "Ta min jacka!", en: "Take my jacket!" },
      accept: ["\\bjag fryser\\b"],
    },
    {
      situation: "It's snowing and you're outside in a T-shirt.",
      speaker: "Karin",
      cue: { t: "Är du inte kall?", en: "Aren't you cold?" },
      expect: { t: "Jo, jag fryser!", en: "Yes, I'm cold!" },
      reaction: { t: "Kom in och värm dig!", en: "Come in and warm up!" },
      accept: ["\\bjag fryser\\b"],
      pitch: 1.1,
    },
  ],
  "det-aer-varmt": [
    {
      situation: "It's a hot day. Nils sees you heading for the water.",
      speaker: "Nils",
      cue: { t: "Ska du bada?", en: "Are you going for a swim?" },
      expect: { t: "Ja, det är varmt!", en: "Yes, it's warm!" },
      reaction: { t: "Perfekt badväder!", en: "Perfect swimming weather!" },
      accept: ["\\bdet är (så |väldigt |jätte)?varmt\\b"],
    },
    {
      situation: "The sun is blazing. Leo asks if you need jackets.",
      speaker: "Leo",
      cue: { t: "Ska vi ta med jackor?", en: "Shall we bring jackets?" },
      expect: { t: "Nej, det är varmt.", en: "No, it's warm." },
      reaction: { t: "Okej, då går vi!", en: "Okay, let's go!" },
      accept: ["\\bdet är (så |väldigt |jätte)?varmt\\b"],
      pitch: 1.3,
    },
  ],
  "vilket-fint-vaeder": [
    {
      situation: "The sun comes out over the harbour.",
      speaker: "Elin",
      cue: { t: "Titta, solen skiner!", en: "Look, the sun is shining!" },
      reaction: { t: "Ja, perfekt för en fika!", en: "Yes, perfect for a coffee!" },
      accept: ["^(vilket|så) fint väder\\b"],
    },
    {
      situation: "A clear blue morning on the island.",
      speaker: "Nils",
      cue: { t: "God morgon! Titta på himlen!", en: "Good morning! Look at the sky!" },
      reaction: { t: "Ja, idag nappar det!", en: "Yes, the fish will bite today!" },
      accept: ["^(vilket|så) fint väder\\b"],
    },
  ],
};

// ---------- Karin: family, health and work ----------

export const karin: Beats = {
  "har-du-barn": [
    {
      situation: "Karin tells you about her job. Ask if she has children.",
      speaker: "Karin",
      cue: { t: "Jag jobbar här på vårdcentralen.", en: "I work here at the health centre." },
      reaction: { t: "Ja, en son. Han heter Leo.", en: "Yes, a son. His name is Leo." },
      accept: ["^har du barn\\b"],
    },
    {
      situation: "Nils points at the red house where he lives. Ask if he has children.",
      speaker: "Nils",
      cue: { t: "Min fru och jag bor i det röda huset.", en: "My wife and I live in the red house." },
      reaction: { t: "Ja, två döttrar. De bor i Göteborg.", en: "Yes, two daughters. They live in Gothenburg." },
      accept: ["^har du barn\\b"],
      pitch: 0.8,
    },
  ],
  "jag-har-barn": [
    {
      situation: "Karin asks about your family.",
      speaker: "Karin",
      cue: { t: "Har du barn?", en: "Do you have children?" },
      reaction: { t: "Vad fint! Jag har en son, Leo.", en: "How lovely! I have a son, Leo." },
      accept: ["^jag har (\\p{N}+|\\p{L}+) barn", "^(nej )?jag har inga barn"],
    },
    {
      situation: "Anna is chatting on the bench.",
      speaker: "Anna",
      cue: { t: "Har du barn?", en: "Do you have children?" },
      reaction: { t: "Mina barn är redan stora.", en: "My children are already grown up." },
      accept: ["^jag har (\\p{N}+|\\p{L}+) barn", "^(nej )?jag har inga barn"],
      pitch: 1.2,
    },
  ],
  "har-du-syskon": [
    {
      situation: "Karin says her family is huge. Ask if she has brothers or sisters.",
      speaker: "Karin",
      cue: { t: "Min familj är jättestor.", en: "My family is huge." },
      reaction: { t: "Ja, fyra bröder!", en: "Yes, four brothers!" },
      accept: ["^har du syskon\\b"],
    },
    {
      situation: "Leo says it's quiet at home. Ask if he has brothers or sisters.",
      speaker: "Leo",
      cue: { t: "Det är så tyst hemma.", en: "It's so quiet at home." },
      reaction: { t: "Nej, jag har inga syskon.", en: "No, I don't have any brothers or sisters." },
      accept: ["^har du syskon\\b"],
      pitch: 1.3,
    },
  ],
  "min-familj": [
    {
      situation: "You're holding a photo. Karin is curious.",
      speaker: "Karin",
      cue: { t: "Vilka är det på bilden?", en: "Who's in the picture?" },
      expect: { t: "Det är min familj.", en: "It's my family." },
      reaction: { t: "Vilken fin familj!", en: "What a lovely family!" },
      accept: ["\\bmin familj\\b"],
    },
    {
      situation: "You're on the phone to your family. Anna asks who you're calling.",
      speaker: "Anna",
      cue: { t: "Vem ringer du till?", en: "Who are you calling?" },
      expect: { t: "Jag ringer min familj.", en: "I'm calling my family." },
      reaction: { t: "Hälsa från mig!", en: "Say hi from me!" },
      accept: ["\\bmin familj\\b"],
      pitch: 1.2,
    },
  ],
  "vad-heter-hon": [
    {
      situation: "Karin shows you a photo of her sister. Ask her name.",
      speaker: "Karin",
      cue: { t: "Det här är min syster.", en: "This is my sister." },
      reaction: { t: "Hon heter Eva.", en: "Her name is Eva." },
      accept: ["^vad heter hon\\b"],
    },
    {
      situation: "Nils says his boat has his daughter's name. Ask what she's called.",
      speaker: "Nils",
      cue: { t: "Min båt heter som min dotter.", en: "My boat has the same name as my daughter." },
      reaction: { t: "Hon heter Alva!", en: "Her name is Alva!" },
      accept: ["^vad heter hon\\b"],
      pitch: 0.8,
    },
  ],
  "jag-har-ont-i": [
    {
      situation: "You come into the health centre holding your head.",
      speaker: "Karin",
      cue: { t: "Hej! Vad är problemet?", en: "Hi! What's the problem?" },
      reaction: { t: "Stackars dig. Sätt dig här.", en: "Poor you. Sit down here." },
      accept: ["^jag har ont i \\p{L}+"],
    },
    {
      situation: "You're limping after a long walk.",
      speaker: "Karin",
      cue: { t: "Varför haltar du?", en: "Why are you limping?" },
      expect: { t: "Jag har ont i foten.", en: "My foot hurts." },
      reaction: { t: "Låt mig titta.", en: "Let me have a look." },
      accept: ["^jag har ont i (foten|benet)\\b"],
    },
  ],
  "jag-maar-inte-bra": [
    {
      situation: "You feel sick. Leo wants to play football.",
      speaker: "Leo",
      cue: { t: "Vill du spela fotboll?", en: "Do you want to play football?" },
      reaction: { t: "Oj, gå till mamma på vårdcentralen!", en: "Oh, go and see my mum at the health centre!" },
      accept: ["\\bjag mår inte (så )?bra\\b"],
      pitch: 1.3,
    },
    {
      situation: "Karin sees you looking pale.",
      speaker: "Karin",
      cue: { t: "Du ser blek ut. Hur mår du?", en: "You look pale. How are you?" },
      reaction: { t: "Sätt dig, jag hämtar vatten.", en: "Sit down, I'll get some water." },
      accept: ["\\bjag mår inte (så )?bra\\b"],
    },
  ],
  "det-goer-ont": [
    {
      situation: "Karin gently presses your sore arm.",
      speaker: "Karin",
      cue: { t: "Gör det ont här?", en: "Does it hurt here?" },
      expect: { t: "Ja, det gör ont!", en: "Yes, it hurts!" },
      reaction: { t: "Okej, vi tar det försiktigt.", en: "Okay, we'll go carefully." },
      accept: ["\\bdet gör (så |jätte)?ont\\b"],
    },
    {
      situation: "A bee just stung your hand.",
      speaker: "Karin",
      cue: { t: "Vad hände?", en: "What happened?" },
      expect: { t: "Aj, det gör ont!", en: "Ouch, it hurts!" },
      reaction: { t: "Ett bi! Här är lite is.", en: "A bee! Here's some ice." },
      accept: ["\\bdet gör (så |jätte)?ont\\b"],
    },
  ],
  "du-borde": [
    {
      situation: "Leo is coughing but wants to go and play football.",
      speaker: "Leo",
      cue: { t: "Jag är förkyld, men jag vill spela!", en: "I have a cold, but I want to play!" },
      expect: { t: "Du borde vila.", en: "You should rest." },
      reaction: { t: "Okej, okej …", en: "Okay, okay …" },
      accept: ["^(men )?du borde \\p{L}+"],
      pitch: 1.3,
    },
    {
      situation: "Nils has been in the sun all day without a hat.",
      speaker: "Nils",
      cue: { t: "Jag har ont i huvudet.", en: "I have a headache." },
      expect: { t: "Du borde dricka vatten.", en: "You should drink some water." },
      reaction: { t: "Du har rätt. Tack!", en: "You're right. Thanks!" },
      accept: ["^du borde \\p{L}+"],
      pitch: 0.8,
    },
  ],
  "krya-paa-dig": [
    {
      situation: "Leo is in bed with a fever. He waves from the window.",
      speaker: "Leo",
      cue: { t: "Hej … jag är sjuk.", en: "Hi … I'm ill." },
      reaction: { t: "Tack! Imorgon spelar vi!", en: "Thanks! We'll play tomorrow!" },
      accept: ["^krya på dig\\b"],
      pitch: 1.3,
    },
    {
      situation: "Bosse has a cold and a very red nose.",
      speaker: "Bosse",
      cue: { t: "Atjo! Jag är förkyld.", en: "Atchoo! I have a cold." },
      reaction: { t: "Tack, du är snäll!", en: "Thanks, you're kind!" },
      accept: ["^krya på dig\\b"],
      pitch: 0.8,
    },
  ],
  "vad-jobbar-du-med": [
    {
      situation: "A woman on the ferry says she's here for work. Ask what she does.",
      speaker: "Anna",
      cue: { t: "Jag är här för jobbet.", en: "I'm here for work." },
      reaction: { t: "Jag är lärare.", en: "I'm a teacher." },
      accept: ["^vad jobbar du (med|som)\\b"],
      pitch: 1.2,
    },
    {
      situation: "Karin looks tired after a long day. Ask what she does.",
      speaker: "Karin",
      cue: { t: "Jag har jobbat hela dagen.", en: "I've worked all day." },
      reaction: { t: "Jag är sjuksköterska här på ön.", en: "I'm a nurse here on the island." },
      accept: ["^vad jobbar du (med|som)\\b"],
    },
  ],
  "jag-jobbar-som": [
    {
      situation: "Karin asks what you do for a living.",
      speaker: "Karin",
      cue: { t: "Och du, vad jobbar du med?", en: "And you, what do you do?" },
      reaction: { t: "Vad intressant!", en: "How interesting!" },
      accept: ["^jag jobbar (som|på|med) \\p{L}+", "^jag är \\p{L}+"],
    },
    {
      situation: "Nils is curious about your job.",
      speaker: "Nils",
      cue: { t: "Vad jobbar du med?", en: "What do you do?" },
      reaction: { t: "Jag har bara fiskat hela livet!", en: "I've only ever fished!" },
      accept: ["^jag jobbar (som|på|med) \\p{L}+", "^jag är \\p{L}+"],
      pitch: 0.8,
    },
  ],
  "jag-slutar": [
    {
      situation: "Karin wants to have coffee after work. You finish at five.",
      speaker: "Karin",
      cue: { t: "När slutar du idag?", en: "When do you finish today?" },
      expect: { t: "Jag slutar klockan fem.", en: "I finish at five." },
      reaction: { t: "Då fikar vi efter jobbet!", en: "Then let's have coffee after work!" },
      accept: ["^jag slutar (klockan )?(fem|5)\\b"],
    },
    {
      situation: "Maja wants to meet at four. You work until five.",
      speaker: "Maja",
      cue: { t: "Ses vi klockan fyra?", en: "Shall we meet at four?" },
      expect: { t: "Nej, jag slutar klockan fem.", en: "No, I finish at five." },
      reaction: { t: "Då ses vi halv sex!", en: "Then let's meet at half past five!" },
      accept: ["\\bjag slutar (klockan )?(fem|5)\\b"],
      pitch: 1.2,
    },
  ],
  semester: [
    {
      situation: "It's July and you're not working.",
      speaker: "Karin",
      cue: { t: "Jobbar du i juli?", en: "Are you working in July?" },
      expect: { t: "Nej, jag har semester!", en: "No, I'm on holiday!" },
      reaction: { t: "Skönt! Vart ska du resa?", en: "Nice! Where are you going?" },
      accept: ["\\b(har|på) semester\\b"],
    },
    {
      situation: "Nils is surprised you're free on a weekday.",
      speaker: "Nils",
      cue: { t: "Jobbar du inte idag?", en: "Aren't you working today?" },
      expect: { t: "Nej, jag har semester!", en: "No, I'm on holiday!" },
      reaction: { t: "Då kan du fiska med mig!", en: "Then you can go fishing with me!" },
      accept: ["\\b(har|på) semester\\b"],
      pitch: 0.8,
    },
  ],
};

// ---------- Stina: time and travel ----------

export const stina: Beats = {
  "vad-aer-klockan": [
    {
      situation: "You left your phone at home. Stina has a big watch.",
      speaker: "Stina",
      cue: { t: "Hej! Kan jag hjälpa dig?", en: "Hi! Can I help you?" },
      reaction: { t: "Klockan är halv tre.", en: "It's half past two." },
      accept: ["^(ursäkta )?vad är klockan\\b"],
    },
    {
      situation: "Lisa has to be home at five. Ask her what time it is.",
      speaker: "Lisa",
      cue: { t: "Mamma säger att jag ska vara hemma klockan fem!", en: "Mum says I have to be home at five!" },
      reaction: { t: "Oj, kvart i fem! Hej då!", en: "Oops, quarter to five! Bye!" },
      accept: ["^(ursäkta )?vad är klockan\\b"],
      pitch: 1.45,
    },
  ],
  "klockan-aer": [
    {
      situation: "The station clock shows three o'clock.",
      speaker: "Turist",
      cue: { t: "Ursäkta, vad är klockan?", en: "Excuse me, what time is it?" },
      expect: { t: "Klockan är tre.", en: "It's three o'clock." },
      reaction: { t: "Tack! Då hinner jag.", en: "Thanks! Then I'll make it." },
      accept: ["^(den |klockan )?är tre\\b"],
      pitch: 0.85,
    },
    {
      situation: "The station clock shows half past nine.",
      speaker: "Stina",
      cue: { t: "Min klocka har stannat. Vad är klockan?", en: "My watch has stopped. What time is it?" },
      expect: { t: "Klockan är halv tio.", en: "It's half past nine." },
      reaction: { t: "Halv tio? Tåget går snart!", en: "Half past nine? The train leaves soon!" },
      accept: ["^(den |klockan )?är halv tio\\b"],
    },
  ],
  "naer-gaar-taaget": [
    {
      situation: "Stina asks if you're going to Stockholm. Ask when the train leaves.",
      speaker: "Stina",
      cue: { t: "Hej! Ska du till Stockholm?", en: "Hi! Are you going to Stockholm?" },
      reaction: { t: "Klockan tio.", en: "At ten o'clock." },
      accept: ["^(ursäkta )?när går (tåget|nästa tåg)\\b"],
    },
    {
      situation: "Stina points at the Uppsala train. Ask when it leaves.",
      speaker: "Stina",
      cue: { t: "Nästa tåg går till Uppsala.", en: "The next train goes to Uppsala." },
      reaction: { t: "Om tjugo minuter.", en: "In twenty minutes." },
      accept: ["^(ursäkta )?när går (det|tåget)\\b"],
    },
  ],
  "vilken-dag-aer-det": [
    {
      situation: "Lisa has lost track of the days in the summer holidays. So have you.",
      speaker: "Lisa",
      cue: { t: "Jag har sommarlov!", en: "It's the summer holidays!" },
      reaction: { t: "Jag vet inte! Kanske onsdag?", en: "I don't know! Maybe Wednesday?" },
      accept: ["^vilken dag är det\\b"],
      pitch: 1.45,
    },
    {
      situation: "Stina says the train doesn't run on Sundays. Ask what day it is.",
      speaker: "Stina",
      cue: { t: "Tåget går inte på söndagar.", en: "The train doesn't run on Sundays." },
      reaction: { t: "Det är lördag, så tåget går!", en: "It's Saturday, so the train is running!" },
      accept: ["^vilken dag är det\\b"],
    },
  ],
  "om-fem-minuter": [
    {
      situation: "The board says the train leaves in five minutes.",
      speaker: "Turist",
      cue: { t: "När går tåget?", en: "When does the train leave?" },
      expect: { t: "Om fem minuter.", en: "In five minutes." },
      reaction: { t: "Då springer jag!", en: "Then I'll run!" },
      accept: ["\\bom fem minuter\\b"],
      pitch: 0.85,
    },
    {
      situation: "Elin calls. You're almost at the dock.",
      speaker: "Elin",
      cue: { t: "När kommer du?", en: "When are you coming?" },
      expect: { t: "Om fem minuter!", en: "In five minutes!" },
      reaction: { t: "Okej, jag väntar!", en: "Okay, I'll wait!" },
      accept: ["\\bom fem minuter\\b"],
    },
  ],
  "tur-och-retur": [
    {
      situation: "You're buying a ticket and coming back tonight.",
      speaker: "Stina",
      cue: { t: "Enkel biljett eller tur och retur?", en: "Single or return?" },
      expect: { t: "Tur och retur, tack.", en: "Return, please." },
      reaction: { t: "Varsågod. Det blir tvåhundra kronor.", en: "Here you go. That'll be two hundred kronor." },
      accept: ["\\btur och retur\\b"],
    },
    {
      situation: "You want to come back to the island tomorrow.",
      speaker: "Stina",
      cue: { t: "Ska du komma tillbaka hit?", en: "Are you coming back here?" },
      expect: { t: "Ja, tur och retur, tack.", en: "Yes, a return, please." },
      reaction: { t: "Då blir det billigare!", en: "Then it's cheaper!" },
      accept: ["\\btur och retur\\b"],
    },
  ],
  "hur-laang-tid-tar-det": [
    {
      situation: "Stina says the train goes to Stockholm. Ask how long it takes.",
      speaker: "Stina",
      cue: { t: "Tåget går till Stockholm.", en: "The train goes to Stockholm." },
      reaction: { t: "Ungefär en timme.", en: "About an hour." },
      accept: ["^hur (lång tid|länge) tar det\\b"],
    },
    {
      situation: "Stina suggests the bus to the airport. Ask how long it takes.",
      speaker: "Stina",
      cue: { t: "Du kan ta bussen till flygplatsen.", en: "You can take the bus to the airport." },
      reaction: { t: "Fyrtio minuter.", en: "Forty minutes." },
      accept: ["^hur (lång tid|länge) tar det\\b"],
    },
  ],
  "aer-platsen-ledig": [
    {
      situation: "The train is full. A woman sits next to an empty seat.",
      speaker: "Kvinnan",
      cue: { t: "Mm?", en: "Mm?" },
      reaction: { t: "Ja, varsågod!", en: "Yes, go ahead!" },
      accept: ["^(ursäkta )?är (den här platsen|det) ledig", "^är det ledigt\\b"],
      pitch: 1.15,
    },
    {
      situation: "An old man on the ferry has his bag on the seat beside him.",
      speaker: "Gubben",
      cue: { t: "Hej hej.", en: "Hi there." },
      reaction: { t: "Nej tyvärr, min fru sitter där.", en: "No, sorry, my wife is sitting there." },
      accept: ["^(ursäkta )?är (den här platsen|det) ledig", "^är det ledigt\\b"],
      pitch: 0.7,
    },
  ],
  "jag-vill-boka": [
    {
      situation: "You call a hotel in Stockholm.",
      speaker: "Receptionen",
      cue: { t: "Hotell Havsutsikt, hej! Vad kan jag göra för dig?", en: "Hotel Sea View, hello! What can I do for you?" },
      reaction: { t: "Självklart! För hur många nätter?", en: "Of course! For how many nights?" },
      accept: ["^(hej )?jag vill boka \\p{L}+", "^(hej )?jag skulle vilja boka \\p{L}+"],
      pitch: 1.15,
    },
    {
      situation: "You and a friend need train tickets.",
      speaker: "Stina",
      cue: { t: "Nästa! Vad vill du ha?", en: "Next! What would you like?" },
      expect: { t: "Jag vill boka två biljetter.", en: "I'd like to book two tickets." },
      reaction: { t: "Till Stockholm?", en: "To Stockholm?" },
      accept: ["^jag (vill|skulle vilja) boka (två )?biljett"],
    },
  ],
  "trevlig-resa": [
    {
      situation: "Your friend Anna is getting on the train.",
      speaker: "Anna",
      cue: { t: "Hej då! Nu åker jag!", en: "Bye! I'm off now!" },
      reaction: { t: "Tack! Vi ses snart!", en: "Thanks! See you soon!" },
      accept: ["^trevlig resa\\b"],
      pitch: 1.2,
    },
    {
      situation: "A family of tourists is leaving on the ferry.",
      speaker: "Turist",
      cue: { t: "Vi åker hem till Tyskland idag.", en: "We're going home to Germany today." },
      reaction: { t: "Tack! Hej då, Lilla Ö!", en: "Thanks! Bye, Lilla Ö!" },
      accept: ["^trevlig resa\\b"],
      pitch: 0.85,
    },
  ],
};

// ---------- Maja: shopping, home and clothes ----------

export const maja: Beats = {
  "har-ni": [
    {
      situation: "You need milk.",
      speaker: "Maja",
      cue: { t: "Hej! Kan jag hjälpa dig?", en: "Hi! Can I help you?" },
      reaction: { t: "Ja, där borta!", en: "Yes, over there!" },
      accept: ["^(hej )?har ni \\p{L}+"],
    },
    {
      situation: "You want to post a card home.",
      speaker: "Maja",
      cue: { t: "Välkommen! Vad letar du efter?", en: "Welcome! What are you looking for?" },
      expect: { t: "Har ni frimärken?", en: "Do you have stamps?" },
      reaction: { t: "Ja, vi har frimärken och vykort.", en: "Yes, we have stamps and postcards." },
      accept: ["^(hej )?har ni frimärken\\b"],
    },
  ],
  "hur-mycket-kostar": [
    {
      situation: "You pick up a piece of cheese with no price on it.",
      speaker: "Maja",
      cue: { t: "Hittade du något?", en: "Did you find something?" },
      reaction: { t: "Fyrtio kronor.", en: "Forty kronor." },
      accept: ["^(hur mycket|vad) kostar \\p{L}+"],
    },
    {
      situation: "A red jacket hangs in the shop window.",
      speaker: "Maja",
      cue: { t: "Den är fin, va?", en: "It's nice, isn't it?" },
      expect: { t: "Hur mycket kostar jackan?", en: "How much is the jacket?" },
      reaction: { t: "Femhundra kronor. Den är ny!", en: "Five hundred kronor. It's new!" },
      accept: ["^(hur mycket|vad) kostar (jackan|den)\\b"],
    },
  ],
  "jag-tittar-bara": [
    {
      situation: "You're just browsing.",
      speaker: "Maja",
      cue: { t: "Hej! Kan jag hjälpa dig?", en: "Hi! Can I help you?" },
      reaction: { t: "Okej, säg till om du behöver något!", en: "Okay, just say if you need anything!" },
      accept: ["\\bjag tittar bara\\b"],
    },
    {
      situation: "You're looking around the clothes corner.",
      speaker: "Maja",
      cue: { t: "Letar du efter något speciellt?", en: "Are you looking for anything special?" },
      reaction: { t: "Varsågod, titta runt!", en: "Go ahead, have a look around!" },
      accept: ["\\bjag tittar bara\\b"],
    },
  ],
  "det-var-allt": [
    {
      situation: "You have everything you need.",
      speaker: "Maja",
      cue: { t: "Något mer?", en: "Anything else?" },
      reaction: { t: "Då blir det sextio kronor.", en: "Then that'll be sixty kronor." },
      accept: ["\\bdet var allt\\b"],
    },
    {
      situation: "Your basket is full.",
      speaker: "Maja",
      cue: { t: "Vill du ha något mer?", en: "Would you like anything else?" },
      reaction: { t: "Okej! Kort eller kontant?", en: "Okay! Card or cash?" },
      accept: ["\\bdet var allt\\b"],
    },
  ],
  "jag-betalar-med-kort": [
    {
      situation: "You don't have any cash.",
      speaker: "Maja",
      cue: { t: "Det blir femtio kronor. Kort eller kontant?", en: "That'll be fifty kronor. Card or cash?" },
      reaction: { t: "Varsågod, sätt i kortet.", en: "Go ahead, put your card in." },
      accept: ["\\bmed kort\\b", "^kort( tack)?$"],
    },
    {
      situation: "Time to pay for your bread.",
      speaker: "Maja",
      cue: { t: "Hur vill du betala?", en: "How would you like to pay?" },
      reaction: { t: "Tack! Här är kvittot.", en: "Thanks! Here's the receipt." },
      accept: ["\\bmed kort\\b", "^kort( tack)?$"],
    },
  ],
  "var-aer": [
    {
      situation: "You're visiting Maja at home and need the toilet.",
      speaker: "Maja",
      cue: { t: "Välkommen in! Sätt dig!", en: "Come in! Sit down!" },
      expect: { t: "Var är toaletten?", en: "Where is the toilet?" },
      reaction: { t: "Till vänster, bredvid köket.", en: "On the left, next to the kitchen." },
      accept: ["^(ursäkta )?var är (toaletten|badrummet)\\b"],
    },
    {
      situation: "Maja can't find her cat, Misse.",
      speaker: "Maja",
      cue: { t: "Jag hittar inte Misse!", en: "I can't find Misse!" },
      expect: { t: "Var är katten?", en: "Where is the cat?" },
      reaction: { t: "Kanske under sängen?", en: "Maybe under the bed?" },
      accept: ["^var är (katten|misse)\\b"],
    },
  ],
  "vaelkommen-in": [
    {
      situation: "Maja knocks on your door with a cake.",
      speaker: "Maja",
      cue: { t: "Hej! Jag har bakat en kaka till dig.", en: "Hi! I've baked you a cake." },
      reaction: { t: "Tack! Vad mysigt du har det!", en: "Thanks! Your place is so cosy!" },
      accept: ["^(hej )?(välkommen in|kom in)\\b"],
    },
    {
      situation: "Leo is at your door.",
      speaker: "Leo",
      cue: { t: "Knack knack! Är du hemma?", en: "Knock knock! Are you home?" },
      reaction: { t: "Tack! Ska jag ta av mig skorna?", en: "Thanks! Shall I take my shoes off?" },
      accept: ["^(hej )?(välkommen in|kom in)\\b"],
      pitch: 1.3,
    },
  ],
  mysigt: [
    {
      situation: "Maja shows you her kitchen, full of candles and plants.",
      speaker: "Maja",
      cue: { t: "Vad tycker du om mitt kök?", en: "What do you think of my kitchen?" },
      expect: { t: "Vad mysigt!", en: "How cosy!" },
      reaction: { t: "Tack! Sätt dig, jag gör kaffe.", en: "Thanks! Sit down, I'll make coffee." },
      accept: ["\\bmysigt\\b"],
    },
    {
      situation: "Karin has lit candles in every window.",
      speaker: "Karin",
      cue: { t: "Titta, jag har tänt ljus i fönstret.", en: "Look, I've lit candles in the window." },
      expect: { t: "Vad mysigt!", en: "How cosy!" },
      reaction: { t: "Ja, nu är det höst.", en: "Yes, it's autumn now." },
      accept: ["\\bmysigt\\b"],
      pitch: 1.1,
    },
  ],
  ligger: [
    {
      situation: "The key is on the table.",
      speaker: "Maja",
      cue: { t: "Var är nyckeln?", en: "Where is the key?" },
      expect: { t: "Den ligger på bordet.", en: "It's on the table." },
      reaction: { t: "Tack! Jag letar alltid efter den.", en: "Thanks! I'm always looking for it." },
      accept: ["^(den|nyckeln) ligger på bordet\\b"],
    },
    {
      situation: "Maja's book is lying under the sofa.",
      speaker: "Maja",
      cue: { t: "Var är min bok?", en: "Where is my book?" },
      expect: { t: "Den ligger under soffan.", en: "It's under the sofa." },
      reaction: { t: "Där är den ju!", en: "There it is!" },
      accept: ["^(den|boken) ligger under soffan\\b"],
    },
  ],
  "jag-lagar-mat": [
    {
      situation: "Leo calls while you're cooking.",
      speaker: "Leo",
      cue: { t: "Hej! Vad gör du?", en: "Hi! What are you doing?" },
      reaction: { t: "Mmm, vad blir det?", en: "Mmm, what are you making?" },
      accept: ["^jag lagar mat\\b"],
      pitch: 1.3,
    },
    {
      situation: "Maja smells something through your window.",
      speaker: "Maja",
      cue: { t: "Vad luktar så gott?", en: "What smells so good?" },
      reaction: { t: "Kan jag få smaka?", en: "Can I have a taste?" },
      accept: ["^jag lagar mat\\b"],
    },
  ],
  "kan-jag-prova": [
    {
      situation: "Maja shows you a new blue jumper.",
      speaker: "Maja",
      cue: { t: "Den blå tröjan är ny!", en: "The blue jumper is new!" },
      expect: { t: "Kan jag prova den?", en: "Can I try it on?" },
      reaction: { t: "Självklart! Där borta.", en: "Of course! Over there." },
      accept: ["^kan jag prova \\p{L}+"],
    },
    {
      situation: "Warm winter boots, in your size.",
      speaker: "Maja",
      cue: { t: "Stövlarna är bra på vintern.", en: "The boots are good in winter." },
      expect: { t: "Kan jag prova stövlarna?", en: "Can I try the boots on?" },
      reaction: { t: "Varsågod, sätt dig här.", en: "Go ahead, sit down here." },
      accept: ["^kan jag prova (dem|stövlarna)\\b"],
    },
  ],
  "den-aer-foer-stor": [
    {
      situation: "The jacket hangs down to your knees.",
      speaker: "Maja",
      cue: { t: "Hur passar jackan?", en: "How does the jacket fit?" },
      reaction: { t: "Här är en mindre.", en: "Here's a smaller one." },
      accept: ["^(nej )?den är (lite |alldeles |för )?(för )?stor\\b"],
    },
    {
      situation: "The hat covers your eyes.",
      speaker: "Maja",
      cue: { t: "Passar mössan?", en: "Does the hat fit?" },
      reaction: { t: "Oj! Den är ju Nils mössa.", en: "Oops! That's Nils's hat." },
      accept: ["^(nej )?den är (lite |alldeles |för )?(för )?stor\\b"],
    },
  ],
  "vilken-faerg": [
    {
      situation: "Leo has a new bike. Ask what colour it is.",
      speaker: "Leo",
      cue: { t: "Jag har köpt en ny cykel!", en: "I've bought a new bike!" },
      reaction: { t: "Gul, såklart!", en: "Yellow, of course!" },
      accept: ["^vilken färg\\b"],
      pitch: 1.3,
    },
    {
      situation: "Karin has painted her house. Ask what colour.",
      speaker: "Karin",
      cue: { t: "Jag har målat huset!", en: "I've painted the house!" },
      reaction: { t: "Rött, som alla hus här!", en: "Red, like all the houses here!" },
      accept: ["^vilken färg\\b"],
      pitch: 1.1,
    },
  ],
  "jag-har-paa-mig": [
    {
      situation: "Leo is looking for you in the square. You're wearing a blue jumper.",
      speaker: "Leo",
      cue: { t: "Jag ser dig inte! Vad har du på dig?", en: "I can't see you! What are you wearing?" },
      reaction: { t: "Nu ser jag dig!", en: "Now I see you!" },
      accept: ["^jag har på mig \\p{L}+"],
      pitch: 1.3,
    },
    {
      situation: "You're wearing a red jacket today.",
      speaker: "Maja",
      cue: { t: "Snygg! Vad har du på dig idag?", en: "Nice! What are you wearing today?" },
      expect: { t: "Jag har på mig en röd jacka.", en: "I'm wearing a red jacket." },
      reaction: { t: "Den köpte du ju här!", en: "You bought that here!" },
      accept: ["^jag har på mig (en )?röd jacka\\b"],
    },
  ],
  "ta-paa-dig": [
    {
      situation: "Leo is heading out into the snow in a T-shirt.",
      speaker: "Leo",
      cue: { t: "Hej då, jag går ut nu!", en: "Bye, I'm going out now!" },
      expect: { t: "Ta på dig jackan!", en: "Put your jacket on!" },
      reaction: { t: "Okej, mamma …", en: "Okay, mum …" },
      accept: ["^ta på dig \\p{L}+"],
      pitch: 1.3,
    },
    {
      situation: "It's freezing and Lisa has no hat.",
      speaker: "Lisa",
      cue: { t: "Jag fryser om öronen!", en: "My ears are freezing!" },
      expect: { t: "Ta på dig mössan!", en: "Put your hat on!" },
      reaction: { t: "Tack! Nu är det bättre.", en: "Thanks! That's better." },
      accept: ["^ta på dig (mössan|en mössa)\\b"],
      pitch: 1.45,
    },
  ],
};

// ---------- Leo: directions, free time and meeting up ----------

export const leo: Beats = {
  "hur-kommer-jag-till": [
    {
      situation: "You want to get to the lighthouse.",
      speaker: "Leo",
      cue: { t: "Hej! Vart ska du?", en: "Hi! Where are you going?" },
      reaction: { t: "Gå rakt fram och sedan upp på berget!", en: "Go straight ahead and then up the hill!" },
      accept: ["^(ursäkta )?hur kommer jag till \\p{L}+"],
    },
    {
      situation: "You want to get to the shop.",
      speaker: "Leo",
      cue: { t: "Behöver du hjälp?", en: "Do you need help?" },
      expect: { t: "Hur kommer jag till affären?", en: "How do I get to the shop?" },
      reaction: { t: "Gå ner mot bryggan. Den ligger till höger.", en: "Go down towards the dock. It's on the right." },
      accept: ["^(ja )?(ursäkta )?hur kommer jag till (affären|lanthandeln)\\b"],
    },
  ],
  "till-vaenster": [
    {
      situation: "Coming from the dock, the café is on the left of the square.",
      speaker: "Turist",
      cue: { t: "Ursäkta, var ligger kaféet?", en: "Excuse me, where is the café?" },
      expect: { t: "Till vänster.", en: "On the left." },
      reaction: { t: "Tack!", en: "Thanks!" },
      accept: ["\\btill vänster\\b"],
      pitch: 0.85,
    },
    {
      situation: "The path to the library turns left.",
      speaker: "Lisa",
      cue: { t: "Vilken väg till biblioteket?", en: "Which way to the library?" },
      expect: { t: "Till vänster!", en: "To the left!" },
      reaction: { t: "Tack! Nu springer jag!", en: "Thanks! I'm off!" },
      accept: ["\\btill vänster\\b"],
      pitch: 1.45,
    },
  ],
  "till-hoeger": [
    {
      situation: "Coming from the dock, the station is on the right of the square.",
      speaker: "Turist",
      cue: { t: "Ursäkta, var ligger stationen?", en: "Excuse me, where is the station?" },
      expect: { t: "Till höger.", en: "On the right." },
      reaction: { t: "Tack så mycket!", en: "Thank you very much!" },
      accept: ["\\btill höger\\b"],
      pitch: 0.85,
    },
    {
      situation: "Walking up from the ferry, Nils's boathouse is on the right.",
      speaker: "Anna",
      cue: { t: "Var är sjöboden?", en: "Where's the boathouse?" },
      expect: { t: "Till höger!", en: "On the right!" },
      reaction: { t: "Tack! Jag ska köpa fisk.", en: "Thanks! I'm going to buy fish." },
      accept: ["\\btill höger\\b"],
      pitch: 1.2,
    },
  ],
  "rakt-fram": [
    {
      situation: "A tourist on the dock asks for the square. It's straight up the lane.",
      speaker: "Turist",
      cue: { t: "Ursäkta, var ligger torget?", en: "Excuse me, where's the square?" },
      expect: { t: "Rakt fram!", en: "Straight ahead!" },
      reaction: { t: "Tack, det var lätt!", en: "Thanks, that was easy!" },
      accept: ["\\brakt fram\\b"],
      pitch: 0.85,
    },
    {
      situation: "You and Leo are walking to the lighthouse. The path goes straight on.",
      speaker: "Leo",
      cue: { t: "Höger eller vänster?", en: "Right or left?" },
      expect: { t: "Rakt fram!", en: "Straight ahead!" },
      reaction: { t: "Precis, rakt fram och upp!", en: "Exactly, straight ahead and up!" },
      accept: ["\\brakt fram\\b"],
    },
  ],
  "jag-har-gaatt-vilse": [
    {
      situation: "Leo finds you wandering in the forest.",
      speaker: "Leo",
      cue: { t: "Hej! Vad gör du här i skogen?", en: "Hi! What are you doing here in the forest?" },
      reaction: { t: "Ingen fara, följ med mig!", en: "No worries, come with me!" },
      accept: ["\\bjag har gått vilse\\b"],
    },
    {
      situation: "Karin sees you looking at your map, confused.",
      speaker: "Karin",
      cue: { t: "Är allt bra?", en: "Is everything okay?" },
      reaction: { t: "Vart ska du? Jag visar dig.", en: "Where are you going? I'll show you." },
      accept: ["\\bjag har gått vilse\\b"],
      pitch: 1.1,
    },
  ],
  "daer-borta": [
    {
      situation: "A tourist is looking for the lighthouse. You can see it.",
      speaker: "Turist",
      cue: { t: "Var är fyren?", en: "Where's the lighthouse?" },
      expect: { t: "Där borta!", en: "Over there!" },
      reaction: { t: "Åh, vad fin den är!", en: "Oh, how pretty it is!" },
      accept: ["\\bdär borta\\b"],
      pitch: 1.1,
    },
    {
      situation: "Lisa has lost her ball. It's by the bench.",
      speaker: "Lisa",
      cue: { t: "Var är min boll?", en: "Where's my ball?" },
      expect: { t: "Där borta!", en: "Over there!" },
      reaction: { t: "Tack!", en: "Thanks!" },
      accept: ["\\bdär borta\\b"],
      pitch: 1.45,
    },
  ],
  "vad-goer-du-paa-fritiden": [
    {
      situation: "Leo has the whole weekend off. Ask what he does in his free time.",
      speaker: "Leo",
      cue: { t: "Jag är ledig hela helgen!", en: "I'm free all weekend!" },
      reaction: { t: "Jag spelar gitarr och läser!", en: "I play the guitar and read!" },
      accept: ["^vad gör du på fritiden\\b"],
    },
    {
      situation: "Nils is done for the day. Ask what he does in his free time.",
      speaker: "Nils",
      cue: { t: "Nu har jag slutat för idag.", en: "Now I've finished for today." },
      reaction: { t: "Jag fiskar, såklart!", en: "I go fishing, of course!" },
      accept: ["^vad gör du på fritiden\\b"],
      pitch: 0.8,
    },
  ],
  "jag-gillar-att": [
    {
      situation: "Leo asks about your hobbies.",
      speaker: "Leo",
      cue: { t: "Vad gör du på fritiden?", en: "What do you do in your free time?" },
      reaction: { t: "Jag också!", en: "Me too!" },
      accept: ["^jag gillar att \\p{L}+", "^jag tycker om att \\p{L}+"],
      notWith: ["jag-tycker-om"],
    },
    {
      situation: "Karin wonders what you like to do.",
      speaker: "Karin",
      cue: { t: "Vad gillar du att göra?", en: "What do you like doing?" },
      reaction: { t: "Vad kul!", en: "How fun!" },
      accept: ["^jag gillar att \\p{L}+", "^jag tycker om att \\p{L}+"],
      notWith: ["jag-tycker-om"],
      pitch: 1.1,
    },
  ],
  "spelar-du": [
    {
      situation: "Leo shows you a new guitar.",
      speaker: "Leo",
      cue: { t: "Titta, min nya gitarr!", en: "Look, my new guitar!" },
      expect: { t: "Spelar du gitarr?", en: "Do you play the guitar?" },
      reaction: { t: "Ja, varje dag!", en: "Yes, every day!" },
      accept: ["^spelar du gitarr\\b"],
    },
    {
      situation: "Lisa is holding a new football.",
      speaker: "Lisa",
      cue: { t: "Jag har en ny fotboll!", en: "I've got a new football!" },
      expect: { t: "Spelar du fotboll?", en: "Do you play football?" },
      reaction: { t: "Ja! Kom och spela!", en: "Yes! Come and play!" },
      accept: ["^spelar du fotboll\\b"],
      pitch: 1.45,
    },
  ],
  "jag-aer-bra-paa": [
    {
      situation: "Leo asks what you're good at.",
      speaker: "Leo",
      cue: { t: "Vad är du bra på?", en: "What are you good at?" },
      reaction: { t: "Coolt! Ska vi simma till stenen?", en: "Cool! Shall we swim to the rock?" },
      accept: ["^jag är (inte )?(så |jätte)?bra på \\p{L}+"],
    },
    {
      situation: "Nils asks if you can fish. You can't really.",
      speaker: "Nils",
      cue: { t: "Kan du fiska?", en: "Can you fish?" },
      expect: { t: "Nej, jag är inte bra på att fiska.", en: "No, I'm not good at fishing." },
      reaction: { t: "Jag lär dig!", en: "I'll teach you!" },
      accept: ["\\bjag är inte (så )?bra på (att )?fiska\\b"],
      pitch: 0.8,
    },
  ],
  "vill-du": [
    {
      situation: "It's hot. Ask Leo if he wants to go for a swim.",
      speaker: "Leo",
      cue: { t: "Puh, vad varmt!", en: "Phew, it's hot!" },
      expect: { t: "Vill du bada?", en: "Do you want to go for a swim?" },
      reaction: { t: "Ja! Vi ses vid stranden!", en: "Yes! See you at the beach!" },
      accept: ["^vill du (bada|simma)\\b"],
    },
    {
      situation: "Karin is on her break. Ask if she wants a coffee.",
      speaker: "Karin",
      cue: { t: "Jag har paus nu.", en: "I'm on my break now." },
      expect: { t: "Vill du fika?", en: "Do you want to get a coffee?" },
      reaction: { t: "Gärna! Jag bjuder.", en: "I'd love to! It's on me." },
      accept: ["^vill du fika\\b"],
      pitch: 1.1,
    },
  ],
  "ja-gaerna": [
    {
      situation: "Leo invites you to the beach.",
      speaker: "Leo",
      cue: { t: "Vill du följa med till stranden?", en: "Do you want to come to the beach?" },
      reaction: { t: "Kul! Vi ses klockan tre!", en: "Great! See you at three!" },
      accept: ["^(ja )?gärna\\b"],
    },
    {
      situation: "Maja offers you a coffee in the shop.",
      speaker: "Maja",
      cue: { t: "Vill du ha en kopp kaffe?", en: "Would you like a cup of coffee?" },
      reaction: { t: "Mjölk?", en: "Milk?" },
      accept: ["^(ja )?gärna\\b"],
      pitch: 1.2,
    },
  ],
  "jag-kan-inte": [
    {
      situation: "Leo wants to play football tonight. You're busy.",
      speaker: "Leo",
      cue: { t: "Vill du spela fotboll ikväll?", en: "Do you want to play football tonight?" },
      expect: { t: "Tyvärr, jag kan inte.", en: "Sorry, I can't." },
      reaction: { t: "Okej, en annan gång!", en: "Okay, another time!" },
      accept: ["\\bjag kan inte\\b"],
      notWith: ["tyvaerr", "en-annan-gaang", "jag-hinner-inte", "jag-aer-upptagen"],
    },
    {
      situation: "Olle invites you for dinner on Saturday. You're away.",
      speaker: "Olle",
      cue: { t: "Vill du äta middag hos mig på lördag?", en: "Would you like to have dinner at mine on Saturday?" },
      expect: { t: "Tyvärr, jag kan inte.", en: "Sorry, I can't." },
      reaction: { t: "Vad synd! Nästa lördag då?", en: "What a shame! Next Saturday then?" },
      accept: ["\\bjag kan inte\\b"],
      notWith: ["tyvaerr", "en-annan-gaang", "jag-hinner-inte", "jag-aer-upptagen"],
      pitch: 0.7,
    },
  ],
  "ska-vi-ses": [
    {
      situation: "Leo has time tomorrow. Suggest meeting up.",
      speaker: "Leo",
      cue: { t: "Jag har tid imorgon.", en: "I have time tomorrow." },
      reaction: { t: "Ja! Klockan tre?", en: "Yes! Three o'clock?" },
      accept: ["^ska vi ses \\p{L}+"],
    },
    {
      situation: "Karin is off on Friday. Suggest meeting then.",
      speaker: "Karin",
      cue: { t: "Jag är ledig på fredag.", en: "I'm off on Friday." },
      expect: { t: "Ska vi ses på fredag?", en: "Shall we meet on Friday?" },
      reaction: { t: "Gärna! Vi fikar hos Bosse.", en: "I'd love to! Let's have coffee at Bosse's." },
      accept: ["^ska vi ses (på )?fredag\\b"],
      pitch: 1.1,
    },
  ],
  "vi-ses-vid": [
    {
      situation: "Leo asks where to meet. Say the dock.",
      speaker: "Leo",
      cue: { t: "Var ses vi?", en: "Where shall we meet?" },
      reaction: { t: "Okej, vid bryggan!", en: "Okay, at the dock!" },
      accept: ["^vi ses vid \\p{L}+"],
    },
    {
      situation: "Leo asks where to meet. Say the library.",
      speaker: "Leo",
      cue: { t: "Okej! Var ses vi?", en: "Okay! Where shall we meet?" },
      expect: { t: "Vi ses vid biblioteket!", en: "See you at the library!" },
      reaction: { t: "Perfekt!", en: "Perfect!" },
      accept: ["^vi ses vid biblioteket\\b"],
    },
  ],
  "jag-bjuder": [
    {
      situation: "At the café, Leo can't find his money.",
      speaker: "Leo",
      cue: { t: "Oj, jag har inga pengar!", en: "Oh no, I don't have any money!" },
      reaction: { t: "Tack! Nästa gång bjuder jag.", en: "Thanks! Next time it's on me." },
      accept: ["^(ingen fara )?jag bjuder\\b"],
    },
    {
      situation: "You and Karin finish your coffee.",
      speaker: "Karin",
      cue: { t: "Vem betalar?", en: "Who's paying?" },
      reaction: { t: "Vad snällt, tack!", en: "How kind, thanks!" },
      accept: ["^jag bjuder\\b"],
      pitch: 1.1,
    },
  ],
};

// ---------- Astrid: nature and the future ----------

export const astrid: Beats = {
  titta: [
    {
      situation: "An elk walks out of the forest. Point it out to Astrid.",
      speaker: "Astrid",
      cue: { t: "Vad är det?", en: "What's that?" },
      expect: { t: "Titta, en älg!", en: "Look, an elk!" },
      reaction: { t: "Oj, vad stor den är!", en: "Wow, it's so big!" },
      accept: ["^titta\\b"],
    },
    {
      situation: "A fox runs through Astrid's garden.",
      speaker: "Astrid",
      cue: { t: "Vad tittar du på?", en: "What are you looking at?" },
      expect: { t: "Titta, en räv!", en: "Look, a fox!" },
      reaction: { t: "Åh nej, mina höns!", en: "Oh no, my hens!" },
      accept: ["^titta\\b"],
    },
  ],
  lyssna: [
    {
      situation: "A cuckoo calls from the forest.",
      speaker: "Astrid",
      cue: { t: "Hör du?", en: "Can you hear that?" },
      expect: { t: "Lyssna, en fågel!", en: "Listen, a bird!" },
      reaction: { t: "Ja, det är en gök!", en: "Yes, it's a cuckoo!" },
      accept: ["^lyssna\\b"],
    },
    {
      situation: "Waves crash on the rocks below the garden.",
      speaker: "Astrid",
      cue: { t: "Vad är det för ljud?", en: "What's that sound?" },
      expect: { t: "Lyssna, havet!", en: "Listen, the sea!" },
      reaction: { t: "Ja, havet sjunger idag.", en: "Yes, the sea is singing today." },
      accept: ["^lyssna\\b"],
    },
  ],
  plocka: [
    {
      situation: "The bushes are full of blueberries.",
      speaker: "Astrid",
      cue: { t: "Titta, så mycket blåbär!", en: "Look, so many blueberries!" },
      expect: { t: "Ska vi plocka?", en: "Shall we pick some?" },
      reaction: { t: "Ja! Här är en hink.", en: "Yes! Here's a bucket." },
      accept: ["\\bplocka\\b"],
    },
    {
      situation: "Astrid says there are mushrooms in the forest.",
      speaker: "Astrid",
      cue: { t: "Det finns svamp i skogen nu.", en: "There are mushrooms in the forest now." },
      expect: { t: "Ska vi plocka svamp?", en: "Shall we pick mushrooms?" },
      reaction: { t: "Gärna! Men bara de goda.", en: "Gladly! But only the good ones." },
      accept: ["\\bplocka\\b"],
    },
  ],
  vattna: [
    {
      situation: "Astrid's flowers are dry and drooping.",
      speaker: "Astrid",
      cue: { t: "Blommorna är så torra!", en: "The flowers are so dry!" },
      expect: { t: "Jag kan vattna dem.", en: "I can water them." },
      reaction: { t: "Tack, lilla vän!", en: "Thank you, little friend!" },
      accept: ["\\bvattna\\b"],
    },
    {
      situation: "Astrid is going away for the weekend.",
      speaker: "Astrid",
      cue: { t: "Jag åker bort i helgen.", en: "I'm going away this weekend." },
      expect: { t: "Jag kan vattna blommorna.", en: "I can water the flowers." },
      reaction: { t: "Vad snällt av dig!", en: "How kind of you!" },
      accept: ["\\bvattna\\b"],
    },
  ],
  vacker: [
    {
      situation: "You stand at the top of the lighthouse with Olle.",
      speaker: "Olle",
      cue: { t: "Vad tycker du om utsikten?", en: "What do you think of the view?" },
      expect: { t: "Den är vacker!", en: "It's beautiful!" },
      reaction: { t: "Ja, den bästa på ön!", en: "Yes, the best on the island!" },
      accept: ["\\bvack(er|ert|ra)\\b"],
      pitch: 0.7,
    },
    {
      situation: "Astrid shows you her roses.",
      speaker: "Astrid",
      cue: { t: "Titta på mina rosor!", en: "Look at my roses!" },
      expect: { t: "Vad vackra!", en: "How beautiful!" },
      reaction: { t: "Tack! De är min stolthet.", en: "Thank you! They're my pride and joy." },
      accept: ["\\bvack(er|ert|ra)\\b"],
    },
  ],
  "jag-ska": [
    {
      situation: "Astrid asks about your summer.",
      speaker: "Astrid",
      cue: { t: "Vad ska du göra i sommar?", en: "What are you going to do this summer?" },
      reaction: { t: "Vad roligt! Berätta mer!", en: "How lovely! Tell me more!" },
      accept: ["^(i sommar )?(jag ska|ska jag) \\p{L}+"],
    },
    {
      situation: "Leo asks what you're doing tomorrow. You're going swimming.",
      speaker: "Leo",
      cue: { t: "Vad ska du göra imorgon?", en: "What are you doing tomorrow?" },
      expect: { t: "Jag ska bada.", en: "I'm going swimming." },
      reaction: { t: "Jag med!", en: "Me too!" },
      accept: ["^(imorgon )?(jag ska|ska jag) (bada|simma)\\b"],
      pitch: 1.3,
    },
  ],
  "jag-vill-bli": [
    {
      situation: "Lisa tells you her dream job and asks yours.",
      speaker: "Lisa",
      cue: { t: "Jag vill bli astronaut! Och du?", en: "I want to be an astronaut! And you?" },
      reaction: { t: "Coolt!", en: "Cool!" },
      accept: ["^jag vill bli \\p{L}+"],
      pitch: 1.45,
    },
    {
      situation: "Astrid teases you about growing up.",
      speaker: "Astrid",
      cue: { t: "Vad vill du bli när du blir stor?", en: "What do you want to be when you grow up?" },
      reaction: { t: "Haha, men du är ju redan stor!", en: "Haha, but you're already grown up!" },
      accept: ["^jag vill bli \\p{L}+"],
    },
  ],
  "jag-hoppas": [
    {
      situation: "Tomorrow is midsummer.",
      speaker: "Astrid",
      cue: { t: "Imorgon är det midsommar!", en: "Tomorrow is midsummer!" },
      expect: { t: "Jag hoppas att det blir sol.", en: "I hope it'll be sunny." },
      reaction: { t: "Det hoppas jag också!", en: "I hope so too!" },
      accept: ["^jag hoppas \\p{L}+"],
    },
    {
      situation: "Leo's team has a football match tomorrow.",
      speaker: "Leo",
      cue: { t: "Vi har match imorgon.", en: "We have a match tomorrow." },
      expect: { t: "Jag hoppas att ni vinner!", en: "I hope you win!" },
      reaction: { t: "Tack!", en: "Thanks!" },
      accept: ["^jag hoppas (att )?ni vinner\\b"],
      pitch: 1.3,
    },
  ],
  "har-du-naagra-planer": [
    {
      situation: "Summer is coming. Ask Astrid about her plans.",
      speaker: "Astrid",
      cue: { t: "Snart är det sommar!", en: "It'll be summer soon!" },
      reaction: { t: "Jag ska plantera potatis!", en: "I'm going to plant potatoes!" },
      accept: ["^har du (några )?planer\\b"],
    },
    {
      situation: "School's out. Ask Leo about his plans.",
      speaker: "Leo",
      cue: { t: "Äntligen sommarlov!", en: "Summer holidays at last!" },
      reaction: { t: "Jag ska spela gitarr hela sommaren!", en: "I'm going to play guitar all summer!" },
      accept: ["^har du (några )?planer\\b"],
      pitch: 1.3,
    },
  ],
  "vi-faar-se": [
    {
      situation: "Astrid wonders if you'll come back next summer. You're not sure.",
      speaker: "Astrid",
      cue: { t: "Kommer du tillbaka nästa sommar?", en: "Will you come back next summer?" },
      reaction: { t: "Jag hoppas det!", en: "I hope so!" },
      accept: ["^vi får se\\b"],
    },
    {
      situation: "Leo asks if it'll be sunny tomorrow. Who knows?",
      speaker: "Leo",
      cue: { t: "Blir det sol imorgon?", en: "Will it be sunny tomorrow?" },
      reaction: { t: "Haha, du låter som Olle!", en: "Haha, you sound like Olle!" },
      accept: ["^vi får se\\b"],
      pitch: 1.3,
    },
  ],
};

// ---------- Olle: the past, feelings and opinions ----------

export const olle: Beats = {
  "vad-gjorde-du-igaar": [
    {
      situation: "Olle says he was in Stockholm yesterday. Ask what he did.",
      speaker: "Olle",
      cue: { t: "Jag var i Stockholm igår!", en: "I was in Stockholm yesterday!" },
      reaction: { t: "Jag gick på museum!", en: "I went to a museum!" },
      accept: ["^vad gjorde du( där| igår)?\\b"],
    },
    {
      situation: "Leo looks exhausted. Ask what he did yesterday.",
      speaker: "Leo",
      cue: { t: "Jag är så trött idag.", en: "I'm so tired today." },
      reaction: { t: "Jag spelade gitarr hela natten!", en: "I played the guitar all night!" },
      accept: ["^vad gjorde du( igår)?\\b"],
      pitch: 1.3,
    },
  ],
  "jag-var": [
    {
      situation: "You stayed home yesterday.",
      speaker: "Olle",
      cue: { t: "Var var du igår? Jag såg dig inte.", en: "Where were you yesterday? I didn't see you." },
      reaction: { t: "Hemma? Men det var så fint väder!", en: "At home? But the weather was so nice!" },
      accept: ["^(igår )?(jag var|var jag) \\p{L}+"],
    },
    {
      situation: "You spent the weekend in Stockholm.",
      speaker: "Olle",
      cue: { t: "Var var du i helgen?", en: "Where were you at the weekend?" },
      expect: { t: "Jag var i Stockholm.", en: "I was in Stockholm." },
      reaction: { t: "Stockholm! Där var jag för trettio år sedan.", en: "Stockholm! I was there thirty years ago." },
      accept: ["\\b(jag var|var jag) i stockholm\\b"],
    },
  ],
  "det-var": [
    {
      situation: "You had a great time at the party.",
      speaker: "Olle",
      cue: { t: "Hur var festen?", en: "How was the party?" },
      expect: { t: "Det var kul!", en: "It was fun!" },
      reaction: { t: "Vad bra!", en: "Good!" },
      accept: ["^det var (så |jätte)?(kul|roligt|jättekul)\\b"],
    },
    {
      situation: "The film was boring.",
      speaker: "Olle",
      cue: { t: "Hur var filmen?", en: "How was the film?" },
      expect: { t: "Det var tråkigt.", en: "It was boring." },
      reaction: { t: "Tråkigt? Vad synd!", en: "Boring? What a shame!" },
      accept: ["^det var (lite |så )?tråkigt\\b"],
    },
  ],
  "jag-saag": [
    {
      situation: "You saw an elk in the forest.",
      speaker: "Olle",
      cue: { t: "Vad såg du i skogen?", en: "What did you see in the forest?" },
      expect: { t: "Jag såg en älg!", en: "I saw an elk!" },
      reaction: { t: "En älg! Hur stor var den?", en: "An elk! How big was it?" },
      accept: ["^jag såg en älg\\b"],
    },
    {
      situation: "From the lighthouse you spotted a seal on the rocks.",
      speaker: "Olle",
      cue: { t: "Såg du något från fyren?", en: "Did you see anything from the lighthouse?" },
      reaction: { t: "En säl! De bor på stenarna där ute.", en: "A seal! They live on the rocks out there." },
      accept: ["^(ja )?jag såg en säl\\b"],
    },
  ],
  "vad-haende": [
    {
      situation: "Olle starts a story about a storm.",
      speaker: "Olle",
      cue: { t: "En natt kom en stor storm …", en: "One night a big storm came …" },
      reaction: { t: "Båten försvann! Men vi hittade den.", en: "The boat disappeared! But we found it." },
      accept: ["^vad hände\\b", "^och sen\\b"],
      notWith: ["och-sen"],
    },
    {
      situation: "Leo's guitar has a broken string.",
      speaker: "Leo",
      cue: { t: "Titta på min gitarr!", en: "Look at my guitar!" },
      reaction: { t: "Jag spelade för hårt!", en: "I played too hard!" },
      accept: ["^(oj )?vad hände\\b"],
      pitch: 1.3,
    },
  ],
  "hur-kaenner-du-dig": [
    {
      situation: "Olle sighs after climbing the lighthouse stairs.",
      speaker: "Olle",
      cue: { t: "Puh, vilken dag …", en: "Phew, what a day …" },
      reaction: { t: "Lite trött, men glad.", en: "A bit tired, but happy." },
      accept: ["^hur känner du dig\\b", "^hur mår du\\b"],
      notWith: ["hur-maar-du"],
    },
    {
      situation: "Karin worked all night at the health centre.",
      speaker: "Karin",
      cue: { t: "Jag har jobbat hela natten.", en: "I've worked all night." },
      reaction: { t: "Trött, men nöjd.", en: "Tired, but pleased." },
      accept: ["^hur känner du dig\\b", "^hur mår du\\b"],
      notWith: ["hur-maar-du"],
      pitch: 1.1,
    },
  ],
  "jag-kaenner-mig": [
    {
      situation: "Olle asks how you feel today.",
      speaker: "Olle",
      cue: { t: "Hur känner du dig idag?", en: "How do you feel today?" },
      reaction: { t: "Jag förstår. Tack för att du berättar.", en: "I see. Thanks for telling me." },
      accept: ["^jag känner mig \\p{L}+"],
    },
    {
      situation: "You were ill, but now you feel better.",
      speaker: "Karin",
      cue: { t: "Hur känner du dig nu?", en: "How do you feel now?" },
      expect: { t: "Jag känner mig bättre.", en: "I feel better." },
      reaction: { t: "Skönt att höra!", en: "Good to hear!" },
      accept: ["^jag känner mig (lite |mycket |mycket )?bättre\\b"],
      pitch: 1.1,
    },
  ],
  "vad-synd": [
    {
      situation: "Olle can't come to the party.",
      speaker: "Olle",
      cue: { t: "Jag kan inte komma på festen.", en: "I can't come to the party." },
      reaction: { t: "Ja, men nästa gång!", en: "Yes, but next time!" },
      accept: ["^(åh )?(vad synd|synd)\\b"],
    },
    {
      situation: "Leo's guitar is broken.",
      speaker: "Leo",
      cue: { t: "Min gitarr är trasig.", en: "My guitar is broken." },
      reaction: { t: "Mamma köper en ny.", en: "Mum's buying a new one." },
      accept: ["^(åh )?(vad synd|synd)\\b"],
      pitch: 1.3,
    },
  ],
  "vad-roligt": [
    {
      situation: "Olle has big news.",
      speaker: "Olle",
      cue: { t: "Jag ska bli morfar!", en: "I'm going to be a grandpa!" },
      reaction: { t: "Ja, jag är så glad!", en: "Yes, I'm so happy!" },
      accept: ["^(åh )?vad (roligt|kul)\\b"],
    },
    {
      situation: "Maja's daughter is coming home.",
      speaker: "Maja",
      cue: { t: "Min dotter kommer hem imorgon!", en: "My daughter is coming home tomorrow!" },
      reaction: { t: "Ja, jag har saknat henne!", en: "Yes, I've missed her!" },
      accept: ["^(åh )?vad (roligt|kul)\\b"],
      pitch: 1.2,
    },
  ],
  "oroa-dig-inte": [
    {
      situation: "Leo has a test tomorrow and is nervous.",
      speaker: "Leo",
      cue: { t: "Jag har prov imorgon, jag är så nervös!", en: "I've got a test tomorrow, I'm so nervous!" },
      reaction: { t: "Tack. Du har rätt.", en: "Thanks. You're right." },
      accept: ["^oroa dig inte\\b"],
      pitch: 1.3,
    },
    {
      situation: "Olle can't see his boat at the dock.",
      speaker: "Olle",
      cue: { t: "Min båt är borta!", en: "My boat is gone!" },
      reaction: { t: "Du har rätt, den är nog i hamnen.", en: "You're right, it's probably in the harbour." },
      accept: ["^oroa dig inte\\b"],
    },
  ],
  "jag-saknar": [
    {
      situation: "Olle notices you look a little sad.",
      speaker: "Olle",
      cue: { t: "Du ser ledsen ut.", en: "You look sad." },
      reaction: { t: "Ring dem ikväll!", en: "Call them tonight!" },
      accept: ["^jag saknar \\p{L}+"],
    },
    {
      situation: "You're thinking about your friends back home.",
      speaker: "Olle",
      cue: { t: "Vad tänker du på?", en: "What are you thinking about?" },
      expect: { t: "Jag saknar mina vänner.", en: "I miss my friends." },
      reaction: { t: "De kan hälsa på här!", en: "They can visit you here!" },
      accept: ["^jag saknar (mina )?vänner\\b"],
    },
  ],
  "vad-tycker-du": [
    {
      situation: "Olle has just finished a new book. Ask what he thinks of it.",
      speaker: "Olle",
      cue: { t: "Jag har läst en ny bok.", en: "I've read a new book." },
      reaction: { t: "Den är jättebra!", en: "It's really good!" },
      accept: ["^(och )?vad tycker du\\b"],
    },
    {
      situation: "Maja has a new coffee in the shop. Ask her opinion.",
      speaker: "Maja",
      cue: { t: "Vi har ett nytt kaffe i affären.", en: "We have a new coffee in the shop." },
      reaction: { t: "Det är starkt, men gott!", en: "It's strong, but good!" },
      accept: ["^(och )?vad tycker du\\b"],
      pitch: 1.2,
    },
  ],
  "jag-tycker-att": [
    {
      situation: "Olle asks what you think of Lilla Ö.",
      speaker: "Olle",
      cue: { t: "Vad tycker du om Lilla Ö?", en: "What do you think of Lilla Ö?" },
      reaction: { t: "Det tycker jag också!", en: "I think so too!" },
      accept: ["^jag tycker (att )?\\p{L}+"],
    },
    {
      situation: "Olle asks what you think of Swedish.",
      speaker: "Olle",
      cue: { t: "Vad tycker du om svenska?", en: "What do you think of Swedish?" },
      expect: { t: "Jag tycker att svenska är roligt.", en: "I think Swedish is fun." },
      reaction: { t: "Bra! Och du blir bättre varje dag.", en: "Good! And you're getting better every day." },
      accept: ["^jag tycker (att )?(svenska|det) är \\p{L}+"],
    },
  ],
  "jag-haaller-med": [
    {
      situation: "Olle makes a bold claim. You agree.",
      speaker: "Olle",
      cue: { t: "Bosses kanelbullar är bäst i Sverige!", en: "Bosse's cinnamon buns are the best in Sweden!" },
      reaction: { t: "Klart du gör!", en: "Of course you do!" },
      accept: ["^(ja )?jag håller med\\b", "^absolut\\b"],
      notWith: ["absolut", "det-staemmer"],
    },
    {
      situation: "Olle says summer is the best season. You agree.",
      speaker: "Olle",
      cue: { t: "Sommaren är den bästa årstiden.", en: "Summer is the best season." },
      reaction: { t: "Men vintern är också fin …", en: "But winter is nice too …" },
      accept: ["^(ja )?jag håller med\\b", "^absolut\\b"],
      notWith: ["absolut", "det-staemmer"],
    },
  ],
  "jag-haaller-inte-med": [
    {
      situation: "Olle says tea is better than coffee. You disagree.",
      speaker: "Olle",
      cue: { t: "Te är bättre än kaffe.", en: "Tea is better than coffee." },
      reaction: { t: "Haha, du låter som Bosse!", en: "Haha, you sound like Bosse!" },
      accept: ["\\bjag håller inte med\\b"],
    },
    {
      situation: "Olle says rain is the best weather. You disagree.",
      speaker: "Olle",
      cue: { t: "Regn är det bästa vädret.", en: "Rain is the best weather." },
      reaction: { t: "Nähä? Men blommorna tycker om regn!", en: "No? But the flowers like rain!" },
      accept: ["\\bjag håller inte med\\b"],
    },
  ],
  "det-beror-paa": [
    {
      situation: "Olle asks if it's better to live in a city or on an island.",
      speaker: "Olle",
      cue: { t: "Är det bättre att bo i stan eller på en ö?", en: "Is it better to live in a city or on an island?" },
      reaction: { t: "Klokt svar!", en: "Wise answer!" },
      accept: ["^(hmm )?det beror på\\b"],
    },
    {
      situation: "Leo can't decide what to do.",
      speaker: "Leo",
      cue: { t: "Ska vi bada eller spela fotboll?", en: "Shall we swim or play football?" },
      reaction: { t: "På vad? Vädret?", en: "On what? The weather?" },
      accept: ["^(hmm )?det beror på\\b"],
      pitch: 1.3,
    },
  ],
};
