import type { PracticeCharacter, PracticeScenario } from "@/types/practice";

// Live and typed conversations with the people of Lilla Ö.

export const characters: PracticeCharacter[] = [
  {
    id: "elin",
    name: "Elin",
    description: "Warm, quick-witted harbour keeper of Lilla Ö who greets every new arrival at the dock.",
  },
  {
    id: "bosse",
    name: "Bosse",
    description: "Jolly, round-bellied owner of Café Kanel; proud of his cinnamon buns and a little theatrical.",
  },
  {
    id: "stina",
    name: "Stina",
    description: "Brisk, kind station master who loves timetables and gently teases travellers who rush.",
  },
  {
    id: "astrid",
    name: "Astrid",
    description: "Unhurried old gardener on the hill who has seen every summer on the island and loves making plans.",
  },
];

export const scenarios: PracticeScenario[] = [
  {
    id: "meet-elin",
    languageCode: "sv",
    characterId: "elin",
    title: "Meet Elin",
    setting: "You have just stepped off the ferry onto the dock of Lilla Ö, a small Swedish island village.",
    learnerRole: "Introduce yourself and get to know Elin.",
    characterRole: "The friendly harbour keeper meeting you for the first time.",
    goal: "Exchange names and complete a short, natural introduction.",
    openingLine: "Hej! Jag heter Elin. Vad heter du?",
    openingEnglish: "Hi! My name is Elin. What is your name?",
    style: "roleplay",
    requiredConceptSlugs: ["hej", "jag-heter"],
    optionalConceptSlugs: ["vad-heter-du", "trevligt-att-traeffas", "ja", "nej"],
    minimumEncountered: 0,
    minimumTurns: 3,
    maximumTurns: 5,
    starterHints: [
      { target: "Hej, jag heter …", english: "Hi, my name is …" },
      { target: "Trevligt att träffas.", english: "Nice to meet you." },
    ],
    fallbackReplies: [
      { target: "Trevligt att träffas! Vad gör du på dagarna?", english: "Nice to meet you! What do you do during the day?" },
      { target: "Det låter bra. Bor du här i stan?", english: "That sounds good. Do you live here in the city?" },
      { target: "Kul att träffas. Vi ses snart igen!", english: "Great to meet you. See you again soon!" },
    ],
  },
  {
    id: "fika-order",
    languageCode: "sv",
    characterId: "bosse",
    title: "Fika at Café Kanel",
    setting: "You step up to the counter of Café Kanel, the island's cosy café.",
    learnerRole: "Choose something and order it naturally.",
    characterRole: "Bosse, the café owner taking your order and chatting while he works.",
    goal: "Order a drink or pastry and respond to one follow-up question.",
    openingLine: "Välkommen till Café Kanel! Vad är du sugen på?",
    openingEnglish: "Welcome to Café Kanel! What are you in the mood for?",
    style: "roleplay",
    requiredConceptSlugs: ["jag-skulle-vilja", "kaffe", "tack"],
    optionalConceptSlugs: ["te", "vatten", "kanelbulle", "med-mjoelk", "cafe-ask-bill"],
    minimumEncountered: 2,
    minimumTurns: 3,
    maximumTurns: 6,
    starterHints: [
      { target: "Jag skulle vilja ha …", english: "I would like …" },
      { target: "… med mjölk, tack.", english: "… with milk, please." },
    ],
    fallbackReplies: [
      { target: "Bra val. Vill du också ha en kanelbulle?", english: "Good choice. Would you also like a cinnamon roll?" },
      { target: "Vill du sitta här eller ta med?", english: "Do you want to sit here or take it away?" },
      { target: "Varsågod! Det blir fyrtio kronor.", english: "Here you go! That will be forty kronor." },
    ],
  },
  {
    id: "centralstation-change",
    languageCode: "sv",
    characterId: "stina",
    title: "A change at the station",
    setting: "You are at the island's little railway station, about to take the train to the mainland.",
    learnerRole: "Find the right train and explain where you need to get off.",
    characterRole: "Stina, the station master helping travellers.",
    goal: "Ask for direction, check the train, and confirm your stop.",
    openingLine: "Hej hej! Spåret har ändrats idag. Vart ska du?",
    openingEnglish: "Hi there! The platform has changed today. Where are you going?",
    style: "roleplay",
    requiredConceptSlugs: ["var-ligger-stationen", "taget-till-stockholm", "jag-ska-av-haer"],
    optionalConceptSlugs: ["kan-du-upprepa", "prata-langsammare", "jag-foerstar-inte"],
    minimumEncountered: 2,
    minimumTurns: 4,
    maximumTurns: 6,
    starterHints: [
      { target: "Var ligger …?", english: "Where is …?" },
      { target: "Går det här tåget till …?", english: "Does this train go to …?" },
    ],
    fallbackReplies: [
      { target: "Tåget till Stockholm går från spår två.", english: "The train to Stockholm leaves from platform two." },
      { target: "Ja, det är rätt tåg. Var ska du gå av?", english: "Yes, this is the right train. Where are you getting off?" },
      { target: "Bra. Trevlig resa!", english: "Good. Have a nice trip!" },
    ],
  },
  {
    id: "make-weekend-plans",
    languageCode: "sv",
    characterId: "astrid",
    title: "Make a plan",
    setting: "Astrid, resting in her hilltop garden, asks what you want to do this weekend.",
    learnerRole: "Share a preference and suggest a plan.",
    characterRole: "Astrid, an old friend making plans with you.",
    goal: "Respond openly, suggest an activity, and agree on a next step.",
    openingLine: "Har du planer i helgen? Ska vi hitta på något?",
    openingEnglish: "Do you have plans this weekend? Should we think of something to do?",
    style: "open_question",
    requiredConceptSlugs: ["kanske", "ska-vi-infinitive"],
    optionalConceptSlugs: ["ja", "nej", "kan-du-upprepa"],
    minimumEncountered: 1,
    minimumTurns: 3,
    maximumTurns: 5,
    starterHints: [
      { target: "Kanske …", english: "Maybe …" },
      { target: "Ska vi …?", english: "Should we …?" },
    ],
    fallbackReplies: [
      { target: "Det vore trevligt. När passar det dig?", english: "That would be nice. When works for you?" },
      { target: "Kanske på lördag?", english: "Maybe Saturday?" },
      { target: "Då har vi en plan.", english: "Then we have a plan." },
    ],
  },
];
