import type { PracticeCharacter, PracticeScenario } from "@/types/practice";

// Live and typed conversations with the people of Lilla Ö.

export const characters: PracticeCharacter[] = [
  {
    id: "elin",
    name: "Elin",
    description: "Warm, quick-witted harbour keeper of Lilla Ö who greets every new arrival at the dock.",
  },
  {
    id: "bosse",
    name: "Bosse",
    description: "Jolly, round-bellied owner of Café Kanel; proud of his cinnamon buns and a little theatrical.",
  },
  {
    id: "stina",
    name: "Stina",
    description: "Brisk, kind station master who loves timetables and gently teases travellers who rush.",
  },
  {
    id: "astrid",
    name: "Astrid",
    description: "Unhurried old gardener on the hill who has seen every summer on the island and loves making plans.",
  },
  {
    id: "nils",
    name: "Nils",
    description: "Weather-beaten, cheerful fisherman who counts his catch out loud and reads the sky before every trip.",
  },
  {
    id: "karin",
    name: "Karin",
    description: "Calm, caring island nurse and Leo's mum; asks how you really are and loves hearing about families.",
  },
  {
    id: "maja",
    name: "Maja",
    description: "Chatty, quick shopkeeper of Lanthandeln who sells everything from bread to wool hats and knows every home on the island.",
  },
  {
    id: "leo",
    name: "Leo",
    description: "Enthusiastic fifteen-year-old bookworm and guitar player who knows every path on the island and is always making plans.",
  },
  {
    id: "olle",
    name: "Olle",
    description: "Retired lighthouse keeper with forty years of island stories and a firm opinion on everything, from coffee to the weather.",
  },
];

export const scenarios: PracticeScenario[] = [
  {
    id: "meet-elin",
    languageCode: "sv",
    characterId: "elin",
    title: "Meet Elin",
    setting: "You have just stepped off the ferry onto the dock of Lilla Ö, a small Swedish island village.",
    learnerRole: "Introduce yourself and get to know Elin.",
    characterRole: "The friendly harbour keeper meeting you for the first time.",
    goal: "Exchange names and complete a short, natural introduction.",
    openingLine: "Hej! Jag heter Elin. Vad heter du?",
    openingEnglish: "Hi! My name is Elin. What is your name?",
    style: "roleplay",
    requiredConceptSlugs: ["hej", "jag-heter"],
    optionalConceptSlugs: ["vad-heter-du", "trevligt-att-traeffas", "ja", "nej"],
    minimumEncountered: 0,
    minimumTurns: 3,
    maximumTurns: 5,
    starterHints: [
      { target: "Hej, jag heter …", english: "Hi, my name is …" },
      { target: "Trevligt att träffas.", english: "Nice to meet you." },
    ],
    fallbackReplies: [
      { target: "Trevligt att träffas! Vad gör du på dagarna?", english: "Nice to meet you! What do you do during the day?" },
      { target: "Det låter bra. Bor du här i stan?", english: "That sounds good. Do you live here in the city?" },
      { target: "Kul att träffas. Vi ses snart igen!", english: "Great to meet you. See you again soon!" },
    ],
  },
  {
    id: "fika-order",
    languageCode: "sv",
    characterId: "bosse",
    title: "Fika at Café Kanel",
    setting: "You step up to the counter of Café Kanel, the island's cosy café.",
    learnerRole: "Choose something and order it naturally.",
    characterRole: "Bosse, the café owner taking your order and chatting while he works.",
    goal: "Order a drink or pastry and respond to one follow-up question.",
    openingLine: "Välkommen till Café Kanel! Vad är du sugen på?",
    openingEnglish: "Welcome to Café Kanel! What are you in the mood for?",
    style: "roleplay",
    requiredConceptSlugs: ["jag-skulle-vilja", "kaffe", "tack"],
    optionalConceptSlugs: ["te", "vatten", "kanelbulle", "med-mjoelk", "cafe-ask-bill"],
    minimumEncountered: 2,
    minimumTurns: 3,
    maximumTurns: 6,
    starterHints: [
      { target: "Jag skulle vilja ha …", english: "I would like …" },
      { target: "… med mjölk, tack.", english: "… with milk, please." },
    ],
    fallbackReplies: [
      { target: "Bra val. Vill du också ha en kanelbulle?", english: "Good choice. Would you also like a cinnamon roll?" },
      { target: "Vill du sitta här eller ta med?", english: "Do you want to sit here or take it away?" },
      { target: "Varsågod! Det blir fyrtio kronor.", english: "Here you go! That will be forty kronor." },
    ],
  },
  {
    id: "centralstation-change",
    languageCode: "sv",
    characterId: "stina",
    title: "A change at the station",
    setting: "You are at the island's little railway station, about to take the train to the mainland.",
    learnerRole: "Find the right train and explain where you need to get off.",
    characterRole: "Stina, the station master helping travellers.",
    goal: "Ask for direction, check the train, and confirm your stop.",
    openingLine: "Hej hej! Spåret har ändrats idag. Vart ska du?",
    openingEnglish: "Hi there! The platform has changed today. Where are you going?",
    style: "roleplay",
    requiredConceptSlugs: ["var-ligger-stationen", "taget-till-stockholm", "jag-ska-av-haer"],
    optionalConceptSlugs: ["kan-du-upprepa", "prata-langsammare", "jag-foerstar-inte"],
    minimumEncountered: 2,
    minimumTurns: 4,
    maximumTurns: 6,
    starterHints: [
      { target: "Var ligger …?", english: "Where is …?" },
      { target: "Går det här tåget till …?", english: "Does this train go to …?" },
    ],
    fallbackReplies: [
      { target: "Tåget till Stockholm går från spår två.", english: "The train to Stockholm leaves from platform two." },
      { target: "Ja, det är rätt tåg. Var ska du gå av?", english: "Yes, this is the right train. Where are you getting off?" },
      { target: "Bra. Trevlig resa!", english: "Good. Have a nice trip!" },
    ],
  },
  {
    id: "make-weekend-plans",
    languageCode: "sv",
    characterId: "astrid",
    title: "Make a plan",
    setting: "Astrid, resting in her hilltop garden, asks what you want to do this weekend.",
    learnerRole: "Share a preference and suggest a plan.",
    characterRole: "Astrid, an old friend making plans with you.",
    goal: "Respond openly, suggest an activity, and agree on a next step.",
    openingLine: "Har du planer i helgen? Ska vi hitta på något?",
    openingEnglish: "Do you have plans this weekend? Should we think of something to do?",
    style: "open_question",
    requiredConceptSlugs: ["kanske", "ska-vi-infinitive"],
    optionalConceptSlugs: ["ja", "nej", "kan-du-upprepa"],
    minimumEncountered: 1,
    minimumTurns: 3,
    maximumTurns: 5,
    starterHints: [
      { target: "Kanske …", english: "Maybe …" },
      { target: "Ska vi …?", english: "Should we …?" },
    ],
    fallbackReplies: [
      { target: "Det vore trevligt. När passar det dig?", english: "That would be nice. When works for you?" },
      { target: "Kanske på lördag?", english: "Maybe Saturday?" },
      { target: "Då har vi en plan.", english: "Then we have a plan." },
    ],
  },
  {
    id: "i-hamnen",
    languageCode: "sv",
    characterId: "nils",
    title: "In the harbour",
    setting: "Nils is sorting today's catch outside his red boathouse by the water.",
    learnerRole: "Chat about the catch, count and talk about the weather.",
    characterRole: "Nils, the fisherman, proud of his catch and always watching the sky.",
    goal: "Ask how many fish he caught, say a number and talk about the weather.",
    openingLine: "Hej! Titta, så många fiskar! Gissa hur många!",
    openingEnglish: "Hi! Look, so many fish! Guess how many!",
    style: "roleplay",
    requiredConceptSlugs: ["hur-maanga", "tio"],
    optionalConceptSlugs: ["en-fisk", "hur-aer-vaedret", "det-blaaser", "solen-skiner", "det-regnar", "vad-kostar-det", "tjugo"],
    minimumEncountered: 2,
    minimumTurns: 3,
    maximumTurns: 6,
    starterHints: [
      { target: "Hur många …?", english: "How many …?" },
      { target: "Det är …", english: "It's …" },
    ],
    fallbackReplies: [
      { target: "Nästan! Det är tolv fiskar.", english: "Almost! It's twelve fish." },
      { target: "Hur är vädret där du bor?", english: "What's the weather like where you live?" },
      { target: "Imorgon ska det blåsa. Då stannar jag hemma.", english: "Tomorrow it's going to be windy. Then I'll stay home." },
    ],
  },
  {
    id: "paa-vaardcentralen",
    languageCode: "sv",
    characterId: "karin",
    title: "At the health centre",
    setting: "You drop into the island's small health centre, where Karin, the nurse, is having a quiet afternoon.",
    learnerRole: "Say how you feel, what hurts, and chat about family.",
    characterRole: "Karin, the kind island nurse, asking how you are and giving simple advice.",
    goal: "Explain what hurts, listen to her advice, and answer a question about your family.",
    openingLine: "Hej och välkommen! Hur mår du idag?",
    openingEnglish: "Hi and welcome! How are you today?",
    style: "roleplay",
    requiredConceptSlugs: ["jag-har-ont-i", "jag-maar-inte-bra"],
    optionalConceptSlugs: ["huvudet", "magen", "feber", "du-borde", "vila", "har-du-syskon", "har-du-barn", "min-familj"],
    minimumEncountered: 2,
    minimumTurns: 3,
    maximumTurns: 6,
    starterHints: [
      { target: "Jag har ont i …", english: "My … hurts." },
      { target: "Jag mår inte bra.", english: "I don't feel well." },
    ],
    fallbackReplies: [
      { target: "Oj då. Hur länge har du haft ont?", english: "Oh dear. How long has it hurt?" },
      { target: "Du borde vila och dricka mycket vatten.", english: "You should rest and drink lots of water." },
      { target: "Har du familj här i Sverige?", english: "Do you have family here in Sweden?" },
    ],
  },
  {
    id: "i-affaeren",
    languageCode: "sv",
    characterId: "maja",
    title: "At the village shop",
    setting: "You step into Lanthandeln, the island's only shop, where Maja stands behind the counter.",
    learnerRole: "Buy a few things, ask about prices and pay.",
    characterRole: "Maja, the shopkeeper, helping you find things and taking your payment.",
    goal: "Ask for something, find out what it costs and pay for it.",
    openingLine: "Hej! Kan jag hjälpa dig med något?",
    openingEnglish: "Hi! Can I help you with anything?",
    style: "roleplay",
    requiredConceptSlugs: ["har-ni", "hur-mycket-kostar"],
    optionalConceptSlugs: ["jag-vill-koepa", "jag-tar", "det-var-allt", "jag-betalar-med-kort", "en-paase", "kan-jag-prova", "roed", "blaa"],
    minimumEncountered: 2,
    minimumTurns: 3,
    maximumTurns: 6,
    starterHints: [
      { target: "Har ni …?", english: "Do you have …?" },
      { target: "Hur mycket kostar …?", english: "How much is …?" },
    ],
    fallbackReplies: [
      { target: "Ja, det har vi! Något mer?", english: "Yes, we have that! Anything else?" },
      { target: "Det blir fyrtio kronor. Kort eller kontant?", english: "That'll be forty kronor. Card or cash?" },
      { target: "Tack så mycket! Vill du ha en påse?", english: "Thank you very much! Would you like a bag?" },
    ],
  },
  {
    id: "efter-skolan",
    languageCode: "sv",
    characterId: "leo",
    title: "After school",
    setting: "Leo is sitting on the library steps with his guitar, wondering what to do this afternoon.",
    learnerRole: "Talk about free time and make a plan to meet up.",
    characterRole: "Leo, a friendly fifteen-year-old who wants to do something fun.",
    goal: "Say what you like doing, agree on an activity and decide when and where to meet.",
    openingLine: "Tjena! Vad gör du på fritiden?",
    openingEnglish: "Hey! What do you do in your free time?",
    style: "open_question",
    requiredConceptSlugs: ["jag-gillar-att", "ska-vi-ses"],
    optionalConceptSlugs: ["vill-du", "vi-ses-vid", "ja-gaerna", "jag-kan-inte", "spela", "simma", "till-vaenster", "rakt-fram"],
    minimumEncountered: 2,
    minimumTurns: 3,
    maximumTurns: 6,
    starterHints: [
      { target: "Jag gillar att …", english: "I like …" },
      { target: "Ska vi ses …?", english: "Shall we meet …?" },
    ],
    fallbackReplies: [
      { target: "Kul! Vill du spela fotboll på stranden?", english: "Cool! Do you want to play football on the beach?" },
      { target: "När ses vi? Klockan fyra?", english: "When shall we meet? Four o'clock?" },
      { target: "Perfekt, vi ses vid biblioteket!", english: "Perfect, see you at the library!" },
    ],
  },
  {
    id: "vid-fyren",
    languageCode: "sv",
    characterId: "olle",
    title: "At the lighthouse",
    setting: "Olle, the old lighthouse keeper, sits on a bench below the lighthouse looking out to sea.",
    learnerRole: "Tell him about something you did, and share your opinion.",
    characterRole: "Olle, who loves stories about the past and asking what people think.",
    goal: "Say what you did recently, give an opinion and react to his.",
    openingLine: "Nämen hej! Vad gjorde du igår?",
    openingEnglish: "Well hello! What did you do yesterday?",
    style: "open_question",
    requiredConceptSlugs: ["jag-var", "jag-tycker-att"],
    optionalConceptSlugs: ["det-var", "jag-saag", "jag-traeffade", "jag-haaller-med", "vad-tycker-du", "baettre", "jag-kaenner-mig", "glad"],
    minimumEncountered: 2,
    minimumTurns: 3,
    maximumTurns: 6,
    starterHints: [
      { target: "Igår var jag …", english: "Yesterday I was …" },
      { target: "Jag tycker att …", english: "I think that …" },
    ],
    fallbackReplies: [
      { target: "Det låter trevligt! Och vad tycker du om Lilla Ö?", english: "That sounds nice! And what do you think of Lilla Ö?" },
      { target: "Jag håller med. Förr i tiden var det ännu lugnare här.", english: "I agree. In the old days it was even calmer here." },
      { target: "Kom tillbaka imorgon, så berättar jag mer!", english: "Come back tomorrow, and I'll tell you more!" },
    ],
  },
];
