import type { Line } from "@/lib/game/line";
import type { UiText } from "@/lib/game/ui-text";

// Every piece of interface copy is Swedish first; English only appears on hover.
export const ui: UiText = {
  title: { t: "Lilla Ö", en: "Little Island" },
  tagline: { t: "Lär dig svenska på en liten ö.", en: "Learn Swedish on a little island." },
  play: { t: "Spela", en: "Play" },
  continue: { t: "Fortsätt", en: "Continue" },
  signIn: { t: "Logga in och spela", en: "Sign in and play" },
  loading: { t: "Båten kommer…", en: "The boat is coming…" },
  level: { t: "Nivå", en: "Level" },
  words: { t: "ord", en: "words" },
  dictionary: { t: "Ordbok", en: "Dictionary" },
  soundOn: { t: "Ljud på", en: "Sound on" },
  soundOff: { t: "Ljud av", en: "Sound off" },
  musicOn: { t: "Musik på", en: "Music on" },
  musicOff: { t: "Musik av", en: "Music off" },
  menu: { t: "Meny", en: "Menu" },
  signOut: { t: "Logga ut", en: "Sign out" },
  close: { t: "Stäng", en: "Close" },
  back: { t: "Tillbaka", en: "Back" },
  home: { t: "Till alla öar", en: "To all islands" },
  walkHint: { t: "Gå med W A S D, eller klicka på marken.", en: "Walk with W A S D, or click on the ground." },
  hoverHint: { t: "Håll musen över ett ord för att se vad det betyder.", en: "Hold the mouse over a word to see what it means." },
  talkTo: (name: string): Line => ({ t: `Prata med ${name}`, en: `Talk to ${name}` }),
  lookAt: { t: "Titta", en: "Look" },
  goalTalk: (name: string, place: Line): Line => ({
    t: `Hitta ${name} vid ${place.t.toLocaleLowerCase("sv-SE")}`,
    en: `Find ${name} at ${place.en.toLocaleLowerCase("en")}`,
  }),
  goalLearnMore: (name: string): Line => ({ t: `Lär dig mer av ${name}`, en: `Learn more from ${name}` }),
  goalMeetFirst: { t: "Gå till Elin på bryggan", en: "Walk to Elin on the dock" },
  goalDone: { t: "Utforska ön och hitta nya ord", en: "Explore the island and find new words" },
  newWord: { t: "Nytt ord!", en: "New word!" },
  levelUp: { t: "Ny nivå!", en: "New level!" },
  treeGrows: { t: "Trädet på torget växer!", en: "The tree in the square is growing!" },
  newFriend: (name: string): Line => ({ t: `${name} vill träffa dig!`, en: `${name} wants to meet you!` }),
  welcomeBack: (name: string): Line => ({ t: `Välkommen tillbaka, ${name}!`, en: `Welcome back, ${name}!` }),
  explains: (name: string): Line => ({ t: `${name} förklarar…`, en: `${name} explains…` }),
  wordGrows: (stage: Line): Line => ({ t: `Ditt ord växer: ${stage.t}!`, en: `Your word grows: ${stage.en}!` }),
  startWith: (name: string): Line => ({ t: `Du börjar hos ${name}!`, en: `You start with ${name}!` }),
  callAndTalk: (name: string): Line => ({ t: `Ring ${name} och prata på svenska!`, en: `Call ${name} and talk in Swedish!` }),
  next: { t: "Nästa", en: "Next" },
  check: { t: "Kolla", en: "Check" },
  dontKnow: { t: "Jag vet inte", en: "I don't know" },
  hint: { t: "Tips", en: "Hint" },
  listen: { t: "Lyssna", en: "Listen" },
  listenAgain: { t: "Lyssna igen", en: "Listen again" },
  slowly: { t: "Långsamt", en: "Slowly" },
  sayIt: { t: "Säg det", en: "Say it" },
  listening: { t: "Jag lyssnar…", en: "I'm listening…" },
  writeTarget: { t: "Skriv på svenska…", en: "Write in Swedish…" },
  sayInTarget: { t: "Säg på svenska", en: "Say in Swedish" },
  whatDoesItMean: { t: "Vad betyder det?", en: "What does it mean?" },
  whatDidYouHear: { t: "Vad hörde du?", en: "What did you hear?" },
  buildSentence: { t: "Bygg meningen", en: "Build the sentence" },
  newPhrase: { t: "Ett nytt uttryck", en: "A new expression" },
  repeatAfterMe: { t: "Säg efter mig!", en: "Repeat after me!" },
  youSaid: { t: "Du sa", en: "You said" },
  heardYou: { t: "Jag hörde", en: "I heard" },
  bye: { t: "Hej då!", en: "Bye!" },
  again: { t: "En gång till!", en: "One more time!" },
  talkForReal: { t: "Prata på riktigt", en: "Talk for real (voice)" },
  chatTyping: { t: "Chatta", en: "Chat (typing)" },
  yourName: { t: "Skriv ditt namn…", en: "Write your name…" },
  myNameIs: { t: "Jag heter…", en: "My name is…" },
  saving: { t: "Sparar…", en: "Saving…" },
  xpGained: { t: "poäng", en: "points" },
  correct: { t: "rätt", en: "correct" },
  phrases: { t: "Fraser", en: "Phrases" },
  grammar: { t: "Grammatik", en: "Grammar" },
  littleGrammar: { t: "Lilla grammatik", en: "Little grammar" },
  newGrammar: { t: "Ny grammatik", en: "New grammar tip" },
  things: { t: "Saker på ön", en: "Things on the island" },
  notFound: { t: "Inte hittad än", en: "Not found yet" },
  notMet: { t: "Inte lärt än", en: "Not learned yet" },
  connecting: { t: "Ringer upp…", en: "Calling…" },
  liveNow: { t: "Prata bara! Jag lyssnar.", en: "Just talk! I'm listening." },
  mute: { t: "Tyst", en: "Mute" },
  unmute: { t: "Mikrofon på", en: "Microphone on" },
  endCall: { t: "Avsluta", en: "End" },
  liveOver: { t: "Samtalet är slut.", en: "The conversation is over." },
  reflect: { t: "Vad lärde jag mig?", en: "What did I learn?" },
  typeReply: { t: "Svara på svenska…", en: "Answer in Swedish…" },
  send: { t: "Skicka", en: "Send" },
  needsAccount: { t: "Logga in för att prata på riktigt.", en: "Sign in to talk for real." },
  liveUnavailable: { t: "Rösten fungerar inte just nu. Vi kan chatta istället!", en: "Voice isn't working right now. We can chat instead!" },
  notReadyToTalk: { t: "Lär dig lite mer först, sen kan vi prata!", en: "Learn a bit more first, then we can talk!" },
  error: { t: "Hoppsan! Något gick fel.", en: "Oops! Something went wrong." },
  tryAgain: { t: "Försök igen", en: "Try again" },
  captions: { t: "Undertexter", en: "Subtitles" },
  mic: { t: "Mikrofon", en: "Microphone" },
  youLabel: { t: "Du", en: "You" },
  stageLabel: { t: "Växer", en: "Growing" },
  letters: { t: "Svenska bokstäver", en: "Swedish letters" },
  controls: { t: "Kontroller", en: "Controls" },
  controlsMove: { t: "Gå: W A S D / pilar / klicka", en: "Walk: W A S D / arrows / click" },
  controlsTalk: { t: "Prata: E / mellanslag", en: "Talk: E / space" },
  controlsCamera: { t: "Kamera: dra med musen, scrolla för zoom", en: "Camera: drag with the mouse, scroll to zoom" },
  controlsRun: { t: "Spring: håll Shift", en: "Run: hold Shift" },
  spelling: { t: "Titta på stavningen!", en: "Look at the spelling!" },
  article: { t: "Glöm inte en eller ett!", en: "Don't forget en or ett!" },
  yourStyle: { t: "Din stil", en: "Your style" },
  style: { t: "Stil", en: "Style" },
  englishAuto: { t: "Engelska: auto", en: "English subtitles: automatic" },
  englishOn: { t: "Engelska: på", en: "English subtitles: on" },
  englishOff: { t: "Engelska: av", en: "English subtitles: off" },
  skip: { t: "Hoppa över", en: "Skip" },
  tryIt: { t: "Testa!", en: "Try it!" },
  nowYouCanSay: { t: "Nu kan du säga…", en: "Now you can say…" },
  letsGo: { t: "Då kör vi!", en: "Let's go!" },
  presents: { t: "Sapling presenterar", en: "Sapling presents" },
  welcomeTitle: { t: "Välkommen till Lilla Ö", en: "Welcome to Little Island" },
  learnedBefore: { t: "Har du lärt dig svenska förut?", en: "Have you learned Swedish before?" },
  quickCheck: { t: "Snabbkoll", en: "Quick check" },
  done: { t: "Klart!", en: "Done!" },
  startFromTop: { t: "Vi börjar från början!", en: "We'll start at the beginning!" },
  replyIfYouLike: { t: "Svara om du vill", en: "Reply if you like" },
  askForBill: { t: "Be om notan!", en: "Ask for the bill!" },
  fillTray: { t: "Fyll brickan!", en: "Fill the tray!" },
  ready: { t: "Klar!", en: "Done!" },
  option: { t: "Alternativ", en: "Option" },
  yourTray: { t: "Din bricka", en: "Your tray" },
  flowers: { t: "blommor", en: "flowers" },
  units: { t: "Kapitel", en: "Chapters" },
  locked: { t: "Låst", en: "Locked" },
};
