import type { Line } from "@/lib/game/line";
import type { Villager } from "@/lib/game/villagers";

// The people of Lilla Ö. Each teaches a few units of the Swedish course.

export const villagers: Villager[] = [
  {
    id: "elin",
    name: "Elin",
    role: { t: "hamnvakt", en: "harbour keeper" },
    place: { t: "Bryggan", en: "The dock" },
    scenarioId: "meet-elin",
    round: "scene",
    stage: "guestbook",
    position: [3.2, 19.5],
    facing: Math.PI * 0.9,
    look: { skin: "#f3c9a8", hair: "#f2d27a", hairStyle: "braid", shirt: "#ffcf3f", pants: "#3c5a8a", accent: "#2f6fb5" },
    voicePitch: 1.25,
    voice: "Leda",
    context: "the ferry dock of Lilla Ö, a tiny Swedish island (Elin keeps the harbour)",
    greetings: [
      { t: "Hej igen! Vad kul att se dig!", en: "Hi again! How nice to see you!" },
      { t: "Hej! Är du redo för lite svenska?", en: "Hi! Are you ready for some Swedish?" },
      { t: "Tjena! Vilket fint väder idag!", en: "Hey! What nice weather today!" },
    ],
    chatter: [
      { t: "Båten kommer klockan tre.", en: "The boat comes at three o'clock." },
      { t: "Titta, en fågel!", en: "Look, a bird!" },
      { t: "Hej hej!", en: "Hi hi!" },
    ],
    locked: { t: "Hej!", en: "Hi!" },
    teach: { t: "Lär mig något!", en: "Teach me something!" },
    talk: { t: "Kan vi prata?", en: "Can we talk?" },
    goodbye: [
      { t: "Vi ses!", en: "See you!" },
      { t: "Ha det bra!", en: "Take care!" },
    ],
  },
  {
    id: "bosse",
    name: "Bosse",
    role: { t: "kafévärd", en: "café owner" },
    place: { t: "Café Kanel", en: "Café Cinnamon" },
    scenarioId: "fika-order",
    round: "cafe",
    stage: "guestbook",
    position: [-10.2, 4.8],
    facing: Math.PI * 0.35,
    look: { skin: "#e8b48f", hair: "#6b4a2f", hairStyle: "short", shirt: "#f4efe6", pants: "#4a3a2e", accent: "#c0392b", hat: "chef", beard: true, apron: "#c0392b", scale: 1.08 },
    voicePitch: 0.8,
    voice: "Achird",
    context: "Café Kanel on Lilla Ö, run by Bosse who bakes cinnamon buns",
    greetings: [
      { t: "Välkommen till Café Kanel!", en: "Welcome to Café Cinnamon!" },
      { t: "Mmm, känner du doften? Nybakat!", en: "Mmm, can you smell it? Freshly baked!" },
      { t: "Hej hej! Dags för fika?", en: "Hi hi! Time for fika?" },
    ],
    chatter: [
      { t: "Kanelbullar! Nybakade kanelbullar!", en: "Cinnamon buns! Freshly baked cinnamon buns!" },
      { t: "Kaffe är livet.", en: "Coffee is life." },
      { t: "Fika är viktigt.", en: "Fika is important." },
    ],
    locked: { t: "Förlåt, vi har stängt. Prata med Elin vid bryggan först!", en: "Sorry, we're closed. Talk to Elin by the dock first!" },
    teach: { t: "Vad finns på menyn?", en: "What's on the menu?" },
    talk: { t: "Jag vill beställa!", en: "I want to order!" },
    goodbye: [
      { t: "Välkommen åter!", en: "Welcome back (come again)!" },
      { t: "Hej då, ha en fin dag!", en: "Bye, have a nice day!" },
    ],
  },
  {
    id: "nils",
    name: "Nils",
    role: { t: "fiskare", en: "fisherman" },
    place: { t: "Sjöboden", en: "The boathouse" },
    scenarioId: "i-hamnen",
    round: "scene",
    stage: "stamps",
    position: [11.5, 22.8],
    facing: -Math.PI * 0.55,
    look: { skin: "#e8b89a", hair: "#9a9a9a", hairStyle: "beanie", shirt: "#f2c230", pants: "#2c3e50", accent: "#c0392b", hat: "beanie", beard: true, scale: 1.04 },
    voicePitch: 0.8,
    voice: "Algenib",
    context: "Nils's red boathouse on the shore of Lilla Ö (Nils is a fisherman who counts everything: fish, boats, kronor, and knows the sea and its weather)",
    greetings: [
      { t: "Hej! Fisken nappar idag!", en: "Hi! The fish are biting today!" },
      { t: "Tjena! Hur många fiskar tror du jag fick?", en: "Hey! How many fish do you think I got?" },
      { t: "God morgon! Jag har varit ute sedan klockan fem.", en: "Good morning! I've been out since five o'clock." },
    ],
    chatter: [
      { t: "Ett, två, tre … tolv fiskar!", en: "One, two, three … twelve fish!" },
      { t: "Havet är lugnt idag.", en: "The sea is calm today." },
      { t: "Måsarna vill ha min fisk.", en: "The seagulls want my fish." },
    ],
    locked: { t: "Jag fiskar just nu. Ta en fika hos Bosse först!", en: "I'm fishing right now. Have a coffee at Bosse's first!" },
    teach: { t: "Lär mig siffrorna!", en: "Teach me the numbers!" },
    talk: { t: "Hur är vädret på havet?", en: "What's the weather like at sea?" },
    goodbye: [
      { t: "Hej då! Akta dig för måsarna!", en: "Bye! Watch out for the seagulls!" },
      { t: "Vi ses i hamnen!", en: "See you in the harbour!" },
    ],
  },
  {
    id: "karin",
    name: "Karin",
    role: { t: "sjuksköterska", en: "nurse" },
    place: { t: "Vårdcentralen", en: "The health centre" },
    scenarioId: "paa-vaardcentralen",
    round: "scene",
    stage: "stamps",
    position: [-16.2, 10.4],
    facing: Math.PI * 0.41,
    look: { skin: "#f1c7a8", hair: "#b5562b", hairStyle: "bob", shirt: "#8ec5e8", pants: "#f4f4f4", accent: "#2e86c1" },
    voicePitch: 1.1,
    voice: "Vindemiatrix",
    context: "the little health centre (vårdcentral) on Lilla Ö, where Karin is the island's nurse; she is Leo's mum and loves talking about family and work",
    greetings: [
      { t: "Hej! Hur mår du idag?", en: "Hi! How are you today?" },
      { t: "Välkommen in! Ta det lugnt.", en: "Come in! Take it easy." },
      { t: "Hej hej! Leo är i skolan idag.", en: "Hi hi! Leo is at school today." },
    ],
    chatter: [
      { t: "Glöm inte att dricka vatten!", en: "Don't forget to drink water!" },
      { t: "Leo är min son, vet du.", en: "Leo is my son, you know." },
      { t: "Tvätta händerna!", en: "Wash your hands!" },
    ],
    locked: { t: "Hej! Jag har mycket att göra. Har du träffat Nils vid sjöboden?", en: "Hi! I've got a lot to do. Have you met Nils at the boathouse?" },
    teach: { t: "Berätta om din familj!", en: "Tell me about your family!" },
    talk: { t: "Jag mår inte så bra …", en: "I don't feel so good …" },
    goodbye: [
      { t: "Ta hand om dig!", en: "Take care of yourself!" },
      { t: "Hej då, ha det så bra!", en: "Bye, take care!" },
    ],
  },
  {
    id: "stina",
    name: "Stina",
    role: { t: "stationsvakt", en: "station master" },
    place: { t: "Stationen", en: "The station" },
    scenarioId: "centralstation-change",
    round: "scene",
    stage: "journey",
    position: [14.2, -1.2],
    facing: -Math.PI * 0.4,
    look: { skin: "#8d5a3b", hair: "#1f1a17", hairStyle: "bob", shirt: "#1f4e79", pants: "#1b2a3a", accent: "#f2c230", hat: "conductor" },
    voicePitch: 1.1,
    voice: "Erinome",
    context: "the island railway station and the train to the mainland (Stina is the station master)",
    greetings: [
      { t: "God dag! Tåget går i tid idag.", en: "Good day! The train is on time today." },
      { t: "Hej! Vart ska du resa?", en: "Hi! Where are you travelling?" },
      { t: "Välkommen till stationen!", en: "Welcome to the station!" },
    ],
    chatter: [
      { t: "Tåget går snart!", en: "The train leaves soon!" },
      { t: "Har du en biljett?", en: "Do you have a ticket?" },
      { t: "Spår två, spår två!", en: "Platform two, platform two!" },
    ],
    locked: { t: "Tåget går inte än. Har du varit på kaféet?", en: "The train isn't running yet. Have you been to the café?" },
    teach: { t: "Hjälp mig att resa!", en: "Help me travel!" },
    talk: { t: "Jag behöver hjälp!", en: "I need help!" },
    goodbye: [
      { t: "Trevlig resa!", en: "Have a nice trip!" },
      { t: "Vi ses på perrongen!", en: "See you on the platform!" },
    ],
  },
  {
    id: "maja",
    name: "Maja",
    role: { t: "handlare", en: "shopkeeper" },
    place: { t: "Lanthandeln", en: "The village shop" },
    scenarioId: "i-affaeren",
    round: "scene",
    stage: "stamps",
    position: [-7.6, 12.6],
    facing: Math.PI * 0.47,
    look: { skin: "#f0c09a", hair: "#7a4a2a", hairStyle: "braid", shirt: "#f7d9a8", pants: "#4a5a3a", accent: "#3f8f5a", apron: "#3f8f5a" },
    voicePitch: 1.2,
    voice: "Laomedeia",
    context: "Lanthandeln, the only shop on Lilla Ö (food, clothes, stamps and postcards), run by cheerful Maja who also knows everyone's home",
    greetings: [
      { t: "Hej och välkommen till Lanthandeln!", en: "Hi and welcome to the village shop!" },
      { t: "Hej! Vi har nybakat bröd idag.", en: "Hi! We have freshly baked bread today." },
      { t: "Tjenare! Letar du efter något?", en: "Hi there! Looking for something?" },
    ],
    chatter: [
      { t: "Extrapris på ost idag!", en: "Special offer on cheese today!" },
      { t: "Vykort! Frimärken! Mjölk!", en: "Postcards! Stamps! Milk!" },
      { t: "Den röda jackan är ny.", en: "The red jacket is new." },
    ],
    locked: { t: "Förlåt, vi har stängt! Fråga Stina vad klockan är.", en: "Sorry, we're closed! Ask Stina what time it is." },
    teach: { t: "Vad har ni i affären?", en: "What do you have in the shop?" },
    talk: { t: "Jag vill handla!", en: "I want to do some shopping!" },
    goodbye: [
      { t: "Tack för besöket!", en: "Thanks for coming by!" },
      { t: "Hej då, välkommen åter!", en: "Bye, come again!" },
    ],
  },
  {
    id: "leo",
    name: "Leo",
    role: { t: "elev", en: "pupil" },
    place: { t: "Biblioteket", en: "The library" },
    scenarioId: "efter-skolan",
    round: "scene",
    stage: "stamps",
    position: [-10.8, -6.2],
    facing: Math.PI * 0.5,
    look: { skin: "#f3d0b0", hair: "#e8c96a", hairStyle: "short", shirt: "#e76f51", pants: "#3c5a8a", accent: "#264653", hat: "cap", scale: 0.88 },
    voicePitch: 1.3,
    voice: "Fenrir",
    context: "the little library on Lilla Ö, where fifteen-year-old Leo reads after school, plays the guitar and knows every path on the island (his mum Karin is the nurse)",
    greetings: [
      { t: "Tjena! Vill du se en rolig bok?", en: "Hey! Want to see a funny book?" },
      { t: "Hej! Jag känner till varenda stig på ön.", en: "Hi! I know every single path on the island." },
      { t: "Tja! Ska vi hitta på något?", en: "Hey! Shall we do something?" },
    ],
    chatter: [
      { t: "Jag spelar gitarr varje dag.", en: "I play the guitar every day." },
      { t: "Mamma jobbar på vårdcentralen.", en: "Mum works at the health centre." },
      { t: "Den här boken är jättebra!", en: "This book is really good!" },
    ],
    locked: { t: "Sch, jag läser! Kom tillbaka senare.", en: "Shh, I'm reading! Come back later." },
    teach: { t: "Visa mig ön!", en: "Show me the island!" },
    talk: { t: "Vad gör du på fritiden?", en: "What do you do in your free time?" },
    goodbye: [
      { t: "Hej då! Vi hörs!", en: "Bye! Talk soon!" },
      { t: "Ses imorgon!", en: "See you tomorrow!" },
    ],
  },
  {
    id: "astrid",
    name: "Astrid",
    role: { t: "trädgårdsmästare", en: "gardener" },
    place: { t: "Trädgården på berget", en: "The garden on the hill" },
    scenarioId: "make-weekend-plans",
    round: "scene",
    stage: "garden",
    position: [-2.2, -14.5],
    facing: Math.PI * 0.15,
    look: { skin: "#f0c4a4", hair: "#e6e6e6", hairStyle: "bun", shirt: "#7aa65a", pants: "#6b5a4a", accent: "#e76f8a", hat: "sunhat", scale: 0.95 },
    voicePitch: 0.95,
    voice: "Sulafat",
    context: "Astrid's vegetable and flower garden on the hill of Lilla Ö",
    greetings: [
      { t: "Nämen hej, lilla vän!", en: "Well hello, little friend!" },
      { t: "Blommorna växer så fint i år.", en: "The flowers are growing so nicely this year." },
      { t: "Sätt dig, sätt dig!", en: "Sit down, sit down!" },
    ],
    chatter: [
      { t: "Vilka fina blommor!", en: "What lovely flowers!" },
      { t: "Solen är varm idag.", en: "The sun is warm today." },
      { t: "Tomaterna är röda nu.", en: "The tomatoes are red now." },
    ],
    locked: { t: "Nämen hej! Kom tillbaka när du har handlat hos Maja.", en: "Well hello! Come back when you've been shopping at Maja's." },
    teach: { t: "Berätta om din dag!", en: "Tell me about your day!" },
    talk: { t: "Ska vi göra något?", en: "Shall we do something?" },
    goodbye: [
      { t: "Hej då, kära du!", en: "Bye, dear!" },
      { t: "Kom snart tillbaka!", en: "Come back soon!" },
    ],
  },
  {
    id: "olle",
    name: "Olle",
    role: { t: "fyrvaktare", en: "lighthouse keeper" },
    place: { t: "Fyren", en: "The lighthouse" },
    scenarioId: "vid-fyren",
    round: "scene",
    stage: "stamps",
    position: [2.2, -28.6],
    facing: Math.PI * 0.13,
    look: { skin: "#e9b996", hair: "#eeeeee", hairStyle: "short", shirt: "#1f3a5f", pants: "#3a3a3a", accent: "#f4f4f4", hat: "cap", beard: true },
    voicePitch: 0.7,
    voice: "Sadaltager",
    context: "the old lighthouse on the northern tip of Lilla Ö, where Olle, the retired lighthouse keeper, tells stories about the past and has an opinion about everything",
    greetings: [
      { t: "Nämen, en besökare! Välkommen till fyren!", en: "Well, a visitor! Welcome to the lighthouse!" },
      { t: "Hej hej! Vill du höra en historia?", en: "Hi hi! Do you want to hear a story?" },
      { t: "Hej! Utsikten är fin idag, va?", en: "Hi! The view is lovely today, isn't it?" },
    ],
    chatter: [
      { t: "Förr i tiden var allt annorlunda.", en: "In the old days everything was different." },
      { t: "Jag har bott här i fyrtio år.", en: "I've lived here for forty years." },
      { t: "Fyren lyser varje natt.", en: "The lighthouse shines every night." },
    ],
    locked: { t: "Fyren är stängd idag. Kom tillbaka en annan dag!", en: "The lighthouse is closed today. Come back another day!" },
    teach: { t: "Berätta en historia!", en: "Tell me a story!" },
    talk: { t: "Vad tycker du om ön?", en: "What do you think of the island?" },
    goodbye: [
      { t: "Hej då, och ta hand om dig!", en: "Bye, and take care of yourself!" },
      { t: "Kom och hälsa på igen!", en: "Come and visit again!" },
    ],
  },
];

// The first meeting doubles as the tutorial: hover-to-translate is taught in Swedish.
export const elinIntro: Line[] = [
  { t: "Hej! Välkommen till Lilla Ö!", en: "Hi! Welcome to Lilla Ö (Little Island)!" },
  { t: "Här pratar alla svenska.", en: "Everyone speaks Swedish here." },
  { t: "Förstår du inte? Håll musen över ett ord.", en: "Don't understand? Hold the mouse over a word." },
  { t: "Jag heter Elin. Vad heter du?", en: "My name is Elin. What's your name?" },
];

export const elinAfterName = (name: string): Line[] => [
  { t: `Trevligt att träffas, ${name}!`, en: `Nice to meet you, ${name}!` },
  { t: "Ser du det lilla trädet på torget? Det är ledset.", en: "Do you see the little tree in the square? It is sad." },
  { t: "Trädet växer när du lär dig svenska.", en: "The tree grows when you learn Swedish." },
  { t: "Kom, jag lär dig dina första ord!", en: "Come, I'll teach you your first words!" },
];

export const praise: Line[] = [
  { t: "Precis!", en: "Exactly!" },
  { t: "Snyggt!", en: "Nice!" },
  { t: "Perfekt!", en: "Perfect!" },
  { t: "Bra jobbat!", en: "Good job!" },
  { t: "Ja, så säger man!", en: "Yes, that's how you say it!" },
  { t: "Helt rätt!", en: "Completely right!" },
];

export const nudges: Line[] = [
  { t: "Nästan! Så här säger man:", en: "Almost! This is how you say it:" },
  { t: "Inte riktigt. Lyssna:", en: "Not quite. Listen:" },
  { t: "Bra försök! Man säger:", en: "Good try! You say:" },
];

export const roundDone: Line[] = [
  { t: "Bra jobbat idag!", en: "Good work today!" },
  { t: "Du lär dig så snabbt!", en: "You learn so fast!" },
  { t: "Vad duktig du är!", en: "How clever you are!" },
];

