// Word-level English glosses for everything Cát Bà says in Vietnamese, beyond
// the single words the course itself teaches (those come from ./course).
// Words written as several syllables ("cà phê") are glossed whole and hover as
// one word; every syllable also has its own gloss for when it stands alone.

export const entries = `
xin chào=hello|chào=hello / bye|chào mừng=welcome|cảm ơn=thank you|cám ơn=thank you (Southern)|xin lỗi=sorry / excuse me|tạm biệt=goodbye|hẹn gặp lại=see you again|không có gì=you're welcome|không sao=it's okay|khỏe=well / healthy|tốt quá=great
tôi=I / me|bạn=you / friend|mình=I / we (friendly)|anh=you (young man) / older brother|chị=you (young woman) / older sister|em=you (younger) / younger sibling|ông=grandpa / you (old man)|bà=grandma / you (old woman)|bác=uncle / you (older man or woman)|cháu=grandchild / I (to elders)|các=(plural) all the|chúng nó=they (kids)|người ta=people / they|ai=who|mọi người=everyone
là=am / is / are|có=have / there is / yes|không=no / not / (question)|được=can / okay / get|được không=can you?|muốn=want|thích=like|biết=know|hiểu=understand|nói=speak / say|nói chuyện=talk|học=learn / study|dạy=teach|sống=live|ở=at / in / live|đi=go|đến=come / arrive / to|về=return / about|vào=come in / enter|ra=out|ngồi=sit|lên=go up / board|lấy=take|mua=buy|bán=sell|ăn=eat|uống=drink|gọi=call / order|gọi món=order (food)|hỏi=ask|kể=tell|giữ=hold|thấy=see|nhìn=look|nghe=listen / hear|xem=look / watch|tìm=find|viết=write|bấm=click / press|kéo=drag|cuộn=scroll|chơi=play|thử=try|gửi=send|lưu=save|đóng=close|bật=turn on|tắt=turn off|khóa=lock|mở=open|mở cửa=open|đóng cửa=closed|quay lại=come back / back|trở lại=come back|bắt đầu=start|bắt được=caught|lớn lên=grow up|lớn=big / grow|trả lời=answer|nấu=cook|làm=make / do|làm quen=get to know|vá=mend|sửa=fix|đi thuyền=take a boat|đi biển=go to sea|đi câu cá=go fishing|câu cá=fish (with a rod)|khám phá=explore|ghép=put together|xếp=arrange / fill|kiểm tra=check|bỏ qua=skip|tiếp=next|tiếp tục=continue|chạy=run|xảy ra=happen|hoạt động=work (function)|cúp máy=hang up|nhắn tin=chat (text)|đăng nhập=sign in|đăng xuất=sign out|tặng=give (a gift)|thanh toán=pay
gì=what|đâu=where|nào=which|bao nhiêu=how much / how many|mấy=how many|thế nào=how|khi nào=when|sao=why / how|như thế=like that|thế này=like this|thế à=really?|thế thì=then|thế=so / then|thôi=only / just / enough|nhé=okay? (friendly)|nha=okay? (friendly)|đi=go / (let's)|đấy=(emphasis)|đây=here / this|kìa=over there|này=this / hey|ạ=(polite)|à=(question, surprise)|ồ=oh|ôi=oh|ơi=hey (calling)|rồi=already / done|chưa=yet / not yet|nữa=more / again|lại=again|cũng=also|rất=very|lắm=very|quá=so / too|thật=really|một chút=a little|một=one / a|những=(plural)|mỗi=every|từ=from / word|với=with|và=and|còn=and / still|hoặc=or|nhưng=but|mà=but|nếu=if|khi=when|để=to / in order to|của=of / 's|cho=give / for|trên=on|trong=in|sau=after / later|trước=before / first|lúc=at (time)|ngay=right away|có ngay=coming right up|ngày xưa=in the old days|bây giờ=now|hôm nay=today|hôm qua=yesterday|ngày mai=tomorrow|sáng sớm=early morning|lát nữa=in a bit|lần sau=next time|lần nữa=once more|lần=time (occasion)|sắp=soon / about to|đang=(is doing)|đã=(did)|như=like|cái mới=something new|mới=new|đầu tiên=first|thật đấy=really
người=person / people|nước=water / country|nước nào=which country|người nước nào=from which country|Mỹ=America|người Mỹ=American|Anh=England / English|người Anh=English (person)|tiếng Anh=English (language)|tiếng Việt=Vietnamese (language)|tiếng=language / sound|Việt Nam=Vietnam|Hà Nội=Hanoi|Cát Bà=Cát Bà (the island)|Hạ Long=Hạ Long|sinh viên=student|giáo viên=teacher|ngư dân=fisherman|chèo đò=row a boat|đò=ferry boat|chủ quán=shop owner|quán=shop / eatery|quán phở=pho shop|người bán hàng=seller|bán hàng=sell goods|hàng=goods|chủ=owner
Lan=Lan (name)|Hùng=Hùng (name)|Mai=Mai (name)|Sơn=Sơn (name)|Minh=Minh (name)|Hoa=Hoa (name)|Linh=Linh (name)|Tuấn=Tuấn (name)|Hương=Hương (name)|Nam=Nam (name)|Trang=Trang (name)|Dũng=Dũng (name)|Thảo=Thảo (name)|Hải=Hải (name)|Ngọc=Ngọc (name)|Phương=Phương (name)|Caleb=Caleb (name)|Sapling=Sapling (name)
đảo=island|biển=sea / sign|vịnh=bay|làng=village|làng chài=fishing village|đầu làng=village square|bến=landing / pier|bến thuyền=boat landing|thuyền=boat|thuyền thúng=basket boat|con thuyền=boat|chợ=market|chùa=pagoda|ngôi chùa=pagoda|ngôi=(classifier for buildings)|nhà=house / home|về nhà=go home|vườn quốc gia=national park|vườn=garden|quốc gia=national|rừng=forest|núi=mountain|đá=stone / ice|hòn đá=stone|hòn=(classifier for stones)|cây=tree / plant|cây đa=banyan tree|đa=banyan|cây dừa=coconut palm|dừa=coconut|tre=bamboo|cây tre=bamboo|hoa=flower|bông hoa=flower|bông=(classifier for flowers)|chim=bird|con chim=bird|cá=fish|con cá=fish|khỉ=monkey|voọc=langur|con voọc=langur|mèo=cat|con mèo=cat|chó=dog|con chó=dog|gà=chicken|trứng=egg|quả trứng=egg|lưới=net|cái lưới=fishing net|nón lá=conical hat|nón=hat|lá=leaf|đèn lồng=lantern|đèn=lamp|lồng=cage|ghế=chair / stool|cái ghế=stool|ghế nhựa=plastic stool|thùng=barrel / box|cái thùng=barrel|xe đạp=bicycle|xe=vehicle|túi=bag|bản đồ=map|sổ=notebook|sổ khách=guest book|khách=guest|tem=stamp(s)|khay=tray|đồ vật=things|đồ=things|vật=object|trời=sky / weather|nắng=sunny|nóng=hot|mát=cool|lặng=calm|đẹp=beautiful|to=big|nhỏ=small|buồn=sad|vui=happy / fun|trẻ=young|mới=new|nhiều=many / a lot|ít=few|đúng=right|sai=wrong|gần=near / almost|hoàn toàn=completely|giỏi=good (at)|hay=good / interesting|tuyệt vời=wonderful|nhanh=fast|chậm=slow|cẩn thận=careful|bận=busy|ngọt=sweet|tươi=fresh|cay=spicy|no=full|rẻ=cheap|đắt=expensive
phở=pho|phở bò=beef pho|phở gà=chicken pho|bò=beef / cow|bát phở=bowl of pho|bát=bowl|cà phê=coffee|cà phê sữa đá=iced milk coffee|sữa=milk|trà=tea|trà đá=iced tea|cốc=glass / cup|chai=bottle|bánh mì=bread / banh mi|bánh=cake / bread|mì=noodles / wheat|cơm=rice / meal|ăn cơm=eat (a meal)|chanh=lime|ớt=chilli|nước dùng=broth|món=dish|ngon=delicious|ngon quá=delicious|thanh long=dragon fruit|xoài=mango|chuối=banana|quả=fruit / (classifier)|tiền=money|tính tiền=the bill|tính=calculate|bớt=reduce|đồng=dong (money)|nghìn=thousand|trăm=hundred|mươi=ten (in twenty, thirty…)|mười=ten|một trăm=one hundred|thôi được=oh, all right
gia đình=family|bố=dad|mẹ=mum|con=child / (classifier)|con một=only child|vợ=wife|chồng=husband|anh trai=older brother|chị gái=older sister|em trai=younger brother|em gái=younger sister|anh chị em=siblings|trai=male|gái=female|tuổi=years old / age|ai=who
ma=ghost|má=cheek|mả=grave|mã=horse|mạ=rice seedling|ngang=level|huyền=falling (tone)|sắc=rising (tone)|nặng=heavy (tone)|ngã=broken (tone)|thanh=tone|sáu=six|dấu=mark / accent
cấp=level|lên cấp=level up|từ=word|từ mới=new word|từ điển=dictionary|menu=menu|âm thanh=sound|micro=microphone|camera=camera|phụ đề=subtitles|chữ cái=letters|chữ=letter / writing|cái=(classifier) / thing|điều khiển=controls|phím cách=space bar|phím=key|mũi tên=arrows|chuột=mouse|mặt đất=the ground|đất=ground|kéo chuột=drag the mouse|phóng to=zoom in|Shift=Shift (key)|W=W|A=A|S=S|D=D|E=E|phong cách=style|tự động=automatic|gợi ý=hint|ngữ pháp=grammar|câu=sentence / phrase|hội thoại=dialogue|thứ tự=order|đúng thứ tự=the right order|giờ khởi hành=departure time|khởi hành=depart|chuyến đi=the journey|giọng nói=voice|cuộc nói chuyện=conversation|cuộc=(classifier for events)|có lỗi=something's wrong|lỗi=error|điểm=points|lựa chọn=option|ghi chú=notes|bài học=lesson|bài=lesson|đang khóa=locked|nghĩa=meaning|cách viết=spelling|cách=way|loại từ=classifier|đảo=island|giới thiệu=introduce / presents|Sapling giới thiệu=Sapling presents|hoàn toàn mới=brand new|khá=quite|khá nhiều=quite a lot|xong=done|nhanh=fast|đầu=beginning / head|từ đầu=from the start|khám=examine
chào nhé=bye now|được=okay|có ngay=coming right up|như thế=like that|đi nào=come on|đi thôi=let's go|cố lên=keep going|nghe này=listen|thế này=like this|chưa đúng=not right yet|gần đúng=almost right|nói theo=repeat after|nói lại=say again|nói chậm=speak slowly|ăn thử=try (food)|mua gì=buy what|lần sau=next time|ra đây=come out here|quán chưa mở=not open yet
tên=name|tên là=is called|gặp=meet|bằng=in / by|giờ=hour / o'clock|ba giờ=three o'clock|non=young|cây non=sapling|thêm=more|phải=must|ngày=day|đó=that|nó=it|tiên=first|hạt=seed|mầm=sprout|nở=bloom|nở hoa=in bloom|chỗ=place|cứ=just (go ahead)|đừng=don't|quên=forget|đừng quên=don't forget|thể=(in có thể)|có thể=can|chuyện=story / matter|theo=follow
`;
