import type { PracticeCharacter, PracticeScenario } from "@/types/practice";

// Live and typed conversations with the people of Cát Bà. Everyone speaks
// Northern (Hanoi) Vietnamese.

export const characters: PracticeCharacter[] = [
  { id: "lan", name: "Lan", description: "Cheerful young boat rower on Cát Bà who greets every visitor at the boat landing, calls them 'bạn' and loves showing off the bay." },
  { id: "hung", name: "Bác Hùng", description: "Warm, proud owner of a little pho shop on Cát Bà who has cooked beef pho for thirty years, calls you 'cháu' and insists you eat more." },
  { id: "mai", name: "Chị Mai", description: "Quick-witted market seller on Cát Bà with mangoes, bananas and dragon fruit, who calls you 'em' and haggles for fun." },
  { id: "son", name: "Ông Sơn", description: "Gentle old fisherman on Cát Bà in a pith helmet who mends his nets, calls you 'cháu' and loves talking about his family and grandchildren." },
];

export const scenarios: PracticeScenario[] = [
  {
    id: "gap-lan",
    languageCode: "vi",
    characterId: "lan",
    title: "Meet Lan",
    setting: "You have just stepped off the boat onto the landing of a fishing village on Cát Bà island, with limestone pillars rising out of the bay behind you.",
    learnerRole: "Introduce yourself and get to know Lan.",
    characterRole: "The friendly boat rower meeting you for the first time.",
    goal: "Exchange names, say where you're from and finish a short, natural introduction.",
    openingLine: "Xin chào! Tôi tên là Lan. Bạn tên là gì?",
    openingEnglish: "Hello! My name is Lan. What's your name?",
    style: "roleplay",
    requiredConceptSlugs: ["xin-chao", "toi-ten-la"],
    optionalConceptSlugs: ["rat-vui", "toi-la-nguoi", "toi-song-o", "ban-khoe-khong", "con-ban", "tam-biet"],
    minimumEncountered: 0,
    minimumTurns: 3,
    maximumTurns: 5,
    starterHints: [
      { target: "Xin chào, tôi tên là …", english: "Hello, my name is …" },
      { target: "Tôi là người …", english: "I'm … (nationality)" },
    ],
    fallbackReplies: [
      { target: "Rất vui được gặp bạn! Bạn là người nước nào?", english: "Nice to meet you! Where are you from?" },
      { target: "Tốt quá! Bạn thích Cát Bà không?", english: "Great! Do you like Cát Bà?" },
      { target: "Cảm ơn bạn. Hẹn gặp lại!", english: "Thank you. See you again!" },
    ],
  },
  {
    id: "o-quan-pho",
    languageCode: "vi",
    characterId: "hung",
    title: "A bowl of pho at Bác Hùng's",
    setting: "You sit down on a little plastic stool outside Bác Hùng's pho shop.",
    learnerRole: "Order something to eat and drink, then pay.",
    characterRole: "Bác Hùng, the owner, taking your order and chatting while he cooks.",
    goal: "Order a pho and a drink, answer one follow-up question and ask for the bill.",
    openingLine: "Chào cháu! Cháu ăn gì?",
    openingEnglish: "Hello! What will you have?",
    style: "roleplay",
    requiredConceptSlugs: ["cho-toi", "pho", "cam-on"],
    optionalConceptSlugs: ["pho-bo", "pho-ga", "tra-da", "ca-phe-sua-da", "khong-cay", "ngon-qua", "tinh-tien"],
    minimumEncountered: 2,
    minimumTurns: 3,
    maximumTurns: 5,
    starterHints: [
      { target: "Cho tôi một bát phở bò.", english: "A bowl of beef pho, please." },
      { target: "Cho tôi một cốc trà đá.", english: "A glass of iced tea, please." },
    ],
    fallbackReplies: [
      { target: "Được! Cháu uống gì?", english: "Sure! What will you drink?" },
      { target: "Phở đây! Ăn đi, nóng lắm!", english: "Here's your pho! Eat up, it's very hot!" },
      { target: "Cảm ơn cháu! Lần sau lại đến nhé!", english: "Thank you! Come again next time!" },
    ],
  },
  {
    id: "di-cho",
    languageCode: "vi",
    characterId: "mai",
    title: "Haggling with Chị Mai",
    setting: "You stop at Chị Mai's fruit stall in the market, piled with mangoes, bananas and dragon fruit.",
    learnerRole: "Buy some fruit and try to get a better price.",
    characterRole: "Chị Mai, the seller, who names a high price and enjoys a bit of haggling.",
    goal: "Ask the price, say it's too expensive, agree on a price and buy something.",
    openingLine: "Chào em! Em mua gì?",
    openingEnglish: "Hi! What are you buying?",
    style: "roleplay",
    requiredConceptSlugs: ["bao-nhieu-tien", "toi-lay"],
    optionalConceptSlugs: ["dat-qua", "bot-di", "xoai", "chuoi", "thanh-long", "nghin", "cam-on"],
    minimumEncountered: 2,
    minimumTurns: 3,
    maximumTurns: 6,
    starterHints: [
      { target: "Xoài bao nhiêu tiền?", english: "How much are the mangoes?" },
      { target: "Đắt quá! Bớt đi!", english: "Too expensive! Make it cheaper!" },
    ],
    fallbackReplies: [
      { target: "Ba mươi nghìn một quả, em ạ.", english: "Thirty thousand each." },
      { target: "Thôi được, hai mươi nghìn!", english: "Oh, all right, twenty thousand!" },
      { target: "Cảm ơn em! Lần sau lại mua nhé!", english: "Thank you! Come and buy again!" },
    ],
  },
  {
    id: "gia-dinh-ong-son",
    languageCode: "vi",
    characterId: "son",
    title: "Family stories with Ông Sơn",
    setting: "You sit with Ông Sơn outside his house by the water while he mends his fishing net.",
    learnerRole: "Tell him about your family and ask about his.",
    characterRole: "Ông Sơn, an old fisherman, curious about your family and proud of his grandchildren.",
    goal: "Say who is in your family, give one age and ask one question about his family.",
    openingLine: "Chào cháu! Gia đình cháu có mấy người?",
    openingEnglish: "Hello! How many people are in your family?",
    style: "roleplay",
    requiredConceptSlugs: ["gia-dinh", "toi-co"],
    optionalConceptSlugs: ["bo", "me", "anh-trai", "chi-gai", "em-trai", "em-gai", "tuoi", "day-la-ai"],
    minimumEncountered: 3,
    minimumTurns: 3,
    maximumTurns: 5,
    starterHints: [
      { target: "Gia đình tôi có bốn người.", english: "There are four people in my family." },
      { target: "Tôi có một em gái.", english: "I have a younger sister." },
    ],
    fallbackReplies: [
      { target: "Thế à! Em gái cháu bao nhiêu tuổi?", english: "Really! How old is your younger sister?" },
      { target: "Ông có ba cháu. Chúng nó ở Hà Nội.", english: "I have three grandchildren. They're in Hanoi." },
      { target: "Cảm ơn cháu. Hẹn gặp lại!", english: "Thank you. See you again!" },
    ],
  },
];
