import type { Line } from "@/lib/game/line";
import type { UiText } from "@/lib/game/ui-text";

// Every piece of interface copy is Vietnamese first; English only appears on hover.
export const ui: UiText = {
  title: { t: "Cát Bà", en: "Cat Ba Island" },
  tagline: { t: "Học tiếng Việt ở một làng chài trên vịnh.", en: "Learn Vietnamese in a fishing village on the bay." },
  play: { t: "Chơi", en: "Play" },
  continue: { t: "Tiếp tục", en: "Continue" },
  signIn: { t: "Đăng nhập và chơi", en: "Sign in and play" },
  loading: { t: "Thuyền đang đến …", en: "The boat is coming …" },
  level: { t: "Cấp", en: "Level" },
  words: { t: "từ", en: "words" },
  dictionary: { t: "Từ điển", en: "Dictionary" },
  soundOn: { t: "Bật âm thanh", en: "Sound on" },
  soundOff: { t: "Tắt âm thanh", en: "Sound off" },
  menu: { t: "Menu", en: "Menu" },
  signOut: { t: "Đăng xuất", en: "Sign out" },
  close: { t: "Đóng", en: "Close" },
  back: { t: "Quay lại", en: "Back" },
  home: { t: "Về các đảo", en: "To all islands" },
  walkHint: { t: "Đi bằng W A S D, hoặc bấm vào mặt đất.", en: "Walk with W A S D, or click on the ground." },
  hoverHint: { t: "Giữ chuột trên một từ để xem nghĩa.", en: "Hold the mouse over a word to see what it means." },
  talkTo: (name: string): Line => ({ t: `Nói chuyện với ${name}`, en: `Talk to ${name}` }),
  lookAt: { t: "Xem", en: "Look" },
  goalTalk: (name: string, place: Line): Line => ({
    t: `Tìm ${name}: ${place.t}`,
    en: `Find ${name} at ${place.en.toLocaleLowerCase("en")}`,
  }),
  goalLearnMore: (name: string): Line => ({ t: `Học thêm với ${name}`, en: `Learn more from ${name}` }),
  goalMeetFirst: { t: "Đi đến chỗ Lan ở bến thuyền", en: "Walk to Lan at the boat landing" },
  goalDone: { t: "Đi khám phá đảo và tìm từ mới", en: "Explore the island and find new words" },
  newWord: { t: "Từ mới!", en: "New word!" },
  levelUp: { t: "Lên cấp!", en: "Level up!" },
  treeGrows: { t: "Cây đa ở đầu làng đang lớn!", en: "The banyan tree in the village square is growing!" },
  newFriend: (name: string): Line => ({ t: `${name} muốn làm quen với bạn!`, en: `${name} wants to meet you!` }),
  welcomeBack: (name: string): Line => ({ t: `Chào mừng bạn trở lại, ${name}!`, en: `Welcome back, ${name}!` }),
  wordGrows: (stage: Line): Line => ({ t: `Từ của bạn đang lớn: ${stage.t}!`, en: `Your word grows: ${stage.en}!` }),
  startWith: (name: string): Line => ({ t: `Bạn bắt đầu với ${name}!`, en: `You start with ${name}!` }),
  callAndTalk: (name: string): Line => ({ t: `Gọi ${name} và nói tiếng Việt!`, en: `Call ${name} and talk in Vietnamese!` }),
  next: { t: "Tiếp", en: "Next" },
  check: { t: "Kiểm tra", en: "Check" },
  dontKnow: { t: "Tôi không biết", en: "I don't know" },
  hint: { t: "Gợi ý", en: "Hint" },
  listen: { t: "Nghe", en: "Listen" },
  listenAgain: { t: "Nghe lại", en: "Listen again" },
  slowly: { t: "Chậm", en: "Slowly" },
  sayIt: { t: "Nói đi", en: "Say it" },
  listening: { t: "Tôi đang nghe …", en: "I'm listening …" },
  writeTarget: { t: "Viết bằng tiếng Việt …", en: "Write in Vietnamese …" },
  sayInTarget: { t: "Nói bằng tiếng Việt", en: "Say it in Vietnamese" },
  whatDoesItMean: { t: "Nghĩa là gì?", en: "What does it mean?" },
  whatDidYouHear: { t: "Bạn nghe thấy gì?", en: "What did you hear?" },
  buildSentence: { t: "Ghép câu", en: "Build the sentence" },
  newPhrase: { t: "Cái mới", en: "Something new" },
  repeatAfterMe: { t: "Nói theo tôi!", en: "Repeat after me!" },
  youSaid: { t: "Bạn đã nói", en: "You said" },
  heardYou: { t: "Tôi nghe thấy", en: "I heard" },
  bye: { t: "Tạm biệt!", en: "Bye!" },
  again: { t: "Lần nữa!", en: "One more time!" },
  talkForReal: { t: "Nói chuyện thật", en: "Talk for real (voice)" },
  chatTyping: { t: "Nhắn tin", en: "Chat (typing)" },
  yourName: { t: "Viết tên của bạn …", en: "Write your name …" },
  myNameIs: { t: "Tôi tên là …", en: "My name is …" },
  saving: { t: "Đang lưu …", en: "Saving …" },
  xpGained: { t: "điểm", en: "points" },
  correct: { t: "đúng", en: "correct" },
  phrases: { t: "Câu", en: "Phrases" },
  grammar: { t: "Ngữ pháp", en: "Grammar" },
  littleGrammar: { t: "Một chút ngữ pháp", en: "A little grammar" },
  newGrammar: { t: "Ngữ pháp mới", en: "New grammar tip" },
  things: { t: "Đồ vật trên đảo", en: "Things on the island" },
  notFound: { t: "Chưa tìm thấy", en: "Not found yet" },
  notMet: { t: "Chưa học", en: "Not learned yet" },
  connecting: { t: "Đang gọi …", en: "Calling …" },
  liveNow: { t: "Cứ nói đi! Tôi đang nghe.", en: "Just talk! I'm listening." },
  mute: { t: "Tắt tiếng", en: "Mute" },
  unmute: { t: "Bật micro", en: "Microphone on" },
  endCall: { t: "Cúp máy", en: "Hang up" },
  liveOver: { t: "Cuộc nói chuyện đã xong.", en: "The conversation is over." },
  reflect: { t: "Tôi đã học được gì?", en: "What did I learn?" },
  typeReply: { t: "Trả lời bằng tiếng Việt …", en: "Answer in Vietnamese …" },
  send: { t: "Gửi", en: "Send" },
  needsAccount: { t: "Đăng nhập để nói chuyện thật.", en: "Sign in to talk for real." },
  liveUnavailable: { t: "Bây giờ giọng nói không hoạt động. Mình nhắn tin nhé!", en: "Voice isn't working right now. Let's chat instead!" },
  notReadyToTalk: { t: "Học thêm một chút nữa, rồi mình nói chuyện!", en: "Learn a bit more first, then we can talk!" },
  error: { t: "Ôi! Có lỗi rồi.", en: "Oops! Something went wrong." },
  tryAgain: { t: "Thử lại", en: "Try again" },
  captions: { t: "Phụ đề", en: "Subtitles" },
  mic: { t: "Micro", en: "Microphone" },
  youLabel: { t: "Bạn", en: "You" },
  stageLabel: { t: "Đang lớn", en: "Growing" },
  letters: { t: "Chữ cái tiếng Việt", en: "Vietnamese letters" },
  controls: { t: "Điều khiển", en: "Controls" },
  controlsMove: { t: "Đi: W A S D / mũi tên / bấm chuột", en: "Walk: W A S D / arrows / click" },
  controlsTalk: { t: "Nói chuyện: E / phím cách", en: "Talk: E / space" },
  controlsCamera: { t: "Camera: kéo chuột, cuộn để phóng to", en: "Camera: drag with the mouse, scroll to zoom" },
  controlsRun: { t: "Chạy: giữ Shift", en: "Run: hold Shift" },
  spelling: { t: "Xem lại cách viết và dấu nhé!", en: "Look at the spelling and the tone marks!" },
  article: { t: "Đừng quên loại từ: con, cái, quả …", en: "Don't forget the classifier: con, cái, quả …" },
  yourStyle: { t: "Phong cách của bạn", en: "Your style" },
  style: { t: "Phong cách", en: "Style" },
  englishAuto: { t: "Tiếng Anh: tự động", en: "English subtitles: automatic" },
  englishOn: { t: "Tiếng Anh: bật", en: "English subtitles: on" },
  englishOff: { t: "Tiếng Anh: tắt", en: "English subtitles: off" },
  skip: { t: "Bỏ qua", en: "Skip" },
  tryIt: { t: "Thử đi!", en: "Try it!" },
  nowYouCanSay: { t: "Bây giờ bạn có thể nói …", en: "Now you can say …" },
  letsGo: { t: "Đi thôi!", en: "Let's go!" },
  presents: { t: "Sapling giới thiệu", en: "Sapling presents" },
  welcomeTitle: { t: "Chào mừng đến Cát Bà", en: "Welcome to Cát Bà" },
  learnedBefore: { t: "Bạn đã học tiếng Việt chưa?", en: "Have you learned Vietnamese before?" },
  quickCheck: { t: "Kiểm tra nhanh", en: "Quick check" },
  done: { t: "Xong!", en: "Done!" },
  startFromTop: { t: "Mình bắt đầu từ đầu nhé!", en: "We'll start at the beginning!" },
  replyIfYouLike: { t: "Trả lời nếu bạn muốn", en: "Reply if you like" },
  askForBill: { t: "Gọi tính tiền!", en: "Ask for the bill!" },
  fillTray: { t: "Xếp khay đi!", en: "Fill the tray!" },
  ready: { t: "Xong!", en: "Done!" },
  option: { t: "Lựa chọn", en: "Option" },
  yourTray: { t: "Khay của bạn", en: "Your tray" },
  flowers: { t: "hoa", en: "flowers" },
  notes: { t: "Ghi chú", en: "Notes" },
  conversation: { t: "Cuộc nói chuyện", en: "The conversation" },
  situation: { t: "Chuyện gì đang xảy ra?", en: "What's happening?" },
  units: { t: "Bài học", en: "Chapters" },
  locked: { t: "Đang khóa", en: "Locked" },
};
