-- vi: 96 concepts, in course order.
insert into public.concepts (language_code, slug, kind, canonical_form, gloss, description, metadata, sort_order, is_active)
values
  ('vi', 'xin-chao', 'chunk', 'Xin chào', 'Hello!', 'Hello!', '{"level":"A1","unit":"xin-chao"}'::jsonb, 1, true),
  ('vi', 'chao-ban', 'chunk', 'Chào bạn', 'Hi!', 'Hi!', '{"level":"A1","unit":"xin-chao"}'::jsonb, 2, true),
  ('vi', 'cam-on', 'chunk', 'Cảm ơn', 'Thank you!', 'Thank you!', '{"level":"A1","unit":"xin-chao"}'::jsonb, 3, true),
  ('vi', 'khong-co-gi', 'chunk', 'Không có gì', 'You''re welcome.', 'You''re welcome.', '{"level":"A1","unit":"xin-chao"}'::jsonb, 4, true),
  ('vi', 'vang', 'word', 'vâng', 'yes (polite)', '"Vâng" is the polite yes of the North.', '{"level":"A1","unit":"xin-chao"}'::jsonb, 5, true),
  ('vi', 'khong', 'word', 'không', 'no', 'no', '{"level":"A1","unit":"xin-chao"}'::jsonb, 6, true),
  ('vi', 'xin-loi', 'chunk', 'Xin lỗi', 'Sorry! / Excuse me!', 'Sorry! / Excuse me!', '{"level":"A1","unit":"xin-chao"}'::jsonb, 7, true),
  ('vi', 'khong-sao', 'chunk', 'Không sao', 'It''s okay. / No problem.', 'It''s okay. / No problem.', '{"level":"A1","unit":"xin-chao"}'::jsonb, 8, true),
  ('vi', 'tam-biet', 'chunk', 'Tạm biệt', 'Goodbye!', 'Goodbye!', '{"level":"A1","unit":"xin-chao"}'::jsonb, 9, true),
  ('vi', 'hen-gap-lai', 'chunk', 'Hẹn gặp lại', 'See you again!', 'See you again!', '{"level":"A1","unit":"xin-chao"}'::jsonb, 10, true),
  ('vi', 'ban-khoe-khong', 'chunk', 'Bạn khỏe không?', 'How are you?', 'How are you?', '{"level":"A1","unit":"xin-chao"}'::jsonb, 11, true),
  ('vi', 'toi-khoe', 'chunk', 'Tôi khỏe, cảm ơn', 'I''m well, thanks.', 'I''m well, thanks.', '{"level":"A1","unit":"xin-chao"}'::jsonb, 12, true),
  ('vi', 'con-ban', 'chunk', 'Còn bạn?', 'And you?', 'And you?', '{"level":"A1","unit":"xin-chao"}'::jsonb, 13, true),
  ('vi', 'toi-khong-biet', 'chunk', 'Tôi không biết', 'I don''t know.', 'I don''t know.', '{"level":"A1","unit":"xin-chao"}'::jsonb, 14, true),
  ('vi', 'day-la', 'construction', 'Đây là …', 'This is …', 'This is …', '{"level":"A1","unit":"xin-chao"}'::jsonb, 15, true),
  ('vi', 'oi', 'word', '… ơi', 'Hey …! (calling someone)', 'Put "ơi" after a name or a title to call someone kindly.', '{"level":"A1","unit":"xin-chao"}'::jsonb, 16, true),
  ('vi', 'tot-qua', 'chunk', 'Tốt quá', 'Great!', 'Great!', '{"level":"A1","unit":"xin-chao"}'::jsonb, 17, true),
  ('vi', 'toi-ten-la', 'chunk', 'Tôi tên là …', 'My name is …', 'My name is …', '{"level":"A1","unit":"gioi-thieu"}'::jsonb, 18, true),
  ('vi', 'ban-ten-la-gi', 'chunk', 'Bạn tên là gì?', 'What''s your name?', 'What''s your name?', '{"level":"A1","unit":"gioi-thieu"}'::jsonb, 19, true),
  ('vi', 'rat-vui', 'chunk', 'Rất vui được gặp bạn', 'Nice to meet you!', 'Nice to meet you!', '{"level":"A1","unit":"gioi-thieu"}'::jsonb, 20, true),
  ('vi', 'toi-la', 'construction', 'Tôi là …', 'I am …', 'I am …', '{"level":"A1","unit":"gioi-thieu"}'::jsonb, 21, true),
  ('vi', 'ban-la-nguoi-nuoc-nao', 'chunk', 'Bạn là người nước nào?', 'Where are you from?', 'Where are you from?', '{"level":"A1","unit":"gioi-thieu"}'::jsonb, 22, true),
  ('vi', 'toi-la-nguoi', 'chunk', 'Tôi là người …', 'I''m … (nationality)', 'I''m … (nationality)', '{"level":"A1","unit":"gioi-thieu"}'::jsonb, 23, true),
  ('vi', 'ban-song-o-dau', 'chunk', 'Bạn sống ở đâu?', 'Where do you live?', 'Where do you live?', '{"level":"A1","unit":"gioi-thieu"}'::jsonb, 24, true),
  ('vi', 'toi-song-o', 'chunk', 'Tôi sống ở …', 'I live in …', 'I live in …', '{"level":"A1","unit":"gioi-thieu"}'::jsonb, 25, true),
  ('vi', 'tieng-viet', 'chunk', 'tiếng Việt', 'Vietnamese (the language)', 'Vietnamese (the language)', '{"level":"A1","unit":"gioi-thieu"}'::jsonb, 26, true),
  ('vi', 'ban-noi-tieng-anh', 'chunk', 'Bạn có nói tiếng Anh không?', 'Do you speak English?', 'Do you speak English?', '{"level":"A1","unit":"gioi-thieu"}'::jsonb, 27, true),
  ('vi', 'mot-chut', 'chunk', 'Tôi nói một chút tiếng Việt', 'I speak a little Vietnamese.', 'I speak a little Vietnamese.', '{"level":"A1","unit":"gioi-thieu"}'::jsonb, 28, true),
  ('vi', 'noi-lai', 'chunk', 'Bạn nói lại được không?', 'Can you say that again?', 'Can you say that again?', '{"level":"A1","unit":"gioi-thieu"}'::jsonb, 29, true),
  ('vi', 'noi-cham', 'chunk', 'Bạn nói chậm được không?', 'Can you speak slowly?', 'Can you speak slowly?', '{"level":"A1","unit":"gioi-thieu"}'::jsonb, 30, true),
  ('vi', 'toi', 'word', 'tôi', 'I / me', 'I / me', '{"level":"A1","unit":"gioi-thieu"}'::jsonb, 31, true),
  ('vi', 'ban', 'word', 'bạn', 'you / friend', 'you / friend', '{"level":"A1","unit":"gioi-thieu"}'::jsonb, 32, true),
  ('vi', 'anh', 'word', 'anh', 'you (to a young man) / older brother', 'Vietnamese picks "you" by age: anh for a man a bit older than you, chị for a woman.', '{"level":"A1","unit":"gioi-thieu"}'::jsonb, 33, true),
  ('vi', 'chi', 'word', 'chị', 'you (to a young woman) / older sister', 'you (to a young woman) / older sister', '{"level":"A1","unit":"gioi-thieu"}'::jsonb, 34, true),
  ('vi', 'em', 'word', 'em', 'you (to someone younger) / younger sibling', 'you (to someone younger) / younger sibling', '{"level":"A1","unit":"gioi-thieu"}'::jsonb, 35, true),
  ('vi', 'pho', 'word', 'phở', 'pho (noodle soup)', 'pho (noodle soup)', '{"level":"A1","unit":"quan-pho"}'::jsonb, 36, true),
  ('vi', 'pho-bo', 'chunk', 'phở bò', 'beef pho', 'beef pho', '{"level":"A1","unit":"quan-pho"}'::jsonb, 37, true),
  ('vi', 'pho-ga', 'chunk', 'phở gà', 'chicken pho', 'chicken pho', '{"level":"A1","unit":"quan-pho"}'::jsonb, 38, true),
  ('vi', 'bat', 'word', 'bát', 'bowl', 'Northerners say "bát"; in the South a bowl is "tô" or "chén".', '{"level":"A1","unit":"quan-pho"}'::jsonb, 39, true),
  ('vi', 'cho-toi', 'construction', 'Cho tôi …', '… please (I''d like …)', '… please (I''d like …)', '{"level":"A1","unit":"quan-pho"}'::jsonb, 40, true),
  ('vi', 'ca-phe', 'chunk', 'cà phê', 'coffee', 'coffee', '{"level":"A1","unit":"quan-pho"}'::jsonb, 41, true),
  ('vi', 'ca-phe-sua-da', 'chunk', 'cà phê sữa đá', 'iced milk coffee', 'iced milk coffee', '{"level":"A1","unit":"quan-pho"}'::jsonb, 42, true),
  ('vi', 'tra-da', 'chunk', 'trà đá', 'iced tea', 'iced tea', '{"level":"A1","unit":"quan-pho"}'::jsonb, 43, true),
  ('vi', 'coc', 'word', 'cốc', 'glass / cup', 'Northerners say "cốc"; in the South it''s "ly".', '{"level":"A1","unit":"quan-pho"}'::jsonb, 44, true),
  ('vi', 'nuoc', 'word', 'nước', 'water', 'water', '{"level":"A1","unit":"quan-pho"}'::jsonb, 45, true),
  ('vi', 'banh-mi', 'chunk', 'bánh mì', 'bread / banh mi', 'bread / banh mi', '{"level":"A1","unit":"quan-pho"}'::jsonb, 46, true),
  ('vi', 'com', 'word', 'cơm', 'rice / a meal', 'rice / a meal', '{"level":"A1","unit":"quan-pho"}'::jsonb, 47, true),
  ('vi', 'an', 'word', 'ăn', 'to eat', 'to eat', '{"level":"A1","unit":"quan-pho"}'::jsonb, 48, true),
  ('vi', 'uong', 'word', 'uống', 'to drink', 'to drink', '{"level":"A1","unit":"quan-pho"}'::jsonb, 49, true),
  ('vi', 'toi-muon', 'construction', 'Tôi muốn …', 'I want …', 'I want …', '{"level":"A1","unit":"quan-pho"}'::jsonb, 50, true),
  ('vi', 'ngon-qua', 'chunk', 'Ngon quá', 'Delicious!', 'Delicious!', '{"level":"A1","unit":"quan-pho"}'::jsonb, 51, true),
  ('vi', 'khong-cay', 'chunk', 'Không cay nhé', 'Not spicy, please.', 'Not spicy, please.', '{"level":"A1","unit":"quan-pho"}'::jsonb, 52, true),
  ('vi', 'no-roi', 'chunk', 'Tôi no rồi', 'I''m full.', 'I''m full.', '{"level":"A1","unit":"quan-pho"}'::jsonb, 53, true),
  ('vi', 'tinh-tien', 'chunk', 'Tính tiền', 'The bill, please!', 'The bill, please!', '{"level":"A1","unit":"quan-pho"}'::jsonb, 54, true),
  ('vi', 'so-mot', 'word', 'một', 'one', 'one', '{"level":"A1","unit":"o-cho"}'::jsonb, 55, true),
  ('vi', 'so-hai', 'word', 'hai', 'two', 'two', '{"level":"A1","unit":"o-cho"}'::jsonb, 56, true),
  ('vi', 'so-ba', 'word', 'ba', 'three', 'three', '{"level":"A1","unit":"o-cho"}'::jsonb, 57, true),
  ('vi', 'so-bon', 'word', 'bốn', 'four', 'four', '{"level":"A1","unit":"o-cho"}'::jsonb, 58, true),
  ('vi', 'so-nam', 'word', 'năm', 'five', 'five', '{"level":"A1","unit":"o-cho"}'::jsonb, 59, true),
  ('vi', 'so-sau', 'word', 'sáu', 'six', 'six', '{"level":"A1","unit":"o-cho"}'::jsonb, 60, true),
  ('vi', 'so-bay', 'word', 'bảy', 'seven', 'seven', '{"level":"A1","unit":"o-cho"}'::jsonb, 61, true),
  ('vi', 'so-tam', 'word', 'tám', 'eight', 'eight', '{"level":"A1","unit":"o-cho"}'::jsonb, 62, true),
  ('vi', 'so-chin', 'word', 'chín', 'nine', 'nine', '{"level":"A1","unit":"o-cho"}'::jsonb, 63, true),
  ('vi', 'so-muoi', 'word', 'mười', 'ten', 'ten', '{"level":"A1","unit":"o-cho"}'::jsonb, 64, true),
  ('vi', 'tram', 'word', 'trăm', 'hundred', 'hundred', '{"level":"A1","unit":"o-cho"}'::jsonb, 65, true),
  ('vi', 'nghin', 'word', 'nghìn', 'thousand', 'Northerners say "nghìn"; in the South it''s "ngàn".', '{"level":"A1","unit":"o-cho"}'::jsonb, 66, true),
  ('vi', 'dong', 'word', 'đồng', 'dong (Vietnamese money)', 'dong (Vietnamese money)', '{"level":"A1","unit":"o-cho"}'::jsonb, 67, true),
  ('vi', 'bao-nhieu-tien', 'chunk', 'Bao nhiêu tiền?', 'How much is it?', 'How much is it?', '{"level":"A1","unit":"o-cho"}'::jsonb, 68, true),
  ('vi', 'cai-nay', 'chunk', 'cái này', 'this one', 'this one', '{"level":"A1","unit":"o-cho"}'::jsonb, 69, true),
  ('vi', 'dat-qua', 'chunk', 'Đắt quá', 'Too expensive!', 'Too expensive!', '{"level":"A1","unit":"o-cho"}'::jsonb, 70, true),
  ('vi', 're', 'word', 'rẻ', 'cheap', 'cheap', '{"level":"A1","unit":"o-cho"}'::jsonb, 71, true),
  ('vi', 'bot-di', 'chunk', 'Bớt đi', 'Make it cheaper!', 'Make it cheaper!', '{"level":"A1","unit":"o-cho"}'::jsonb, 72, true),
  ('vi', 'toi-lay', 'construction', 'Tôi lấy …', 'I''ll take …', 'I''ll take …', '{"level":"A1","unit":"o-cho"}'::jsonb, 73, true),
  ('vi', 'co-khong', 'construction', 'Có … không?', 'Do you have …?', 'Do you have …?', '{"level":"A1","unit":"o-cho"}'::jsonb, 74, true),
  ('vi', 'xoai', 'word', 'quả xoài', 'mango', 'Northerners count fruit with "quả"; in the South it''s "trái".', '{"level":"A1","unit":"o-cho"}'::jsonb, 75, true),
  ('vi', 'chuoi', 'word', 'quả chuối', 'banana', 'banana', '{"level":"A1","unit":"o-cho"}'::jsonb, 76, true),
  ('vi', 'thanh-long', 'chunk', 'quả thanh long', 'dragon fruit', 'dragon fruit', '{"level":"A1","unit":"o-cho"}'::jsonb, 77, true),
  ('vi', 'gia-dinh', 'chunk', 'gia đình', 'family', 'family', '{"level":"A1","unit":"gia-dinh"}'::jsonb, 78, true),
  ('vi', 'bo', 'word', 'bố', 'dad', 'Northerners say "bố"; in the South it''s "ba".', '{"level":"A1","unit":"gia-dinh"}'::jsonb, 79, true),
  ('vi', 'me', 'word', 'mẹ', 'mum', 'mum', '{"level":"A1","unit":"gia-dinh"}'::jsonb, 80, true),
  ('vi', 'ong', 'word', 'ông', 'grandfather / you (to an old man)', 'grandfather / you (to an old man)', '{"level":"A1","unit":"gia-dinh"}'::jsonb, 81, true),
  ('vi', 'ba', 'word', 'bà', 'grandmother / you (to an old woman)', 'grandmother / you (to an old woman)', '{"level":"A1","unit":"gia-dinh"}'::jsonb, 82, true),
  ('vi', 'anh-trai', 'chunk', 'anh trai', 'older brother', 'older brother', '{"level":"A1","unit":"gia-dinh"}'::jsonb, 83, true),
  ('vi', 'chi-gai', 'chunk', 'chị gái', 'older sister', 'older sister', '{"level":"A1","unit":"gia-dinh"}'::jsonb, 84, true),
  ('vi', 'em-trai', 'chunk', 'em trai', 'younger brother', 'younger brother', '{"level":"A1","unit":"gia-dinh"}'::jsonb, 85, true),
  ('vi', 'em-gai', 'chunk', 'em gái', 'younger sister', 'younger sister', '{"level":"A1","unit":"gia-dinh"}'::jsonb, 86, true),
  ('vi', 'con', 'word', 'con', 'child', 'child', '{"level":"A1","unit":"gia-dinh"}'::jsonb, 87, true),
  ('vi', 'chau', 'word', 'cháu', 'grandchild', 'grandchild', '{"level":"A1","unit":"gia-dinh"}'::jsonb, 88, true),
  ('vi', 'vo', 'word', 'vợ', 'wife', 'wife', '{"level":"A1","unit":"gia-dinh"}'::jsonb, 89, true),
  ('vi', 'chong', 'word', 'chồng', 'husband', 'husband', '{"level":"A1","unit":"gia-dinh"}'::jsonb, 90, true),
  ('vi', 'nguoi', 'word', 'người', 'person / people', 'person / people', '{"level":"A1","unit":"gia-dinh"}'::jsonb, 91, true),
  ('vi', 'toi-co', 'construction', 'Tôi có …', 'I have …', 'I have …', '{"level":"A1","unit":"gia-dinh"}'::jsonb, 92, true),
  ('vi', 'anh-chi-em', 'chunk', 'Bạn có anh chị em không?', 'Do you have brothers and sisters?', 'Do you have brothers and sisters?', '{"level":"A1","unit":"gia-dinh"}'::jsonb, 93, true),
  ('vi', 'bao-nhieu-tuoi', 'chunk', 'Bạn bao nhiêu tuổi?', 'How old are you?', 'How old are you?', '{"level":"A1","unit":"gia-dinh"}'::jsonb, 94, true),
  ('vi', 'tuoi', 'chunk', 'Tôi … tuổi', 'I''m … years old.', 'I''m … years old.', '{"level":"A1","unit":"gia-dinh"}'::jsonb, 95, true),
  ('vi', 'day-la-ai', 'chunk', 'Đây là ai?', 'Who is this?', 'Who is this?', '{"level":"A1","unit":"gia-dinh"}'::jsonb, 96, true)
on conflict (language_code, slug) do update
set
  kind = excluded.kind,
  canonical_form = excluded.canonical_form,
  gloss = excluded.gloss,
  description = coalesce(nullif(excluded.description, excluded.gloss), public.concepts.description, excluded.description),
  metadata = public.concepts.metadata || excluded.metadata,
  sort_order = excluded.sort_order,
  is_active = true,
  updated_at = now();
