import type { PracticeCharacter, PracticeScenario } from "@/types/practice";

export const characters: PracticeCharacter[] = [
  {
    id: "emil",
    name: "Emil",
    description: "Patient, dryly funny, and usually on his way to a bakery.",
  },
];

export const scenarios: PracticeScenario[] = [
  {
    id: "meet-emil",
    languageCode: "da",
    characterId: "emil",
    title: "Meet Emil",
    setting: "You meet outside a bakery in Nørrebro.",
    learnerRole: "Introduce yourself and get to know Emil.",
    characterRole: "A friendly local meeting you for the first time.",
    goal: "Exchange names and complete a short, natural introduction.",
    openingLine: "Hej! Jeg hedder Emil. Hvad hedder du?",
    openingEnglish: "Hi! My name is Emil. What is your name?",
    style: "roleplay",
    requiredConceptSlugs: ["hej", "jeg-hedder"],
    optionalConceptSlugs: ["hvad-hedder-du", "hyggeligt-at-moede-dig", "ja", "nej"],
    minimumEncountered: 0,
    minimumTurns: 3,
    maximumTurns: 5,
    starterHints: [
      { target: "Hej, jeg hedder …", english: "Hi, my name is …" },
      { target: "Hyggeligt at møde dig.", english: "Nice to meet you." },
    ],
    fallbackReplies: [
      { target: "Hyggeligt at møde dig! Hvad laver du til daglig?", english: "Nice to meet you! What do you do day to day?" },
      { target: "Det lyder godt. Bor du her i byen?", english: "That sounds good. Do you live here in the city?" },
      { target: "Godt at møde dig. Vi ses snart igen!", english: "Good to meet you. See you again soon!" },
    ],
  },
  {
    id: "bakery-order",
    languageCode: "da",
    characterId: "emil",
    title: "At the bakery",
    setting: "Emil has brought you to his favorite neighborhood bakery.",
    learnerRole: "Choose something and order it naturally.",
    characterRole: "Your friend, helping only when the conversation stalls.",
    goal: "Order a drink or pastry and respond to one follow-up question.",
    openingLine: "Hvad har du lyst til? Jeg tager en kaffe.",
    openingEnglish: "What would you like? I’m having a coffee.",
    style: "roleplay",
    requiredConceptSlugs: ["jeg-vil-gerne", "kaffe", "tak"],
    optionalConceptSlugs: ["te", "vand", "kanelsnegl", "med-maelk", "regningen-tak"],
    minimumEncountered: 2,
    minimumTurns: 3,
    maximumTurns: 6,
    starterHints: [
      { target: "Jeg vil gerne have …", english: "I would like …" },
      { target: "… med mælk, tak.", english: "… with milk, please." },
    ],
    fallbackReplies: [
      { target: "Godt valg. Vil du også have en kanelsnegl?", english: "Good choice. Would you also like a cinnamon roll?" },
      { target: "Skal vi sidde her eller tage det med?", english: "Should we sit here or take it with us?" },
      { target: "Perfekt. Jeg finder et bord.", english: "Perfect. I’ll find a table." },
    ],
  },
  {
    id: "station-change",
    languageCode: "da",
    characterId: "emil",
    title: "A change at the station",
    setting: "Your train platform changes while you and Emil are travelling.",
    learnerRole: "Find the right train and explain where you need to get off.",
    characterRole: "Your travelling companion.",
    goal: "Ask for direction, check the train, and confirm your stop.",
    openingLine: "Sporet er ændret. Ved du, hvor toget til København går fra?",
    openingEnglish: "The platform changed. Do you know where the train to Copenhagen leaves from?",
    style: "roleplay",
    requiredConceptSlugs: ["hvor-er-stationen", "toget-til-koebenhavn", "jeg-skal-af-her"],
    optionalConceptSlugs: ["kan-du-gentage", "tal-langsommere", "jeg-forstaar-ikke"],
    minimumEncountered: 2,
    minimumTurns: 4,
    maximumTurns: 6,
    starterHints: [
      { target: "Hvor er …?", english: "Where is …?" },
      { target: "Går dette tog til …?", english: "Does this train go to …?" },
    ],
    fallbackReplies: [
      { target: "Jeg tror, det er spor fem. Skal vi spørge nogen?", english: "I think it is platform five. Should we ask someone?" },
      { target: "Ja, det er det rigtige tog. Hvor skal du af?", english: "Yes, this is the right train. Where are you getting off?" },
      { target: "Fint, så siger jeg til, når vi er der.", english: "Great, then I’ll tell you when we are there." },
    ],
  },
  {
    id: "make-weekend-plans",
    languageCode: "da",
    characterId: "emil",
    title: "Make a plan",
    setting: "Emil asks what you want to do this weekend.",
    learnerRole: "Share a preference and suggest a plan.",
    characterRole: "A friend making plans with you.",
    goal: "Respond openly, suggest an activity, and agree on a next step.",
    openingLine: "Har du planer i weekenden? Skal vi finde på noget?",
    openingEnglish: "Do you have plans this weekend? Should we think of something to do?",
    style: "open_question",
    requiredConceptSlugs: ["maaske", "skal-vi-infinitive"],
    optionalConceptSlugs: ["ja", "nej", "kan-du-gentage"],
    minimumEncountered: 1,
    minimumTurns: 3,
    maximumTurns: 5,
    starterHints: [
      { target: "Måske …", english: "Maybe …" },
      { target: "Skal vi …?", english: "Should we …?" },
    ],
    fallbackReplies: [
      { target: "Det kunne være hyggeligt. Hvornår passer det dig?", english: "That could be nice. When works for you?" },
      { target: "Måske lørdag?", english: "Maybe Saturday?" },
      { target: "Så har vi en plan.", english: "Then we have a plan." },
    ],
  },
];
