import type { Discovery } from "@/lib/game/discoveries";

// Things on Tannenau the player can find and name.
export const discoveries: Discovery[] = [
  { id: "faehre", t: "der Dampfer", en: "the steamboat", x: 2.6, z: 38, prop: "none", lift: 3.4 },
  { id: "steg", t: "der Steg", en: "the landing stage", x: -1.2, z: 30.5, prop: "none", lift: 1.8 },
  { id: "fisch", t: "der Fisch", en: "the fish", x: 1.1, z: 33, prop: "bucket", lift: 1.6 },
  { id: "moewe", t: "die Möwe", en: "the gull", x: -1.5, z: 38.5, prop: "gull", lift: 2.6 },
  { id: "ruderboot", t: "das Ruderboot", en: "the rowing boat", x: -4.4, z: 31.8, rot: 0.6, prop: "rowboat", lift: 1.6 },
  { id: "laterne", t: "die Laterne", en: "the lantern", x: 1.8, z: 15, prop: "none", lift: 3 },
  { id: "maibaum", t: "der Maibaum", en: "the maypole", x: 4.6, z: 3.6, prop: "none", lift: 9 },
  { id: "brunnen", t: "der Brunnen", en: "the fountain", x: -4.5, z: 3.5, prop: "none", lift: 2.8 },
  { id: "bank", t: "die Bank", en: "the bench", x: -4, z: 10.5, prop: "none", lift: 1.8 },
  { id: "fahrrad", t: "das Fahrrad", en: "the bicycle", x: -7.8, z: 13.2, rot: 0.9, prop: "bike", lift: 1.8 },
  { id: "tasse", t: "die Tasse", en: "the cup", x: -9, z: 9.8, prop: "cup", lift: 2, y: 1.2 },
  { id: "brezel", t: "die Brezel", en: "the pretzel", x: -12.4, z: 10.2, prop: "pretzel", lift: 2.8 },
  { id: "fass", t: "das Fass", en: "the barrel", x: -18.8, z: 9.4, prop: "barrel", lift: 1.6 },
  { id: "katze", t: "die Katze", en: "the cat", x: -16, z: 12.2, rot: 1.2, prop: "cat", lift: 1.3 },
  { id: "briefkasten", t: "der Briefkasten", en: "the mailbox", x: -8.6, z: 18.8, rot: 0.4, prop: "mailbox", lift: 2 },
  { id: "kuckucksuhr", t: "die Kuckucksuhr", en: "the cuckoo clock", x: 8.2, z: 17.6, rot: -2.4, prop: "cuckoo", lift: 3.4 },
  { id: "hund", t: "der Hund", en: "the dog", x: 6.2, z: 21, rot: -2.2, prop: "dog", lift: 1.4 },
  { id: "uhr", t: "die Bahnhofsuhr", en: "the station clock", x: 15, z: -6, prop: "none", lift: 3.7 },
  { id: "zug", t: "der Zug", en: "the train", x: 22.4, z: -5, prop: "none", lift: 3.6 },
  { id: "stein", t: "der Stein", en: "the stone", x: -28.5, z: 1, prop: "stone", lift: 2.2 },
  { id: "tanne", t: "die Tanne", en: "the fir tree", x: -19.5, z: 3.5, prop: "fir", lift: 6.4 },
  { id: "reh", t: "das Reh", en: "the deer", x: -17, z: -13.5, rot: 0.8, prop: "deer", lift: 2.2 },
  { id: "pilz", t: "der Pilz", en: "the mushroom", x: -13.5, z: -26, prop: "mushroom", lift: 1.2 },
  { id: "kuh", t: "die Kuh", en: "the cow", x: -1.8, z: -24.5, rot: 1.3, prop: "cow", lift: 2.4 },
  { id: "schubkarre", t: "die Schubkarre", en: "the wheelbarrow", x: -3.6, z: -12.2, rot: 0.5, prop: "wheelbarrow", lift: 1.6 },
  { id: "blume", t: "die Blume", en: "the flower", x: -9.4, z: -11.6, prop: "flower", lift: 1.3 },
  { id: "apfelbaum", t: "der Apfelbaum", en: "the apple tree", x: 3.2, z: -15.5, prop: "appletree", lift: 4.6 },
  { id: "igel", t: "der Igel", en: "the hedgehog", x: 8.5, z: -8.5, prop: "hedgehog", lift: 1.1 },
  { id: "schaukel", t: "die Schaukel", en: "the swing", x: -8.5, z: -3.5, prop: "swing", lift: 3.6 },
  { id: "kapelle", t: "die Kapelle", en: "the chapel", x: 6.6, z: -22, prop: "none", lift: 7.5 },
];
