// Word-level English glosses for everything Tannenau says in German, beyond
// the single words the course itself teaches (those come from ./course).
// Inflected forms the stemmer can't reach are listed explicitly.

export const entries = `
der=the|die=the|das=the / that|dem=the (to the)|den=the|des=of the|ein=a / one|eine=a / one|einen=a / one|einem=a (to a)|einer=a / one (of a)
ich=I|mich=me|mir=(to) me|du=you|dich=you|dir=(to) you|er=he|ihn=him|ihm=(to) him|sie=she / they / you (formal)|ihnen=(to) them / you (formal)|es=it|s=it
wir=we|uns=us|ihr=you (all) / her|euch=you (all)|man=one / you
bin=am|bist=are|ist=is|sind=are|seid=are|war=was|warst=were|waren=were|gewesen=been
habe=have|hast=have|hat=has|haben=have / to have|habt=have|hatte=had|hatten=had
kann=can|kannst=can|können=can / to be able to|könnt=can|muss=must / have to|musst=must|müssen=must / to have to|soll=should|sollst=should|sollen=should
will=want|willst=want|wollen=want / to want|wollte=wanted|möchte=would like|möchtest=would like|darf=may|werde=will|wird=will / becomes|werden=will / to become
nicht=not|kein=no / not a|keine=no / not any|keinen=no / not a|nichts=nothing|nur=only|noch=still / yet|schon=already|auch=also / too|sehr=very|so=so / like this|ganz=quite / completely|gar=at all
und=and|oder=or|aber=but|denn=because / then|wenn=if / when|weil=because|dass=that|ob=whether
was=what|wer=who|wie=how / like|wo=where|woher=where from|wohin=where to|wann=when|warum=why|welche=which|welcher=which|welches=which
in=in|im=in the|ins=into the|an=at / on|am=at the / on the|auf=on / onto|aus=from / out of|bei=at / near|beim=at the|mit=with|nach=to / after|von=from / of|vom=from the|zu=to / too|zum=to the|zur=to the|für=for|um=at / around|bis=until / to|über=over / about|unter=under|vor=in front of / ago|hinter=behind|neben=next to|zwischen=between|ohne=without|ab=from / off
hier=here|da=there|dort=there|drüben=over there|heute=today|morgen=tomorrow|gestern=yesterday|jetzt=now|dann=then|mal=just / once|gleich=soon / right away|gerade=just now|wieder=again|erst=only / first|zurück=back|los=off / wrong|ja=yes|nein=no|doch=yes (really) / after all|na=well|oh=oh|ah=ah|ach=oh|hmm=hmm|mmm=mmm|brr=brr (cold!)|au=ouch|oje=oh dear|haha=haha|wow=wow|buhuu=boo-hoo|na ja=well
gut=good / well|gute=good|guten=good|guter=good|gutes=good|besten=best|schlecht=bad|perfekt=perfect|lang=long|lange=long / a long time|kurz=short / briefly|letzte=last|letztes=last|letzten=last|nächste=next|nächsten=next|erste=first|ersten=first|fünften=fifth|echt=really|fast=almost|alle=all / everyone|allen=all|ander=other|andererseits=on the other hand|einerseits=on the one hand
mache=do / make|machst=do / make|macht=does / makes|machen=to do / to make|machs=do it (mach's)|komm=come|komme=come|kommst=come|kommt=comes|kommen=to come|gehe=go|gehst=go|geht=goes|gehen=to go|geh=go|fahre=go / drive|fährst=go / drive|fährt=goes / drives|fahrt=go / drive|steigen=to get (on / off)|steig=get (on)
sage=say|sagst=say|sagt=says|sag=say|sprich=speak|sprichst=speak|spricht=speaks|sprechen=to speak|verstehe=understand|verstehst=understand|versteht=understands|nehme=take|nimm=take|nimmst=take|nehmen=to take|gibt=gives / there is|geben=to give|finde=find / think|findest=find / think|findet=finds|mag=like|magst=like|stehe=stand|steht=stands / suits|stehen=to stand|liegt=lies / is|liegen=to lie / be located|hängt=hangs|sitzen=to sit|setz=sit|schau=look|schaue=look|zeig=show|zeigen=to show|erzähl=tell|hör=listen|hol=get|hole=get / fetch|bring=bring|bringe=bring|probier=try|frag=ask|füll=fill|vergiss=forget|halte=hold|ruf=call|rufe=call|melde=sign|lauf=walk|geh=go|finde=find|erkunde=explore|bau=build|lern=learn|schreib=write|mach=make / do|wasch=wash|bleib=stay|bleibe=stay|bleiben=to stay|warte=wait|klick=click|klicken=to click
tut=does / hurts|tun=to do|weh=sore / hurting|leid=sorry (es tut mir leid)|recht=right (recht haben)|lust=desire (Lust haben = feel like)|sorge=worry|dank=thanks|geschehen=done (gern geschehen = you're welcome)|gleichfalls=likewise|ebenfalls=likewise|genauso=just the same
hallo=hello|tschüss=bye|grüß=greet (Grüß Gott = hello)|gott=God (Grüß Gott = hello)|wiedersehen=seeing again (Auf Wiedersehen = goodbye)|servus=hi / bye (southern)|willkommen=welcome|appetit=appetite (Guten Appetit = enjoy)|besserung=recovery (Gute Besserung = get well)|andermal=another time|moment=moment|okay=okay
tannenau=Tannenau (the island)|greta=Greta (name)|franz=Franz (name)|hilde=Hilde (name)|hildes=Hilde's|gretas=Greta's|lena=Lena (name)|jonas=Jonas (name)|marie=Marie (name)|sepp=Sepp (name)|aylin=Aylin (name)|paul=Paul (name)|mia=Mia (name)|anna=Anna (name)|lukas=Lukas (name)|emma=Emma (name)|max=Max (name)|tom=Tom (name)|sophie=Sophie (name)|felix=Felix (name)|klara=Klara (name)|ben=Ben (name)|jan=Jan (name)|lea=Lea (name)|weber=Weber (surname)|mimi=Mimi (cat's name)|bello=Bello (dog's name)|caleb=Caleb (name)|karl=Karl (name)
freiburg=Freiburg (a city)|titisee=Titisee (a lake town)|hinterzarten=Hinterzarten (a village)|konstanz=Konstanz (a city)|seebrücke=Seebrücke (Lake Bridge)|wien=Vienna|berlin=Berlin|hamburg=Hamburg|köln=Cologne|münchen=Munich|england=England|japan=Japan|spanisch=Spanish|französisch=French|kuckuck=cuckoo|café=café
kirschtorte=cherry cake|schwarzwälder=Black Forest (adj.)|telefonnummer=phone number|lieblingszahl=favourite number|lieblingsfach=favourite subject|fußballverein=football club|zahnschmerzen=toothache|bauchschmerzen=stomach ache|geburtstagsuhr=birthday watch|mitnehmen=take away (zum Mitnehmen)|hunger=hunger|durst=thirst|t=T (as in T-shirt)|shirt=shirt|e=E (as in e-mail)|mail=mail|rad=bike / wheel|w=W|a=A|d=D|n=n|st=st|ge=ge-|be=be|have=have|to=to|dog=dog (English)|thank=thank (English)|you=you (English)
fährfrau=ferry keeper|bäuerin=farmer (woman)|bahnhofsvorsteherin=station master (woman)|marktfrau=market seller|marktstand=market stall|uhrmacher=clockmaker|uhrmacherei=clockmaker's workshop|anlegestelle=landing stage|förster=forester|forsthaus=forester's lodge|arztpraxis=doctor's surgery|bäckerei=bakery|hof=farm / yard|zuhause=home|linde=linden tree|dampfer=steamboat|steg=landing stage / jetty|möwe=gull|ruderboot=rowing boat|laterne=lantern|maibaum=maypole|fass=barrel|briefkasten=mailbox|bahnhofsuhr=station clock|schubkarre=wheelbarrow|apfelbaum=apple tree|schaukel=swing|doktor=doctor
bereit=ready|tick=tick|tack=tock|rein=in (come in)|jede=every|vergeht=passes (time)|gelaunt=in a mood (gut gelaunt = cheerful)|unterricht=lessons / class|angefangen=started|ruhe=quiet|kennenzulernen=to get to know|kennenlernen=to get to know|reden=to talk|gespräch=conversation|stimme=voice / agree|funktioniert=works|hoppla=oops|schiefgegangen=gone wrong|versuchen=to try|versuch=try / attempt|völlig=completely|unbekannt=unknown|samen=seed|keim=sprout|setzling=sapling|blüte=blossom|wächst=grows|maus=mouse
anmelden=sign in|abmelden=sign out|wörterbuch=dictionary|menü=menu|schließen=close|anschauen=look at|stufe=level|ton=sound|mikrofon=microphone|stil=style|tablett=tray|prüfen=check|tipp=tip / hint|anhören=listen to|chatten=to chat|speichern=saving|punkte=points|dinge=things|gefunden=found|stumm=muted|auflegen=hang up|senden=send|untertitel=subtitles|buchstaben=letters|steuerung=controls|laufen=to walk / run|pfeile=arrows|leertaste=space bar|kamera=camera|ziehen=to drag|scrollen=to scroll|zoomen=to zoom|rennen=to run|shift=Shift (key)|halten=to hold|schreibweise=spelling|artikel=article|automatisch=automatic|überspringen=skip|probiers=try it|präsentiert=presents|sapling=Sapling (a name)|kurzer=short|test=test|fangen=start (anfangen)|fängst=start|vorne=the front (von vorne = from the start)|auswahl=choice / option|kapitel=chapter(s)|gesperrt=locked|gratis=free (no charge)|fehler=mistake|bestell=order|bestellen=to order|bestellt=ordered|tun=to do|reparieren=to repair|besonders=especially|fünfzehn=fifteen|zweihundert=two hundred|einundvierzig=forty-one|achtzehn=eighteen|zweiunddreißig=thirty-two|fünfundvierzig=forty-five|dreiundvierzig=forty-three|vierzigunddrei=forty-three (wrong order)|vierunddreißig=thirty-four
dieser=this|diese=this|dieses=this|diesen=this|alle=all|welches=which|jeden=every|jede=every|ganzen=whole|einmal=once|zweimal=twice|nichts=nothing|etwas=something|selbst=self
wiener=Viennese|dabei=with (me)|offen=open|steil=steep|mitte=middle|zentrum=centre|kenne=know|verkauft=sells|trägt=wears|trägst=wear|leder=leather|fällt=falls|launisch=moody|weihnachten=Christmas|laut=according to / loud|bild=picture|läuft=runs|gebrochen=broken|schlägt=beats|knie=knee|starke=strong|spaß=fun|kunst=art|fängt=starts|aufgabe=task|geregnet=rained|fallen=to fall|scheu=shy|schlau=clever|sammelt=collects|nüsse=nuts|giftig=poisonous|hackt=chops|also=so / well|regnen=to rain|schneien=to snow|schlägst=suggest (vorschlagen)|gutes=good|ärgere=get annoyed|ärgert=gets annoyed|ärgern=to annoy|freue=am pleased|freut=pleases|freust=are pleased|freuen=to please|höher=higher|höchsten=highest|helfe=help|helfen=to help|hilf=help|preis=price|politik=politics|sich=oneself|vorstellen=to introduce|unterwegs=on the way|uhrzeit=time (of day)|alltag=everyday life|gesundheit=health|wahl=choice|müssen=must|schläft=sleeps|schlaf=sleep|welche=which|ergänzt=added|fühlst=feel|ausruhen=to rest|ruh=rest|passiert=happened|ende=end|reserviert=reserved|lass=let|werde=will|denke=think|denkst=think|stimme=agree|beispiel=example|nur=only|achtzig=eighty|endlich=finally|reif=ripe|magst=like|siehst=see|sieht=sees|können=can|hole=get / fetch|wohin=where to|gerade=right now|kurz=briefly|halte=hold|sag=say|wollte=wanted|sprichst=speak|letzte=last|welcher=which|gebaut=built|verb=verb|verben=verbs|endung=ending|endungen=endings|bord=board (an Bord = on board)|bushaltestelle=bus stop|nomen=noun(s)|ans=to the|machst=do|willst=want|nachbarn=neighbours|wissen=know / to know|hit=today (dialect)|isch=is (dialect)|schee=nice (dialect)|gell=isn't it? (southern)|ball=ball|werfen=to throw|enkel=grandchildren|fleißig=hard-working|oje=oh dear|blass=pale|eis=ice cream|runtergefallen=fallen down|beruflich=for work|sprache=language|schild=sign|dialog=dialogue|puzzle=puzzle|reihenfolge=order / sequence|gästebuch=guest book|stempel=stamp(s)|zweifel=doubt|ändert=changes|stellen=to ask (a question)|geschlechter=genders|bauen=to build|habst=have (wrong form)|rest=rest|teilen=parts|anweisungen=instructions|bewegung=movement|zukunft=future|meistens=usually|präsens=present tense|infinitiv=infinitive|schickt=sends
hätte=would have (ich hätte gern = I'd like)|spazieren=to stroll (spazieren gehen = go for a walk)|dauert=lasts / takes|bedeutet=means|hin=there (hin und zurück = return)|viertel=quarter|problem=problem|sonst=otherwise / else|fehlt=is missing (was fehlt dir = what's wrong)|beginnt=begins|vorbei=over / past|grammatik=grammar|schmeckt=tastes|verlaufen=got lost (sich verlaufen)|blühen=bloom|vorsicht=careful|berühmt=famous|räume=tidy (aufräumen)|ordnung=order (in Ordnung = all right)|notizen=notes
schicht=shift (at work)|gast=guest|gäste=guests|sachen=things|theke=counter|paar=few (ein paar = a few)|kasse=till / checkout|trinkgeld=tip(s)|profi=pro|puh=phew|geschafft=done it / made it|sofort=right away|lieber=rather (doch lieber = … instead)
`;
