import type { PracticeCharacter, PracticeScenario } from "@/types/practice";

// Live and typed conversations with the people of Tannenau.

export const characters: PracticeCharacter[] = [
  { id: "greta", name: "Greta", description: "Cheerful, chatty ferry keeper of Tannenau who greets every visitor at the landing stage and knows everyone's business." },
  { id: "franz", name: "Franz", description: "Big-hearted baker of Café Kuckuck, proud of his pretzels and his Black Forest cake, and a little dramatic about both." },
  { id: "jonas", name: "Jonas", description: "Precise, gentle clockmaker who loves numbers, cuckoo clocks and being exactly on time." },
  { id: "hilde", name: "Hilde", description: "Warm old farmer in a Bollenhut who calls everyone 'mein Kind', tells stories about the old days and loves making plans." },
  { id: "lena", name: "Lena", description: "Efficient, friendly station master who knows every timetable by heart and teases travellers who run late." },
  { id: "marie", name: "Marie", description: "Lively market seller with fruit, vegetables and scarves, who haggles for fun and compliments everyone's style." },
  { id: "sepp", name: "Sepp", description: "Quiet, outdoorsy forester who knows every animal, trail and weather sign in the Black Forest." },
  { id: "aylin", name: "Aylin", description: "Calm, kind village doctor with a dry sense of humour who asks how you really feel." },
  { id: "paul", name: "Paul", description: "Patient village teacher who loves big questions, good arguments and asking what you think." },
];

export const scenarios: PracticeScenario[] = [
  {
    id: "meet-greta",
    languageCode: "de",
    characterId: "greta",
    title: "Meet Greta",
    setting: "You have just stepped off the steamboat onto the landing stage of Tannenau, a village on an island in a Black Forest lake.",
    learnerRole: "Introduce yourself and get to know Greta.",
    characterRole: "The friendly ferry keeper meeting you for the first time.",
    goal: "Exchange names, say where you're from and finish a short, natural introduction.",
    openingLine: "Hallo! Ich heiße Greta. Wie heißt du?",
    openingEnglish: "Hi! My name is Greta. What's your name?",
    style: "roleplay",
    requiredConceptSlugs: ["hallo", "ich-heisse"],
    optionalConceptSlugs: ["freut-mich", "ich-komme-aus", "ich-wohne-in", "wie-gehts", "und-dir", "tschuess"],
    minimumEncountered: 0,
    minimumTurns: 3,
    maximumTurns: 5,
    starterHints: [
      { target: "Hallo, ich heiße …", english: "Hi, my name is …" },
      { target: "Ich komme aus …", english: "I'm from …" },
    ],
    fallbackReplies: [
      { target: "Freut mich! Woher kommst du?", english: "Nice to meet you! Where are you from?" },
      { target: "Toll! Und wie gefällt dir Tannenau?", english: "Great! And how do you like Tannenau?" },
      { target: "Schön, dass du hier bist. Bis bald!", english: "Nice that you're here. See you soon!" },
    ],
  },
  {
    id: "kaffee-und-kuchen",
    languageCode: "de",
    characterId: "franz",
    title: "Coffee and cake at Café Kuckuck",
    setting: "You step up to the counter of Café Kuckuck, the bakery and café on the market square.",
    learnerRole: "Choose something and order it naturally.",
    characterRole: "Franz, the baker, taking your order and chatting while he works.",
    goal: "Order a drink and something to eat, answer one follow-up question and pay.",
    openingLine: "Grüß Gott! Was darf's sein?",
    openingEnglish: "Hello! What can I get you?",
    style: "roleplay",
    requiredConceptSlugs: ["ich-haette-gern", "kaffee", "danke"],
    optionalConceptSlugs: ["tee", "brezel", "kuchen", "mit-milch", "zahlen-bitte", "fuer-hier", "zum-mitnehmen"],
    minimumEncountered: 2,
    minimumTurns: 3,
    maximumTurns: 6,
    starterHints: [
      { target: "Ich hätte gern …", english: "I'd like …" },
      { target: "… mit Milch, bitte.", english: "… with milk, please." },
    ],
    fallbackReplies: [
      { target: "Gute Wahl! Möchtest du auch eine Brezel?", english: "Good choice! Would you like a pretzel too?" },
      { target: "Für hier oder zum Mitnehmen?", english: "For here or to take away?" },
      { target: "Bitte schön! Das macht vier Euro achtzig.", english: "Here you go! That's four euros eighty." },
    ],
  },
  {
    id: "beim-uhrmacher",
    languageCode: "de",
    characterId: "jonas",
    title: "At the clockmaker's",
    setting: "You bring a broken watch to Jonas's workshop, full of ticking cuckoo clocks.",
    learnerRole: "Explain what you need and agree on a day to collect the watch.",
    characterRole: "Jonas, the clockmaker, who asks questions and suggests times.",
    goal: "Say what you need, understand a price and agree on a day and time.",
    openingLine: "Hallo! Was kann ich für dich tun?",
    openingEnglish: "Hi! What can I do for you?",
    style: "roleplay",
    requiredConceptSlugs: ["die-uhr", "kaputt", "wann"],
    optionalConceptSlugs: ["passt-es", "das-passt", "es-ist-uhr", "um", "kostet", "montag", "freitag"],
    minimumEncountered: 2,
    minimumTurns: 3,
    maximumTurns: 6,
    starterHints: [
      { target: "Meine Uhr ist kaputt.", english: "My watch is broken." },
      { target: "Passt es dir am …?", english: "Does … suit you?" },
    ],
    fallbackReplies: [
      { target: "Zeig mal. Ah, das kann ich reparieren.", english: "Let me see. Ah, I can repair that." },
      { target: "Kannst du am Freitag um drei Uhr kommen?", english: "Can you come on Friday at three o'clock?" },
      { target: "Gut, dann bis Freitag!", english: "Good, see you on Friday then!" },
    ],
  },
  {
    id: "auf-dem-hof",
    languageCode: "de",
    characterId: "hilde",
    title: "On Hilde's farm",
    setting: "Hilde invites you to sit on the bench in front of her old farmhouse on the hill.",
    learnerRole: "Talk about your family and your week.",
    characterRole: "Hilde, the farmer, curious about your life and full of stories.",
    goal: "Tell Hilde about your family, something you did recently and a plan for the weekend.",
    openingLine: "Setz dich, mein Kind! Erzähl mal, hast du Familie?",
    openingEnglish: "Sit down, my dear! Tell me, do you have family?",
    style: "open_question",
    requiredConceptSlugs: ["ich-habe", "die-familie"],
    optionalConceptSlugs: ["der-bruder", "die-schwester", "die-eltern", "perfekt-habe-gemacht", "wollen-wir", "am-wochenende"],
    minimumEncountered: 2,
    minimumTurns: 3,
    maximumTurns: 6,
    starterHints: [
      { target: "Ich habe …", english: "I have …" },
      { target: "Am Wochenende …", english: "At the weekend …" },
    ],
    fallbackReplies: [
      { target: "Wie schön! Und was hast du gestern gemacht?", english: "How lovely! And what did you do yesterday?" },
      { target: "Und am Wochenende? Hast du schon Pläne?", english: "And at the weekend? Do you have plans yet?" },
      { target: "Dann komm doch zum Kaffee vorbei!", english: "Then come round for coffee!" },
    ],
  },
  {
    id: "am-bahnhof",
    languageCode: "de",
    characterId: "lena",
    title: "At the station",
    setting: "You are at Tannenau's little station, about to take the train over the lake to the mountains.",
    learnerRole: "Buy a ticket, check the train and find out when it leaves.",
    characterRole: "Lena, the station master helping travellers.",
    goal: "Ask for a ticket, check the train goes where you need and confirm the platform or time.",
    openingLine: "Guten Tag! Wohin möchtest du fahren?",
    openingEnglish: "Good day! Where would you like to go?",
    style: "roleplay",
    requiredConceptSlugs: ["die-fahrkarte", "faehrt-dieser-zug", "wann-faehrt"],
    optionalConceptSlugs: ["hin-und-zurueck", "einfach", "das-gleis", "umsteigen", "ich-muss-aussteigen"],
    minimumEncountered: 2,
    minimumTurns: 4,
    maximumTurns: 6,
    starterHints: [
      { target: "Eine Fahrkarte nach …, bitte.", english: "A ticket to …, please." },
      { target: "Wann fährt der Zug?", english: "When does the train leave?" },
    ],
    fallbackReplies: [
      { target: "Einfach oder hin und zurück?", english: "One way or return?" },
      { target: "Der Zug fährt um zehn Uhr fünfzehn von Gleis zwei.", english: "The train leaves at ten fifteen from platform two." },
      { target: "Gute Reise!", english: "Have a good trip!" },
    ],
  },
  {
    id: "auf-dem-markt",
    languageCode: "de",
    characterId: "marie",
    title: "At the market",
    setting: "It's market day on the square and Marie's stall is full of fruit, vegetables and colourful scarves.",
    learnerRole: "Buy a few things, ask about prices and pay.",
    characterRole: "Marie, the market seller, who loves to chat and recommend things.",
    goal: "Ask for two things, ask how much they cost and finish the purchase.",
    openingLine: "Guten Morgen! Was darf's sein?",
    openingEnglish: "Good morning! What can I get you?",
    style: "roleplay",
    requiredConceptSlugs: ["ich-nehme", "was-kostet-das"],
    optionalConceptSlugs: ["das-kilo", "der-apfel", "die-kirsche", "das-ist-alles", "mit-karte", "gefaellt-mir"],
    minimumEncountered: 2,
    minimumTurns: 3,
    maximumTurns: 6,
    starterHints: [
      { target: "Ich nehme …", english: "I'll take …" },
      { target: "Was kostet das?", english: "How much is that?" },
    ],
    fallbackReplies: [
      { target: "Die Kirschen sind heute besonders süß!", english: "The cherries are especially sweet today!" },
      { target: "Sonst noch etwas?", english: "Anything else?" },
      { target: "Das macht sechs Euro, bitte.", english: "That's six euros, please." },
    ],
  },
  {
    id: "im-wald",
    languageCode: "de",
    characterId: "sepp",
    title: "In the forest",
    setting: "Sepp meets you at the edge of the fir forest behind his lodge.",
    learnerRole: "Talk about the weather, what you like doing and plan a walk.",
    characterRole: "Sepp, the forester, who loves the forest and knows every trail.",
    goal: "Say what the weather is like, share a hobby and agree to go for a walk.",
    openingLine: "Servus! Schönes Wetter heute, oder?",
    openingEnglish: "Hi! Nice weather today, isn't it?",
    style: "open_question",
    requiredConceptSlugs: ["das-wetter", "wandern"],
    optionalConceptSlugs: ["es-regnet", "sonnig", "ich-spiele-gern", "was-machst-du-gern", "der-wald", "hast-du-lust"],
    minimumEncountered: 2,
    minimumTurns: 3,
    maximumTurns: 6,
    starterHints: [
      { target: "Es ist …", english: "It's …" },
      { target: "Ich … gern.", english: "I like …" },
    ],
    fallbackReplies: [
      { target: "Was machst du gern in deiner Freizeit?", english: "What do you like doing in your free time?" },
      { target: "Wollen wir zum See wandern?", english: "Shall we hike to the lake?" },
      { target: "Super, dann gehen wir los!", english: "Great, then let's go!" },
    ],
  },
  {
    id: "beim-arzt",
    languageCode: "de",
    characterId: "aylin",
    title: "At the doctor's",
    setting: "You're not feeling well and visit Aylin's surgery on the market square.",
    learnerRole: "Explain what hurts and how you feel, and understand the advice.",
    characterRole: "Aylin, the village doctor, calm and kind.",
    goal: "Say what hurts, answer one question about how long, and understand what to do.",
    openingLine: "Guten Tag! Was fehlt dir denn?",
    openingEnglish: "Hello! What seems to be the problem?",
    style: "roleplay",
    requiredConceptSlugs: ["tut-weh", "krank"],
    optionalConceptSlugs: ["der-kopf", "der-bauch", "das-fieber", "mir-geht-es-schlecht", "du-musst", "gute-besserung"],
    minimumEncountered: 2,
    minimumTurns: 3,
    maximumTurns: 6,
    starterHints: [
      { target: "Mein … tut weh.", english: "My … hurts." },
      { target: "Ich habe Fieber.", english: "I have a fever." },
    ],
    fallbackReplies: [
      { target: "Seit wann hast du die Schmerzen?", english: "How long have you had the pain?" },
      { target: "Du musst viel trinken und im Bett bleiben.", english: "You have to drink a lot and stay in bed." },
      { target: "Gute Besserung!", english: "Get well soon!" },
    ],
  },
  {
    id: "in-der-schule",
    languageCode: "de",
    characterId: "paul",
    title: "A chat with the teacher",
    setting: "After class, Paul sits with you on the school steps and asks what you think about life on the island.",
    learnerRole: "Say what you do and give your opinion with a reason.",
    characterRole: "Paul, the teacher, who loves to hear what people think and why.",
    goal: "Say what you do for a living, give an opinion and a reason with weil.",
    openingLine: "Na, wie findest du Tannenau?",
    openingEnglish: "So, what do you think of Tannenau?",
    style: "open_question",
    requiredConceptSlugs: ["ich-finde", "weil"],
    optionalConceptSlugs: ["ich-bin-von-beruf", "das-stimmt", "besser", "meiner-meinung-nach", "dass"],
    minimumEncountered: 2,
    minimumTurns: 3,
    maximumTurns: 6,
    starterHints: [
      { target: "Ich finde …", english: "I think …" },
      { target: "…, weil …", english: "…, because …" },
    ],
    fallbackReplies: [
      { target: "Interessant! Und was bist du von Beruf?", english: "Interesting! And what do you do for a living?" },
      { target: "Warum findest du das?", english: "Why do you think that?" },
      { target: "Da hast du recht. Bis morgen!", english: "You're right about that. See you tomorrow!" },
    ],
  },
];
