import type { Line } from "@/lib/game/line";
import type { UiText } from "@/lib/game/ui-text";

// Every piece of interface copy is German first; English only appears on hover.
export const ui: UiText = {
  title: { t: "Tannenau", en: "Fir Meadow" },
  tagline: { t: "Lerne Deutsch in einem Dorf im Schwarzwald.", en: "Learn German in a Black Forest village." },
  play: { t: "Spielen", en: "Play" },
  continue: { t: "Weiter", en: "Continue" },
  signIn: { t: "Anmelden und spielen", en: "Sign in and play" },
  loading: { t: "Das Boot kommt …", en: "The boat is coming …" },
  level: { t: "Stufe", en: "Level" },
  words: { t: "Wörter", en: "words" },
  dictionary: { t: "Wörterbuch", en: "Dictionary" },
  soundOn: { t: "Ton an", en: "Sound on" },
  soundOff: { t: "Ton aus", en: "Sound off" },
  menu: { t: "Menü", en: "Menu" },
  signOut: { t: "Abmelden", en: "Sign out" },
  close: { t: "Schließen", en: "Close" },
  back: { t: "Zurück", en: "Back" },
  home: { t: "Zu allen Inseln", en: "To all islands" },
  walkHint: { t: "Lauf mit W A S D oder klick auf den Boden.", en: "Walk with W A S D, or click on the ground." },
  hoverHint: { t: "Halte die Maus über ein Wort, dann siehst du, was es bedeutet.", en: "Hold the mouse over a word to see what it means." },
  talkTo: (name: string): Line => ({ t: `Mit ${name} sprechen`, en: `Talk to ${name}` }),
  lookAt: { t: "Anschauen", en: "Look" },
  goalTalk: (name: string, place: Line): Line => ({
    t: `Finde ${name}: ${place.t}`,
    en: `Find ${name} at ${place.en.toLocaleLowerCase("en")}`,
  }),
  goalLearnMore: (name: string): Line => ({ t: `Lerne mehr von ${name}`, en: `Learn more from ${name}` }),
  goalMeetFirst: { t: "Geh zu Greta an der Anlegestelle", en: "Walk to Greta at the landing stage" },
  goalDone: { t: "Erkunde die Insel und finde neue Wörter", en: "Explore the island and find new words" },
  newWord: { t: "Neues Wort!", en: "New word!" },
  levelUp: { t: "Neue Stufe!", en: "New level!" },
  treeGrows: { t: "Die Linde auf dem Marktplatz wächst!", en: "The linden tree on the market square is growing!" },
  newFriend: (name: string): Line => ({ t: `${name} möchte dich kennenlernen!`, en: `${name} wants to meet you!` }),
  welcomeBack: (name: string): Line => ({ t: `Willkommen zurück, ${name}!`, en: `Welcome back, ${name}!` }),
  wordGrows: (stage: Line): Line => ({ t: `Dein Wort wächst: ${stage.t}!`, en: `Your word grows: ${stage.en}!` }),
  startWith: (name: string): Line => ({ t: `Du fängst bei ${name} an!`, en: `You start with ${name}!` }),
  callAndTalk: (name: string): Line => ({ t: `Ruf ${name} an und sprich Deutsch!`, en: `Call ${name} and talk in German!` }),
  next: { t: "Weiter", en: "Next" },
  check: { t: "Prüfen", en: "Check" },
  dontKnow: { t: "Ich weiß es nicht", en: "I don't know" },
  hint: { t: "Tipp", en: "Hint" },
  listen: { t: "Anhören", en: "Listen" },
  listenAgain: { t: "Noch mal anhören", en: "Listen again" },
  slowly: { t: "Langsam", en: "Slowly" },
  sayIt: { t: "Sag es", en: "Say it" },
  listening: { t: "Ich höre zu …", en: "I'm listening …" },
  writeTarget: { t: "Schreib auf Deutsch …", en: "Write in German …" },
  sayInTarget: { t: "Sag es auf Deutsch", en: "Say it in German" },
  whatDoesItMean: { t: "Was bedeutet das?", en: "What does it mean?" },
  whatDidYouHear: { t: "Was hast du gehört?", en: "What did you hear?" },
  buildSentence: { t: "Bau den Satz", en: "Build the sentence" },
  newPhrase: { t: "Etwas Neues", en: "Something new" },
  repeatAfterMe: { t: "Sprich mir nach!", en: "Repeat after me!" },
  youSaid: { t: "Du hast gesagt", en: "You said" },
  heardYou: { t: "Ich habe gehört", en: "I heard" },
  bye: { t: "Tschüss!", en: "Bye!" },
  again: { t: "Noch einmal!", en: "One more time!" },
  talkForReal: { t: "Richtig sprechen", en: "Talk for real (voice)" },
  chatTyping: { t: "Chatten", en: "Chat (typing)" },
  yourName: { t: "Schreib deinen Namen …", en: "Write your name …" },
  myNameIs: { t: "Ich heiße …", en: "My name is …" },
  saving: { t: "Speichern …", en: "Saving …" },
  xpGained: { t: "Punkte", en: "points" },
  correct: { t: "richtig", en: "correct" },
  phrases: { t: "Sätze", en: "Phrases" },
  grammar: { t: "Grammatik", en: "Grammar" },
  littleGrammar: { t: "Kleine Grammatik", en: "Little grammar" },
  newGrammar: { t: "Neue Grammatik", en: "New grammar tip" },
  things: { t: "Dinge auf der Insel", en: "Things on the island" },
  notFound: { t: "Noch nicht gefunden", en: "Not found yet" },
  notMet: { t: "Noch nicht gelernt", en: "Not learned yet" },
  connecting: { t: "Ich rufe an …", en: "Calling …" },
  liveNow: { t: "Sprich einfach! Ich höre zu.", en: "Just talk! I'm listening." },
  mute: { t: "Stumm", en: "Mute" },
  unmute: { t: "Mikrofon an", en: "Microphone on" },
  endCall: { t: "Auflegen", en: "Hang up" },
  liveOver: { t: "Das Gespräch ist vorbei.", en: "The conversation is over." },
  reflect: { t: "Was habe ich gelernt?", en: "What did I learn?" },
  typeReply: { t: "Antworte auf Deutsch …", en: "Answer in German …" },
  send: { t: "Senden", en: "Send" },
  needsAccount: { t: "Melde dich an, um richtig zu sprechen.", en: "Sign in to talk for real." },
  liveUnavailable: { t: "Die Stimme funktioniert gerade nicht. Wir können chatten!", en: "Voice isn't working right now. We can chat instead!" },
  notReadyToTalk: { t: "Lern erst noch ein bisschen, dann können wir reden!", en: "Learn a bit more first, then we can talk!" },
  error: { t: "Hoppla! Etwas ist schiefgegangen.", en: "Oops! Something went wrong." },
  tryAgain: { t: "Noch mal versuchen", en: "Try again" },
  captions: { t: "Untertitel", en: "Subtitles" },
  mic: { t: "Mikrofon", en: "Microphone" },
  youLabel: { t: "Du", en: "You" },
  stageLabel: { t: "Wächst", en: "Growing" },
  letters: { t: "Deutsche Buchstaben", en: "German letters" },
  controls: { t: "Steuerung", en: "Controls" },
  controlsMove: { t: "Laufen: W A S D / Pfeile / Klick", en: "Walk: W A S D / arrows / click" },
  controlsTalk: { t: "Sprechen: E / Leertaste", en: "Talk: E / space" },
  controlsCamera: { t: "Kamera: mit der Maus ziehen, scrollen zum Zoomen", en: "Camera: drag with the mouse, scroll to zoom" },
  controlsRun: { t: "Rennen: Shift halten", en: "Run: hold Shift" },
  spelling: { t: "Schau auf die Schreibweise!", en: "Look at the spelling!" },
  article: { t: "Vergiss den Artikel nicht: der, die oder das!", en: "Don't forget the article: der, die or das!" },
  yourStyle: { t: "Dein Stil", en: "Your style" },
  style: { t: "Stil", en: "Style" },
  englishAuto: { t: "Englisch: automatisch", en: "English subtitles: automatic" },
  englishOn: { t: "Englisch: an", en: "English subtitles: on" },
  englishOff: { t: "Englisch: aus", en: "English subtitles: off" },
  skip: { t: "Überspringen", en: "Skip" },
  tryIt: { t: "Probier's!", en: "Try it!" },
  nowYouCanSay: { t: "Jetzt kannst du sagen …", en: "Now you can say …" },
  letsGo: { t: "Los geht's!", en: "Let's go!" },
  hide: { t: "Ausblenden", en: "Hide" },
  show: { t: "Zeigen", en: "Show" },
  presents: { t: "Sapling präsentiert", en: "Sapling presents" },
  welcomeTitle: { t: "Willkommen in Tannenau", en: "Welcome to Tannenau" },
  learnedBefore: { t: "Hast du schon mal Deutsch gelernt?", en: "Have you learned German before?" },
  quickCheck: { t: "Kurzer Test", en: "Quick check" },
  done: { t: "Fertig!", en: "Done!" },
  startFromTop: { t: "Wir fangen von vorne an!", en: "We'll start at the beginning!" },
  replyIfYouLike: { t: "Antworte, wenn du willst", en: "Reply if you like" },
  askForBill: { t: "Frag nach der Rechnung!", en: "Ask for the bill!" },
  fillTray: { t: "Füll das Tablett!", en: "Fill the tray!" },
  ready: { t: "Fertig!", en: "Done!" },
  option: { t: "Auswahl", en: "Option" },
  yourTray: { t: "Dein Tablett", en: "Your tray" },
  flowers: { t: "Blumen", en: "flowers" },
  notes: { t: "Notizen", en: "Notes" },
  conversation: { t: "Das Gespräch", en: "The conversation" },
  situation: { t: "Was passiert?", en: "What's happening?" },
  units: { t: "Kapitel", en: "Chapters" },
  locked: { t: "Gesperrt", en: "Locked" },
};
