import type { Line } from "@/lib/game/line";
import type { Villager } from "@/lib/game/villagers";

// The people of Tannenau. Each teaches a few units of the German course.

export const villagers: Villager[] = [
  {
    id: "greta",
    name: "Greta",
    role: { t: "Fährfrau", en: "ferry keeper" },
    place: { t: "Die Anlegestelle", en: "The landing stage" },
    scenarioId: "meet-greta",
    round: "scene",
    stage: "guestbook",
    position: [3.4, 22.4],
    facing: Math.PI * 0.9,
    look: { skin: "#f3c9a8", hair: "#e9c46a", hairStyle: "braid", shirt: "#2f6fb5", pants: "#27364f", accent: "#e76f51" },
    voicePitch: 1.2,
    voice: "Kore",
    context: "the landing stage of Tannenau, a small island village in a Black Forest lake (Greta runs the ferry)",
    greetings: [
      { t: "Hallo! Schön, dich zu sehen!", en: "Hi! Nice to see you!" },
      { t: "Grüß dich! Bereit für ein bisschen Deutsch?", en: "Hi there! Ready for a bit of German?" },
      { t: "Grüß Gott! Was für ein schöner Tag!", en: "Hello! What a lovely day!" },
    ],
    chatter: [
      { t: "Das Boot kommt um drei Uhr.", en: "The boat comes at three o'clock." },
      { t: "Schau mal, ein Vogel!", en: "Look, a bird!" },
      { t: "Hallo, hallo!", en: "Hello, hello!" },
    ],
    locked: { t: "Hallo!", en: "Hi!" },
    teach: { t: "Bring mir etwas bei!", en: "Teach me something!" },
    talk: { t: "Können wir reden?", en: "Can we talk?" },
    goodbye: [
      { t: "Bis bald!", en: "See you soon!" },
      { t: "Mach's gut!", en: "Take care!" },
    ],
  },
  {
    id: "franz",
    name: "Franz",
    role: { t: "Bäcker", en: "baker" },
    place: { t: "Café Kuckuck", en: "Cuckoo Café" },
    scenarioId: "kaffee-und-kuchen",
    round: "cafe",
    stage: "guestbook",
    position: [-10.4, 7.6],
    facing: Math.PI * 0.35,
    look: { skin: "#eab896", hair: "#5b3a24", hairStyle: "short", shirt: "#f4efe6", pants: "#4a3a2e", accent: "#b5541c", hat: "chef", beard: true, apron: "#b5541c", scale: 1.08 },
    voicePitch: 0.8,
    voice: "Algieba",
    context: "Café Kuckuck, the bakery and café of Tannenau, run by Franz who bakes pretzels and Black Forest cake",
    greetings: [
      { t: "Willkommen im Café Kuckuck!", en: "Welcome to Café Kuckuck!" },
      { t: "Riechst du das? Frische Brezeln!", en: "Can you smell that? Fresh pretzels!" },
      { t: "Grüß Gott! Zeit für Kaffee und Kuchen?", en: "Hello! Time for coffee and cake?" },
    ],
    chatter: [
      { t: "Brezeln! Frische Brezeln!", en: "Pretzels! Fresh pretzels!" },
      { t: "Kaffee ist das Leben.", en: "Coffee is life." },
      { t: "Der Kuchen ist noch warm.", en: "The cake is still warm." },
    ],
    locked: { t: "Tut mir leid, wir haben noch zu. Sprich zuerst mit Greta an der Anlegestelle!", en: "Sorry, we're still closed. Talk to Greta at the landing stage first!" },
    teach: { t: "Was gibt es heute?", en: "What is there today?" },
    talk: { t: "Ich möchte bestellen!", en: "I'd like to order!" },
    goodbye: [
      { t: "Bis zum nächsten Mal!", en: "Until next time!" },
      { t: "Tschüss, einen schönen Tag noch!", en: "Bye, have a nice day!" },
    ],
  },
  {
    id: "jonas",
    name: "Jonas",
    role: { t: "Uhrmacher", en: "clockmaker" },
    place: { t: "Die Uhrmacherei", en: "The clockmaker's workshop" },
    scenarioId: "beim-uhrmacher",
    round: "scene",
    stage: "stamps",
    position: [9.4, 13.2],
    facing: -Math.PI * 0.7,
    look: { skin: "#c68a62", hair: "#2b1d14", hairStyle: "short", shirt: "#3f7d4f", pants: "#2c3e50", accent: "#6b3f24", hat: "cap" },
    voicePitch: 1.05,
    voice: "Puck",
    context: "the clockmaker's workshop in Tannenau, full of cuckoo clocks (Jonas repairs clocks and loves numbers)",
    greetings: [
      { t: "Tick, tack! Hallo!", en: "Tick, tock! Hi!" },
      { t: "Komm rein, die Kuckucksuhr ist fast fertig.", en: "Come in, the cuckoo clock is almost finished." },
      { t: "Hallo! Weißt du, wie spät es ist?", en: "Hi! Do you know what time it is?" },
    ],
    chatter: [
      { t: "Kuckuck! Kuckuck!", en: "Cuckoo! Cuckoo!" },
      { t: "Noch eine Minute …", en: "One more minute …" },
      { t: "Jede Uhr hat ihre Zeit.", en: "Every clock has its time." },
    ],
    locked: { t: "Ich habe gerade keine Zeit. Komm später wieder!", en: "I don't have time right now. Come back later!" },
    teach: { t: "Zeig mir deine Uhren!", en: "Show me your clocks!" },
    talk: { t: "Hast du kurz Zeit?", en: "Do you have a moment?" },
    goodbye: [
      { t: "Bis später!", en: "See you later!" },
      { t: "Die Zeit vergeht so schnell!", en: "Time flies so fast!" },
    ],
  },
  {
    id: "hilde",
    name: "Hilde",
    role: { t: "Bäuerin", en: "farmer" },
    place: { t: "Der Hof am Berg", en: "The farm on the hill" },
    scenarioId: "auf-dem-hof",
    round: "scene",
    stage: "garden",
    position: [-3.2, -15.2],
    facing: Math.PI * 0.15,
    look: { skin: "#f0c4a4", hair: "#e6e6e6", hairStyle: "bun", shirt: "#1f2a3a", pants: "#2c2a3d", accent: "#d42a2a", hat: "bollenhut", apron: "#f6f1e7", scale: 0.95 },
    voicePitch: 0.95,
    voice: "Sulafat",
    context: "Hilde's old Black Forest farmhouse on the hill of Tannenau, with cows, cherries and a vegetable garden",
    greetings: [
      { t: "Na, grüß dich, mein Kind!", en: "Well, hello there, my dear!" },
      { t: "Die Kühe sind heute gut gelaunt.", en: "The cows are in a good mood today." },
      { t: "Setz dich, setz dich!", en: "Sit down, sit down!" },
    ],
    chatter: [
      { t: "Was für schöne Blumen!", en: "What lovely flowers!" },
      { t: "Die Sonne ist heute warm.", en: "The sun is warm today." },
      { t: "Die Kirschen sind reif.", en: "The cherries are ripe." },
    ],
    locked: { t: "Grüß dich! Komm wieder, wenn du ein bisschen mehr Deutsch kannst.", en: "Hello! Come back when you know a bit more German." },
    teach: { t: "Erzähl mir von deinem Tag!", en: "Tell me about your day!" },
    talk: { t: "Wollen wir etwas machen?", en: "Shall we do something?" },
    goodbye: [
      { t: "Tschüss, mein Kind!", en: "Bye, my dear!" },
      { t: "Komm bald wieder!", en: "Come back soon!" },
    ],
  },
  {
    id: "lena",
    name: "Lena",
    role: { t: "Bahnhofsvorsteherin", en: "station master" },
    place: { t: "Der Bahnhof", en: "The station" },
    scenarioId: "am-bahnhof",
    round: "scene",
    stage: "journey",
    position: [14.2, 0.4],
    facing: -Math.PI * 0.4,
    look: { skin: "#8d5a3b", hair: "#1f1a17", hairStyle: "bob", shirt: "#8b1e2d", pants: "#1b2a3a", accent: "#f2c230", hat: "conductor" },
    voicePitch: 1.1,
    voice: "Despina",
    context: "the little railway station of Tannenau, where the train crosses the lake to the mountains (Lena is the station master)",
    greetings: [
      { t: "Guten Tag! Der Zug ist heute pünktlich.", en: "Good day! The train is on time today." },
      { t: "Hallo! Wohin fährst du?", en: "Hi! Where are you going?" },
      { t: "Willkommen am Bahnhof!", en: "Welcome to the station!" },
    ],
    chatter: [
      { t: "Der Zug fährt gleich ab!", en: "The train is leaving soon!" },
      { t: "Hast du eine Fahrkarte?", en: "Do you have a ticket?" },
      { t: "Gleis zwei, bitte!", en: "Platform two, please!" },
    ],
    locked: { t: "Der Zug fährt noch nicht. Warst du schon im Café?", en: "The train isn't running yet. Have you been to the café?" },
    teach: { t: "Hilf mir beim Reisen!", en: "Help me travel!" },
    talk: { t: "Ich brauche Hilfe!", en: "I need help!" },
    goodbye: [
      { t: "Gute Reise!", en: "Have a good trip!" },
      { t: "Bis zum nächsten Zug!", en: "See you at the next train!" },
    ],
  },
  {
    id: "marie",
    name: "Marie",
    role: { t: "Marktfrau", en: "market seller" },
    place: { t: "Der Marktstand", en: "The market stall" },
    scenarioId: "auf-dem-markt",
    round: "scene",
    stage: "stamps",
    position: [4.2, 8.8],
    facing: -Math.PI * 0.2,
    look: { skin: "#f6d7c0", hair: "#b5542c", hairStyle: "bun", shirt: "#f7c948", pants: "#3d3d3d", accent: "#c0392b", apron: "#6fae4f" },
    voicePitch: 1.15,
    voice: "Callirrhoe",
    context: "the fruit, vegetable and clothes stall on the market square of Tannenau (Marie sells everything and loves to chat)",
    greetings: [
      { t: "Hallo! Frisches Obst und Gemüse!", en: "Hi! Fresh fruit and vegetables!" },
      { t: "Guten Morgen! Was darf's sein?", en: "Good morning! What can I get you?" },
      { t: "Schau mal, die Äpfel sind heute super!", en: "Look, the apples are great today!" },
    ],
    chatter: [
      { t: "Äpfel, Birnen, Kirschen!", en: "Apples, pears, cherries!" },
      { t: "Alles frisch vom Hof!", en: "Everything fresh from the farm!" },
      { t: "Heute im Angebot!", en: "On offer today!" },
    ],
    locked: { t: "Der Markt ist heute zu. Komm später wieder!", en: "The market is closed today. Come back later!" },
    teach: { t: "Was kostet das?", en: "How much is that?" },
    talk: { t: "Ich möchte einkaufen!", en: "I'd like to go shopping!" },
    goodbye: [
      { t: "Danke schön, tschüss!", en: "Thank you, bye!" },
      { t: "Bis nächste Woche!", en: "See you next week!" },
    ],
  },
  {
    id: "sepp",
    name: "Sepp",
    role: { t: "Förster", en: "forester" },
    place: { t: "Das Forsthaus", en: "The forester's lodge" },
    scenarioId: "im-wald",
    round: "scene",
    stage: "stamps",
    position: [-19.2, -3.4],
    facing: Math.PI * 0.6,
    look: { skin: "#e0a986", hair: "#6b4a2f", hairStyle: "short", shirt: "#5f7f3a", pants: "#4a3a2e", accent: "#3f5a2a", hat: "cap", beard: true, scale: 1.05 },
    voicePitch: 0.75,
    voice: "Iapetus",
    context: "the forester's lodge at the edge of the fir forest on Tannenau (Sepp looks after the forest, the animals and the hiking trails)",
    greetings: [
      { t: "Servus! Heute ist ein guter Tag zum Wandern.", en: "Hi! Today is a good day for hiking." },
      { t: "Hallo! Hörst du den Kuckuck im Wald?", en: "Hi! Can you hear the cuckoo in the forest?" },
      { t: "Grüß Gott! Der Wald ist heute so still.", en: "Hello! The forest is so quiet today." },
    ],
    chatter: [
      { t: "Der Wald ist mein Zuhause.", en: "The forest is my home." },
      { t: "Da drüben ist ein Reh!", en: "There's a deer over there!" },
      { t: "Riechst du die Tannen?", en: "Can you smell the firs?" },
    ],
    locked: { t: "Ich muss gleich in den Wald. Komm später wieder!", en: "I have to go into the forest now. Come back later!" },
    teach: { t: "Zeig mir den Wald!", en: "Show me the forest!" },
    talk: { t: "Gehen wir wandern?", en: "Shall we go hiking?" },
    goodbye: [
      { t: "Pass auf dich auf!", en: "Take care of yourself!" },
      { t: "Bis bald im Wald!", en: "See you soon in the forest!" },
    ],
  },
  {
    id: "aylin",
    name: "Aylin",
    role: { t: "Ärztin", en: "doctor" },
    place: { t: "Die Arztpraxis", en: "The doctor's surgery" },
    scenarioId: "beim-arzt",
    round: "scene",
    stage: "stamps",
    position: [-9.6, 14.6],
    facing: Math.PI * 0.8,
    look: { skin: "#d9a07a", hair: "#241a14", hairStyle: "bob", shirt: "#ffffff", pants: "#2f4f6f", accent: "#2f8f8f" },
    voicePitch: 1.1,
    voice: "Laomedeia",
    context: "the doctor's surgery in Tannenau (Aylin is the village doctor, calm, kind and a little funny)",
    greetings: [
      { t: "Hallo! Wie geht es dir heute?", en: "Hi! How are you today?" },
      { t: "Guten Tag! Alles in Ordnung?", en: "Good day! Is everything all right?" },
      { t: "Schön, dich zu sehen! Bist du gesund?", en: "Nice to see you! Are you well?" },
    ],
    chatter: [
      { t: "Viel Wasser trinken!", en: "Drink lots of water!" },
      { t: "Ein Apfel am Tag …", en: "An apple a day …" },
      { t: "Gute Besserung!", en: "Get well soon!" },
    ],
    locked: { t: "Die Praxis ist noch geschlossen. Bis später!", en: "The surgery is still closed. See you later!" },
    teach: { t: "Hilf mir, Frau Doktor!", en: "Help me, doctor!" },
    talk: { t: "Kann ich kurz mit dir reden?", en: "Can I talk to you for a moment?" },
    goodbye: [
      { t: "Gute Besserung!", en: "Get well soon!" },
      { t: "Pass auf dich auf!", en: "Take care of yourself!" },
    ],
  },
  {
    id: "paul",
    name: "Paul",
    role: { t: "Lehrer", en: "teacher" },
    place: { t: "Die Schule", en: "The school" },
    scenarioId: "in-der-schule",
    round: "scene",
    stage: "stamps",
    position: [15.2, -14.2],
    facing: -Math.PI * 0.2,
    look: { skin: "#f1c7a5", hair: "#8a6a44", hairStyle: "short", shirt: "#6c5ce7", pants: "#34495e", accent: "#f7c948" },
    voicePitch: 0.9,
    voice: "Orus",
    context: "the little village school of Tannenau (Paul is the teacher, patient and fond of big questions)",
    greetings: [
      { t: "Guten Morgen! Hast du deine Hausaufgaben gemacht?", en: "Good morning! Have you done your homework?" },
      { t: "Hallo! Heute lernen wir etwas Neues.", en: "Hi! Today we're learning something new." },
      { t: "Na, wie war dein Tag?", en: "So, how was your day?" },
    ],
    chatter: [
      { t: "Wer weiß die Antwort?", en: "Who knows the answer?" },
      { t: "Ruhe, bitte!", en: "Quiet, please!" },
      { t: "Die Pause ist gleich vorbei.", en: "Break is almost over." },
    ],
    locked: { t: "Der Unterricht hat noch nicht angefangen. Komm später wieder!", en: "Class hasn't started yet. Come back later!" },
    teach: { t: "Was lernen wir heute?", en: "What are we learning today?" },
    talk: { t: "Darf ich etwas fragen?", en: "May I ask something?" },
    goodbye: [
      { t: "Bis morgen!", en: "See you tomorrow!" },
      { t: "Schönen Feierabend!", en: "Have a nice evening!" },
    ],
  },
];

// The first meeting doubles as the tutorial: hover-to-translate is taught in German.
export const intro: Line[] = [
  { t: "Hallo! Willkommen in Tannenau!", en: "Hi! Welcome to Tannenau (Fir Meadow)!" },
  { t: "Hier sprechen alle Deutsch.", en: "Everyone speaks German here." },
  { t: "Verstehst du etwas nicht? Halte die Maus über ein Wort.", en: "Don't understand something? Hold the mouse over a word." },
  { t: "Ich heiße Greta. Wie heißt du?", en: "My name is Greta. What's your name?" },
];

export const afterName = (name: string): Line[] => [
  { t: `Schön, dich kennenzulernen, ${name}!`, en: `Nice to meet you, ${name}!` },
  { t: "Siehst du die kleine Linde auf dem Marktplatz? Sie ist traurig.", en: "Do you see the little linden tree on the market square? It is sad." },
  { t: "Die Linde wächst, wenn du Deutsch lernst.", en: "The linden tree grows when you learn German." },
  { t: "Komm, ich bringe dir deine ersten Wörter bei!", en: "Come, I'll teach you your first words!" },
];

export const praise: Line[] = [
  { t: "Genau!", en: "Exactly!" },
  { t: "Super!", en: "Great!" },
  { t: "Perfekt!", en: "Perfect!" },
  { t: "Gut gemacht!", en: "Well done!" },
  { t: "Ja, so sagt man das!", en: "Yes, that's how you say it!" },
  { t: "Völlig richtig!", en: "Completely right!" },
];

export const nudges: Line[] = [
  { t: "Fast! So sagt man das:", en: "Almost! This is how you say it:" },
  { t: "Nicht ganz. Hör mal:", en: "Not quite. Listen:" },
  { t: "Guter Versuch! Man sagt:", en: "Good try! You say:" },
];

export const roundDone: Line[] = [
  { t: "Gut gemacht heute!", en: "Good work today!" },
  { t: "Du lernst so schnell!", en: "You learn so fast!" },
  { t: "Du bist echt gut!", en: "You're really good!" },
];
